#!/usr/bin/env python3
"""
configure_site.py
=================
Single-file Python generator.  Reads the ``investment-platform/`` source files
from this repository and writes a complete, upload-ready PHP website with
**zero JavaScript**.  All interactivity and XMR price conversion are handled
server-side in PHP.

Requirements
------------
    Python 3.7+  (standard library only — no pip packages needed)

Usage
-----
    # From the repository root (most common):
    python configure_site.py

    # Specify a custom output directory and wallet address:
    python configure_site.py --output ./my-site --wallet 4YourMoneroAddressHere

    # If running from outside the repository:
    python configure_site.py --repo-root C:\\path\\to\\repo --output C:\\path\\to\\site

Arguments
---------
    --repo-root  PATH   Repository root directory.  Default: current directory.
    --output     PATH   Output directory (created if absent).
                        Default: ./site-output
    --wallet     ADDR   Monero primary receiving address (starts with "4").
                        If omitted the script attempts to read it from
                        acceptxmr.yaml in the repo root.
    --version           Print the script version and exit.

Generated output layout
-----------------------
    <output>/
    ├── .htaccess              Security headers; deny sensitive file types
    ├── index.php              Tier-selection landing page
    ├── pay.php                Payment-display page (XMR amount + address)
    ├── css/
    │   └── payment.css        Pure CSS — no external fonts or CDN imports
    └── includes/
        ├── .htaccess          Deny all direct HTTP access to this directory
        ├── config.php         Tier data, wallet address, API settings
        └── price.php          Server-side XMR price fetcher with file cache

Post-generation steps
---------------------
    1.  Open includes/config.php and confirm XMR_WALLET_ADDRESS.
    2.  Upload the entire output folder to a PHP 7.4+-enabled web host.
    3.  Grant the web server write access to the includes/ directory
        (required for the price_cache.json file created at runtime).
    4.  Browse to index.php to confirm the site works.
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import sys
import textwrap
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Script metadata
# ---------------------------------------------------------------------------
_VERSION = "1.0.0"

# Placeholder token replaced by the generated-file header in every template.
_HDR = "%%GENERATED_HEADER%%"


def _file_header(filename: str) -> str:
    """Return a standardised PHP block-comment header (no surrounding /* */)."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f" * {filename}",
        f" * Auto-generated by configure_site.py v{_VERSION} on {ts}.",
        " * Re-run configure_site.py to regenerate — manual edits will be overwritten.",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Source-file readers
# ---------------------------------------------------------------------------

def _read_payment_config(repo_root: pathlib.Path) -> dict:
    """Load investment-platform/payment-config.json, or return built-in defaults."""
    path = repo_root / "investment-platform" / "payment-config.json"
    if path.exists():
        with path.open(encoding="utf-8") as fh:
            cfg = json.load(fh)
        try:
            print(f"  [read]  {path.relative_to(repo_root)}")
        except ValueError:
            print(f"  [read]  {path}")
        return cfg
    print(f"  [warn]  {path} not found — using built-in defaults.", file=sys.stderr)
    return _default_config()


def _read_wallet_from_yaml(repo_root: pathlib.Path) -> str:
    """
    Extract ``primary-address:`` from acceptxmr.yaml using only the stdlib.
    Returns an empty string if the file is absent or the key is not found.
    """
    path = repo_root / "acceptxmr.yaml"
    if not path.exists():
        return ""
    text = path.read_text(encoding="utf-8")
    m = re.search(r"^\s*primary-address:\s*(\S+)", text, re.MULTILINE)
    return m.group(1) if m else ""


def _default_config() -> dict:
    return {
        "currency": "USD",
        "tiers": [
            {"name": "Starter",      "amount": 1000},
            {"name": "Basic",        "amount": 2500},
            {"name": "Standard",     "amount": 5000},
            {"name": "Advanced",     "amount": 10000},
            {"name": "Professional", "amount": 25000},
            {"name": "Enterprise",   "amount": 50000},
            {"name": "Premium",      "amount": 100000},
            {"name": "Elite",        "amount": 250000},
            {"name": "Ultimate",     "amount": 500000},
            {"name": "Platinum",     "amount": 1000000},
        ],
        "defaultTierIndex": 0,
        "xmrPrecision": 6,
        "overlayTitle": "Pay with Monero (XMR)",
        "xmrPriceApiUrl": (
            "https://api.coingecko.com/api/v3/simple/price"
            "?ids=monero&vs_currencies=usd"
        ),
        "priceCacheDurationMs": 60000,
    }


# ---------------------------------------------------------------------------
# PHP helper
# ---------------------------------------------------------------------------

def _php_sq(value: str) -> str:
    """Wrap a Python string as a PHP single-quoted string literal."""
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return "'" + escaped + "'"


# ---------------------------------------------------------------------------
# Generator: includes/.htaccess
# ---------------------------------------------------------------------------

def _gen_includes_htaccess() -> str:
    return textwrap.dedent("""\
        # Deny all direct HTTP access to PHP include files.

        # Apache 2.4+
        <IfModule mod_authz_core.c>
            Require all denied
        </IfModule>

        # Apache 2.2 fallback
        <IfModule !mod_authz_core.c>
            Order deny,allow
            Deny from all
        </IfModule>
    """)


# ---------------------------------------------------------------------------
# Generator: .htaccess (site root)
# ---------------------------------------------------------------------------

def _gen_root_htaccess() -> str:
    return textwrap.dedent(r"""
        Options -Indexes

        # --- Security headers ---
        <IfModule mod_headers.c>
            Header always set X-Content-Type-Options  "nosniff"
            Header always set X-Frame-Options         "SAMEORIGIN"
            Header always set Referrer-Policy         "strict-origin-when-cross-origin"
            Header always set Content-Security-Policy "default-src 'self'; script-src 'none'; object-src 'none'; style-src 'self'; img-src 'self' data:; connect-src 'none';"
        </IfModule>

        # --- Deny direct access to data / config files ---
        <FilesMatch "\.(json|yaml|yml|env|ini|log|sh|py|toml|lock)$">
            <IfModule mod_authz_core.c>
                Require all denied
            </IfModule>
            <IfModule !mod_authz_core.c>
                Order deny,allow
                Deny from all
            </IfModule>
        </FilesMatch>

        # --- PHP error display: off in production ---
        php_flag display_errors Off
        php_flag log_errors     On
    """).lstrip("\n")


# ---------------------------------------------------------------------------
# Generator: includes/config.php
# ---------------------------------------------------------------------------

def _gen_config_php(config: dict, wallet_address: str) -> str:
    tiers           = config.get("tiers", _default_config()["tiers"])
    default_index   = int(config.get("defaultTierIndex", 0))
    precision       = int(config.get("xmrPrecision", 6))
    currency        = str(config.get("currency", "USD"))
    title           = str(config.get("overlayTitle", "Pay with Monero (XMR)"))
    api_url         = str(config.get(
        "xmrPriceApiUrl",
        "https://api.coingecko.com/api/v3/simple/price?ids=monero&vs_currencies=usd",
    ))
    cache_ttl_s     = max(10, int(config.get("priceCacheDurationMs", 60000)) // 1000)

    # Build the PHP array literal for tiers.
    tier_lines = []
    for t in tiers:
        name   = str(t.get("name", "Tier"))
        amount = int(t.get("amount", 1000))
        tier_lines.append(
            "    ['name' => " + _php_sq(name) + ", 'amount' => " + str(amount) + "],"
        )
    tiers_block = "\n".join(tier_lines)

    parts = [
        "<?php",
        "/**",
        _file_header("includes/config.php"),
        " *",
        " * ==============================================================",
        " * IMPORTANT: set XMR_WALLET_ADDRESS to your Monero address",
        " * before deploying to a live server.",
        " * ==============================================================",
        " */",
        "declare(strict_types=1);",
        "",
        "// ---------------------------------------------------------------------------",
        "// Investment tiers  (name => USD amount)",
        "// ---------------------------------------------------------------------------",
        "define('XMR_TIERS', [",
        tiers_block,
        "]);",
        "",
        "// Default tier index (0-based). Used when no ?tier= is in the URL.",
        "define('DEFAULT_TIER_INDEX', " + str(default_index) + ");",
        "",
        "// ---------------------------------------------------------------------------",
        "// Display settings",
        "// ---------------------------------------------------------------------------",
        "",
        "// Decimal places shown for XMR amounts.",
        "define('XMR_PRECISION', " + str(precision) + ");",
        "",
        "// Fiat currency code (display only).",
        "define('XMR_CURRENCY', " + _php_sq(currency) + ");",
        "",
        "// Page title.",
        "define('XMR_OVERLAY_TITLE', " + _php_sq(title) + ");",
        "",
        "// ---------------------------------------------------------------------------",
        "// Wallet — SET THIS BEFORE GOING LIVE",
        "// ---------------------------------------------------------------------------",
        "",
        "// Your Monero primary address (starts with '4' on mainnet).",
        "define('XMR_WALLET_ADDRESS', " + _php_sq(wallet_address) + ");",
        "",
        "// ---------------------------------------------------------------------------",
        "// Price API",
        "// ---------------------------------------------------------------------------",
        "",
        "// Primary source: CoinGecko public API (no API key required).",
        "define('XMR_PRICE_API_PRIMARY',  " + _php_sq(api_url) + ");",
        "",
        "// Fallback mirror: CryptoCompare.",
        "define('XMR_PRICE_API_FALLBACK', 'https://min-api.cryptocompare.com/data/price?fsym=XMR&tsyms=USD');",
        "",
        "// Seconds to cache the fetched price (reduces API calls).",
        "define('XMR_PRICE_CACHE_TTL', " + str(cache_ttl_s) + ");",
        "",
        "// Absolute path to the price-cache file.",
        "// The web-server process must have write permission to this path.",
        "define('XMR_PRICE_CACHE_FILE', __DIR__ . DIRECTORY_SEPARATOR . 'price_cache.json');",
        "",
        "// HTTP request timeout in seconds when fetching a live price.",
        "define('XMR_FETCH_TIMEOUT', 10);",
    ]
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Generator: includes/price.php
# (Written as a plain Python string — no f-string brace escaping required.)
# ---------------------------------------------------------------------------

_PRICE_PHP = """\
<?php
/**
%%GENERATED_HEADER%%
 *
 * Provides fetch_xmr_price():
 *   Returns [float $usd_per_xmr, string|null $error, int $cache_age_seconds]
 *
 * Caches the price on disk for XMR_PRICE_CACHE_TTL seconds.
 * Uses cURL when available; falls back to file_get_contents otherwise.
 */
declare(strict_types=1);

/**
 * Fetch (or return cached) XMR/USD price.
 *
 * @return array{float, string|null, int}
 *   [0] USD price per 1 XMR  (0.0 on total failure)
 *   [1] Error message or null on success
 *   [2] Cache age in seconds  (0 = freshly fetched)
 */
function fetch_xmr_price(): array
{
    $cache_file = XMR_PRICE_CACHE_FILE;
    $ttl        = XMR_PRICE_CACHE_TTL;

    // --- Try the on-disk cache first ---
    $cached = _xmr_read_cache($cache_file);
    if ($cached !== null) {
        $age = time() - (int)($cached['timestamp'] ?? 0);
        if ($age < $ttl && ($cached['price'] ?? 0) > 0) {
            return [(float)$cached['price'], null, $age];
        }
    }

    // --- Fetch a fresh price ---
    $price = _xmr_fetch_from_url(XMR_PRICE_API_PRIMARY);
    if ($price === null) {
        $price = _xmr_fetch_from_url(XMR_PRICE_API_FALLBACK);
    }

    if ($price !== null && $price > 0) {
        _xmr_write_cache($cache_file, $price);
        return [$price, null, 0];
    }

    // --- Both APIs failed: serve stale cache rather than nothing ---
    if ($cached !== null && ($cached['price'] ?? 0) > 0) {
        $age = time() - (int)($cached['timestamp'] ?? 0);
        return [
            (float)$cached['price'],
            'Live price unavailable \xe2\x80\x94 showing cached rate',
            $age,
        ];
    }

    return [0.0, 'XMR price could not be fetched. Please try again shortly.', 0];
}

// ---------------------------------------------------------------------------
// Internal helpers — prefixed _xmr_ to avoid name collisions.
// ---------------------------------------------------------------------------

/** @return array<string,mixed>|null */
function _xmr_read_cache(string $path): ?array
{
    if (!is_file($path)) {
        return null;
    }
    $raw = @file_get_contents($path);
    if ($raw === false) {
        return null;
    }
    $data = @json_decode($raw, true);
    return is_array($data) ? $data : null;
}

function _xmr_write_cache(string $path, float $price): void
{
    $payload = json_encode(['price' => $price, 'timestamp' => time()]);
    if ($payload !== false) {
        @file_put_contents($path, $payload, LOCK_EX);
    }
}

/**
 * Parse the XMR/USD price from a single HTTP endpoint.
 * Understands both CoinGecko and CryptoCompare response shapes.
 */
function _xmr_fetch_from_url(string $url): ?float
{
    $body = _xmr_http_get($url);
    if ($body === null) {
        return null;
    }
    $data = @json_decode($body, true);
    if (!is_array($data)) {
        return null;
    }
    // CoinGecko format:    {"monero":{"usd":170.5}}
    if (isset($data['monero']['usd']) && is_numeric($data['monero']['usd'])) {
        return (float)$data['monero']['usd'];
    }
    // CryptoCompare format: {"USD":170.5}
    if (isset($data['USD']) && is_numeric($data['USD'])) {
        return (float)$data['USD'];
    }
    return null;
}

/**
 * Perform a GET request.
 * Prefers cURL; falls back to file_get_contents when cURL is unavailable.
 * Returns the response body on success, null on any failure.
 */
function _xmr_http_get(string $url): ?string
{
    if (function_exists('curl_init')) {
        $ch = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT        => XMR_FETCH_TIMEOUT,
            CURLOPT_CONNECTTIMEOUT => 5,
            CURLOPT_SSL_VERIFYPEER => true,
            CURLOPT_SSL_VERIFYHOST => 2,
            CURLOPT_USERAGENT      => 'AcceptXMR-PHP/1.0',
            CURLOPT_FOLLOWLOCATION => false,
        ]);
        $body  = curl_exec($ch);
        $errno = curl_errno($ch);
        curl_close($ch);
        return ($errno === 0 && is_string($body) && $body !== '') ? $body : null;
    }

    if (ini_get('allow_url_fopen')) {
        $ctx = stream_context_create([
            'http' => [
                'timeout'    => XMR_FETCH_TIMEOUT,
                'user_agent' => 'AcceptXMR-PHP/1.0',
            ],
            'ssl' => [
                'verify_peer'      => true,
                'verify_peer_name' => true,
            ],
        ]);
        $body = @file_get_contents($url, false, $ctx);
        return (is_string($body) && $body !== '') ? $body : null;
    }

    // Neither cURL nor allow_url_fopen is available.
    return null;
}
"""


# ---------------------------------------------------------------------------
# Generator: css/payment.css
# (Dark theme by default; pure CSS — zero external imports or JS dependencies.)
# ---------------------------------------------------------------------------

_PAYMENT_CSS = """\
/*
%%GENERATED_HEADER%%
 *
 * Pure CSS — no @import url() from CDNs, no external fonts, no JS animations.
 * All selectors follow the .xmr-* / .payment-* namespace convention to avoid
 * collisions when this sheet is embedded in a larger site.
 */

/* ============================================================
   CSS Custom Properties — theming tokens
   ============================================================ */
:root {
  /* Brand / accent */
  --xmr-primary:        #f26822;   /* Monero orange                          */
  --xmr-primary-dark:   #c85410;   /* Hover / active state                   */
  --xmr-primary-light:  #fde8d8;   /* Tinted background highlight            */

  /* XMR-amount colour — intentionally brighter than the brand primary */
  --xmr-amount-color:   #ff6600;   /* XMR value display                      */

  /* Surfaces — dark theme by default */
  --xmr-bg:             #1a1a1a;   /* Page background                        */
  --xmr-surface:        #252525;   /* Card surface                           */
  --xmr-surface-alt:    #2e2e2e;   /* Slightly lighter surface               */
  --xmr-surface-inset:  #181818;   /* Inset / code block background          */

  /* Text */
  --xmr-text:           #ececec;   /* Primary text                           */
  --xmr-text-muted:     #9e9e9e;   /* Secondary / label text                 */
  --xmr-text-link:      #f26822;   /* Link colour                            */

  /* Borders */
  --xmr-border:         #3a3a3a;   /* Default border                         */
  --xmr-border-accent:  #f26822;   /* Accent border (XMR amount row)         */

  /* Status */
  --xmr-success:        #4caf50;
  --xmr-warning:        #ff9800;
  --xmr-error:          #f44336;

  /* Layout */
  --xmr-radius:         10px;
  --xmr-radius-sm:       6px;
  --xmr-shadow:         0 8px 40px rgba(0, 0, 0, 0.55);

  /* Typography */
  --xmr-font:  system-ui, -apple-system, "Segoe UI", Roboto,
               "Helvetica Neue", Arial, sans-serif;
  --xmr-mono:  "SFMono-Regular", Consolas, "Liberation Mono",
               Menlo, "Courier New", monospace;

  /* Animation */
  --xmr-transition: 0.18s ease;
}

/* ============================================================
   Page baseline
   ============================================================ */
*,
*::before,
*::after {
  box-sizing: border-box;
}

body {
  margin:                  0;
  padding:                 0;
  background:              var(--xmr-bg);
  color:                   var(--xmr-text);
  font-family:             var(--xmr-font);
  line-height:             1.6;
  -webkit-font-smoothing:  antialiased;
}

a {
  color:           var(--xmr-text-link);
  text-decoration: none;
}

a:hover,
a:focus {
  text-decoration: underline;
}

kbd {
  display:          inline-block;
  padding:          1px 5px;
  font-family:      var(--xmr-mono);
  font-size:        0.82em;
  background:       var(--xmr-surface-alt);
  border:           1px solid var(--xmr-border);
  border-radius:    3px;
  color:            var(--xmr-text);
}

/* ============================================================
   .page-wrapper — full-height centering shell
   ============================================================ */
.page-wrapper {
  min-height:      100vh;
  display:         flex;
  flex-direction:  column;
  align-items:     center;
  justify-content: center;
  padding:         24px 16px;
}

/* ============================================================
   .payment-card — centered card, max-width 600 px
   ============================================================ */
.payment-card {
  width:           100%;
  max-width:       600px;
  background:      var(--xmr-surface);
  border-radius:   var(--xmr-radius);
  box-shadow:      var(--xmr-shadow);
  overflow:        hidden;
  display:         flex;
  flex-direction:  column;
}

.payment-card__header {
  background:   var(--xmr-primary);
  padding:      20px 24px 16px;
}

.payment-card__title {
  margin:          0;
  font-size:       1.2rem;
  font-weight:     700;
  color:           #ffffff;
  letter-spacing:  0.02em;
}

.payment-card__subtitle {
  margin:     4px 0 0;
  font-size:  0.88rem;
  color:      rgba(255, 255, 255, 0.82);
}

.payment-card__body {
  padding:         24px;
  display:         flex;
  flex-direction:  column;
  gap:             18px;
}

.payment-card__footer {
  padding:     14px 24px 18px;
  background:  var(--xmr-surface-alt);
  border-top:  1px solid var(--xmr-border);
}

.payment-card__footnote {
  margin:      0;
  font-size:   0.78rem;
  color:       var(--xmr-text-muted);
  text-align:  center;
  line-height: 1.5;
}

/* ============================================================
   Tier badge
   ============================================================ */
.tier-badge {
  display:        inline-flex;
  align-self:     flex-start;
  background:     var(--xmr-primary);
  color:          #ffffff;
  font-size:      0.76rem;
  font-weight:    700;
  padding:        3px 14px;
  border-radius:  20px;
  letter-spacing: 0.06em;
  text-transform: uppercase;
}

/* ============================================================
   .amount-display — large bold USD amount
   ============================================================ */
.amount-display {
  display:         flex;
  flex-direction:  column;
  gap:             4px;
  padding:         16px 18px;
  background:      var(--xmr-surface-alt);
  border-radius:   var(--xmr-radius);
  border:          1px solid var(--xmr-border);
}

.amount-display__label {
  font-size:      0.8rem;
  font-weight:    600;
  color:          var(--xmr-text-muted);
  text-transform: uppercase;
  letter-spacing: 0.06em;
}

.amount-display__value {
  font-size:      2rem;
  font-weight:    800;
  color:          var(--xmr-text);
  line-height:    1.1;
  letter-spacing: -0.01em;
}

/* ============================================================
   .xmr-amount — extra-large monospace XMR amount in XMR orange
   ============================================================ */
.xmr-amount {
  display:         flex;
  flex-direction:  column;
  gap:             4px;
  padding:         16px 18px;
  background:      #1e1000;
  border-radius:   var(--xmr-radius);
  border:          1px solid var(--xmr-amount-color);
}

.xmr-amount__label {
  font-size:      0.8rem;
  font-weight:    600;
  color:          var(--xmr-text-muted);
  text-transform: uppercase;
  letter-spacing: 0.06em;
}

.xmr-amount__value {
  font-size:      2.2rem;
  font-weight:    800;
  color:          var(--xmr-amount-color);
  font-family:    var(--xmr-mono);
  line-height:    1.1;
  letter-spacing: -0.01em;
  word-break:     break-all;
}

.xmr-amount__unit {
  font-size:   1rem;
  font-weight: 400;
  color:       var(--xmr-text-muted);
  font-family: var(--xmr-mono);
}

.xmr-rate-note {
  margin:     0;
  font-size:  0.78rem;
  color:      var(--xmr-text-muted);
  font-style: italic;
}

/* ============================================================
   .wallet-address — <code> block, word-break, user-select: all
   ============================================================ */
.wallet-address {
  display:         flex;
  flex-direction:  column;
  gap:             8px;
  padding:         16px 18px;
  background:      var(--xmr-surface-alt);
  border-radius:   var(--xmr-radius);
  border:          1px solid var(--xmr-border);
}

.wallet-address__label {
  font-size:      0.8rem;
  font-weight:    600;
  color:          var(--xmr-text-muted);
  text-transform: uppercase;
  letter-spacing: 0.06em;
}

/*
 * The <code> element uses user-select: all so that a single click selects
 * the entire address — the user can then press Ctrl+C / Cmd+C to copy.
 * No JavaScript is required.
 */
.wallet-address__code {
  display:             block;
  padding:             10px 12px;
  background:          var(--xmr-surface-inset);
  border-radius:       var(--xmr-radius-sm);
  border:              1px solid var(--xmr-border);
  font-family:         var(--xmr-mono);
  font-size:           0.82rem;
  color:               var(--xmr-text);
  word-break:          break-all;
  overflow-wrap:       anywhere;
  cursor:              text;
  user-select:         all;
  -webkit-user-select: all;
  -moz-user-select:    all;
  line-height:         1.5;
}

.wallet-address__code:focus {
  outline:        2px solid var(--xmr-primary);
  outline-offset: 2px;
}

.wallet-address__hint {
  margin:     0;
  font-size:  0.76rem;
  color:      var(--xmr-text-muted);
  line-height: 1.5;
}

/* ============================================================
   .tier-selector — styled <select> + submit form
   ============================================================ */
.tier-selector {
  display:        flex;
  flex-direction: column;
  gap:            16px;
}

.tier-selector__label {
  display:        block;
  font-size:      0.88rem;
  font-weight:    600;
  color:          var(--xmr-text);
  margin-bottom:  4px;
}

.tier-selector__select {
  width:              100%;
  padding:            10px 36px 10px 14px;
  background-color:   var(--xmr-surface-inset);
  color:              var(--xmr-text);
  border:             1px solid var(--xmr-border);
  border-radius:      var(--xmr-radius-sm);
  font-family:        var(--xmr-font);
  font-size:          1rem;
  cursor:             pointer;
  appearance:         none;
  -webkit-appearance: none;
  /* Custom dropdown arrow — SVG data-URI, no JS required */
  background-image:    url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8' viewBox='0 0 12 8'%3E%3Cpath fill='%23f26822' d='M0 0l6 8 6-8z'/%3E%3C/svg%3E");
  background-repeat:   no-repeat;
  background-position: right 14px center;
}

.tier-selector__select:focus {
  outline:      2px solid var(--xmr-primary);
  outline-offset: 2px;
  border-color: var(--xmr-primary);
}

.tier-selector__select option {
  background: var(--xmr-surface);
  color:      var(--xmr-text);
}

/* ============================================================
   .btn — generic button / link-button
   ============================================================ */
.btn {
  display:         inline-flex;
  align-items:     center;
  justify-content: center;
  padding:         11px 24px;
  border:          none;
  border-radius:   var(--xmr-radius-sm);
  font-family:     var(--xmr-font);
  font-size:       0.95rem;
  font-weight:     600;
  cursor:          pointer;
  text-decoration: none;
  transition:      background var(--xmr-transition),
                   opacity    var(--xmr-transition),
                   transform  var(--xmr-transition);
  white-space:     nowrap;
}

.btn:active {
  transform: scale(0.98);
}

.btn--primary {
  background: var(--xmr-primary);
  color:      #ffffff;
  width:      100%;
}

.btn--primary:hover,
.btn--primary:focus {
  background:      var(--xmr-primary-dark);
  color:           #ffffff;
  text-decoration: none;
}

.btn--secondary {
  background: transparent;
  color:      var(--xmr-text-muted);
  border:     1px solid var(--xmr-border);
  font-size:  0.85rem;
  padding:    8px 16px;
}

.btn--secondary:hover,
.btn--secondary:focus {
  background:      var(--xmr-surface-alt);
  color:           var(--xmr-text);
  text-decoration: none;
}

/* ============================================================
   Notices / inline alerts
   ============================================================ */
.notice {
  padding:     12px 16px;
  border-radius: var(--xmr-radius-sm);
  font-size:   0.85rem;
  line-height: 1.5;
  border-left: 4px solid;
}

.notice--warning {
  background:   #2a1f00;
  color:        #ffcc66;
  border-color: var(--xmr-warning);
}

.notice--error {
  background:   #2a0000;
  color:        #ff9999;
  border-color: var(--xmr-error);
}

.notice--info {
  background:   #001a2a;
  color:        #99ccff;
  border-color: #4499ff;
}

/* ============================================================
   Nav / breadcrumb
   ============================================================ */
.nav-back {
  width:         100%;
  max-width:     600px;
  margin-bottom: 12px;
  font-size:     0.85rem;
}

.nav-back a {
  color: var(--xmr-text-muted);
}

.nav-back a:hover {
  color: var(--xmr-text);
}

/* ============================================================
   Reduced-motion override
   ============================================================ */
@media (prefers-reduced-motion: reduce) {
  .btn {
    transition: none;
  }
}

/* ============================================================
   Light-mode override (applied when OS preference is light)
   ============================================================ */
@media (prefers-color-scheme: light) {
  :root {
    --xmr-bg:            #f0ece8;
    --xmr-surface:       #ffffff;
    --xmr-surface-alt:   #f8f5f0;
    --xmr-surface-inset: #f0ece8;
    --xmr-text:          #1a1a1a;
    --xmr-text-muted:    #6b6b6b;
    --xmr-border:        #e0d8d0;
  }

  .xmr-amount {
    background:   #fff3e6;
    border-color: var(--xmr-amount-color);
  }

  .notice--warning { background: #fff8e0; color: #7a4f00; }
  .notice--error   { background: #fff0f0; color: #8b0000; }
  .notice--info    { background: #e8f4ff; color: #003b6b; }
}

/* ============================================================
   Mobile responsiveness
   ============================================================ */
@media (max-width: 640px) {
  .payment-card__header {
    padding: 16px 18px 14px;
  }

  .payment-card__body {
    padding: 18px;
    gap:     14px;
  }

  .amount-display__value {
    font-size: 1.6rem;
  }

  .xmr-amount__value {
    font-size: 1.7rem;
  }

  .wallet-address__code {
    font-size: 0.75rem;
  }
}
"""


# ---------------------------------------------------------------------------
# Generator: index.php
# ---------------------------------------------------------------------------

_INDEX_PHP = """\
<?php
/**
%%GENERATED_HEADER%%
 *
 * Tier-selection landing page.
 * Presents an investment-tier drop-down; on submit redirects to pay.php.
 * Zero JavaScript — pure PHP + HTML form.
 */
declare(strict_types=1);
require_once __DIR__ . '/includes/config.php';

$tiers    = XMR_TIERS;
$currency = XMR_CURRENCY;
$title    = XMR_OVERLAY_TITLE;
$ttl      = XMR_PRICE_CACHE_TTL;

// Preserve selected tier if the user navigates back from pay.php.
$selected = DEFAULT_TIER_INDEX;
if (isset($_GET['tier'])) {
    $t = (int)$_GET['tier'];
    if ($t >= 0 && $t < count($tiers)) {
        $selected = $t;
    }
}
?><!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="referrer" content="strict-origin-when-cross-origin">
  <title><?php echo htmlspecialchars($title, ENT_QUOTES, 'UTF-8'); ?></title>
  <link rel="stylesheet" href="css/payment.css">
</head>
<body>
<div class="page-wrapper">
  <main class="payment-card" role="main" aria-label="Investment tier selection">

    <!-- Header -->
    <div class="payment-card__header">
      <h1 class="payment-card__title">
        <?php echo htmlspecialchars($title, ENT_QUOTES, 'UTF-8'); ?>
      </h1>
      <p class="payment-card__subtitle">
        Select your investment tier, then complete payment in Monero (XMR).
      </p>
    </div>

    <!-- Body -->
    <div class="payment-card__body">
      <form method="get" action="pay.php" class="tier-selector" autocomplete="off">

        <div>
          <label class="tier-selector__label" for="tier-select">
            Investment Tier
          </label>
          <select name="tier" id="tier-select" class="tier-selector__select" required>
            <?php foreach ($tiers as $i => $tier): ?>
            <option value="<?php echo (int)$i; ?>"
              <?php if ($i === $selected) { echo 'selected'; } ?>>
              <?php
                echo htmlspecialchars($tier['name'], ENT_QUOTES, 'UTF-8');
                echo ' \xe2\x80\x94 ';
                echo htmlspecialchars($currency, ENT_QUOTES, 'UTF-8');
                echo '\xc2\xa0';
                echo number_format((int)$tier['amount']);
              ?>
            </option>
            <?php endforeach; ?>
          </select>
        </div>

        <button type="submit" class="btn btn--primary">
          Continue to Payment &rarr;
        </button>

      </form>
    </div><!-- /.payment-card__body -->

    <!-- Footer -->
    <div class="payment-card__footer">
      <p class="payment-card__footnote">
        Payments are accepted in Monero (XMR) at the live exchange rate.
        Prices are refreshed every <?php echo (int)$ttl; ?> seconds.
        This page contains no JavaScript.
      </p>
    </div>

  </main><!-- /.payment-card -->
</div><!-- /.page-wrapper -->
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Generator: pay.php
# ---------------------------------------------------------------------------

_PAY_PHP = """\
<?php
/**
%%GENERATED_HEADER%%
 *
 * Payment-display page.
 *
 * URL parameters (GET):
 *   ?tier=N       0-based index into XMR_TIERS  (default: DEFAULT_TIER_INDEX)
 *   ?amount=X     Custom USD amount (takes priority over tier if both supplied)
 *
 * Features:
 *   - Server-side XMR price fetch with file-based cache (includes/price.php)
 *   - Wallet address displayed in a <code> block; CSS user-select:all lets
 *     users click once to select the whole address, then Ctrl+C / Cmd+C to copy
 *   - Monero URI <a href> opens the wallet app on supported devices
 *   - Zero JavaScript
 */
declare(strict_types=1);
require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/price.php';

$tiers     = XMR_TIERS;
$currency  = XMR_CURRENCY;
$title     = XMR_OVERLAY_TITLE;
$wallet    = XMR_WALLET_ADDRESS;
$precision = XMR_PRECISION;

// ---------------------------------------------------------------------------
// Resolve USD amount
// ---------------------------------------------------------------------------
$tier_obj   = null;
$usd_amount = 0.0;

if (isset($_GET['amount'])) {
    $raw = (float)filter_var($_GET['amount'], FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION);
    if ($raw > 0) {
        $usd_amount = $raw;
    }
}

if ($usd_amount <= 0 && isset($_GET['tier'])) {
    $tier_idx = (int)$_GET['tier'];
    if ($tier_idx >= 0 && $tier_idx < count($tiers)) {
        $tier_obj   = $tiers[$tier_idx];
        $usd_amount = (float)$tier_obj['amount'];
    }
}

if ($usd_amount <= 0) {
    $def_idx    = max(0, min(DEFAULT_TIER_INDEX, count($tiers) - 1));
    $tier_obj   = $tiers[$def_idx];
    $usd_amount = (float)$tier_obj['amount'];
}

// ---------------------------------------------------------------------------
// Fetch live XMR price (server-side)
// ---------------------------------------------------------------------------
[$xmr_price, $price_error, $cache_age] = fetch_xmr_price();

// ---------------------------------------------------------------------------
// Calculate XMR equivalent
// ---------------------------------------------------------------------------
$xmr_amount    = ($xmr_price > 0) ? ($usd_amount / $xmr_price) : null;
$xmr_formatted = ($xmr_amount !== null)
    ? number_format($xmr_amount, $precision, '.', '')
    : null;

$rate_note = null;
if ($xmr_price > 0) {
    $rate_note  = '1&nbsp;XMR&nbsp;=&nbsp;' . htmlspecialchars($currency, ENT_QUOTES, 'UTF-8');
    $rate_note .= '&nbsp;' . number_format($xmr_price, 2);
    $rate_note .= $cache_age > 0
        ? ' (cached&nbsp;' . (int)$cache_age . 's&nbsp;ago)'
        : ' (live)';
}

// ---------------------------------------------------------------------------
// Format USD for display
// ---------------------------------------------------------------------------
$usd_display = htmlspecialchars($currency, ENT_QUOTES, 'UTF-8')
             . '&nbsp;'
             . number_format((float)$usd_amount, 2);

// ---------------------------------------------------------------------------
// Build "back" link preserving the selected tier index
// ---------------------------------------------------------------------------
$back_tier = null;
foreach ($tiers as $i => $t) {
    if ((int)$t['amount'] === (int)$usd_amount) {
        $back_tier = (int)$i;
        break;
    }
}
$index_href = 'index.php' . ($back_tier !== null ? '?tier=' . $back_tier : '');

// ---------------------------------------------------------------------------
// Monero URI (opens compatible wallet app — no JS required)
// ---------------------------------------------------------------------------
$monero_uri = null;
if ($wallet !== '' && $xmr_formatted !== null) {
    $monero_uri = 'monero:'
        . rawurlencode($wallet)
        . '?tx_amount=' . rawurlencode($xmr_formatted);
}
?><!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="referrer" content="strict-origin-when-cross-origin">
  <title>
    <?php echo htmlspecialchars($title, ENT_QUOTES, 'UTF-8'); ?> &mdash; Payment
  </title>
  <link rel="stylesheet" href="css/payment.css">
</head>
<body>
<div class="page-wrapper">

  <!-- Breadcrumb -->
  <nav class="nav-back" aria-label="Navigation">
    <a href="<?php echo htmlspecialchars($index_href, ENT_QUOTES, 'UTF-8'); ?>">
      &larr; Change tier
    </a>
  </nav>

  <main class="payment-card" role="main" aria-label="Payment details">

    <!-- Header -->
    <div class="payment-card__header">
      <h1 class="payment-card__title">
        <?php echo htmlspecialchars($title, ENT_QUOTES, 'UTF-8'); ?>
      </h1>
      <?php if ($tier_obj !== null): ?>
      <p class="payment-card__subtitle">
        <?php echo htmlspecialchars($tier_obj['name'], ENT_QUOTES, 'UTF-8'); ?> Plan
      </p>
      <?php endif; ?>
    </div>

    <!-- Body -->
    <div class="payment-card__body">

      <?php if ($tier_obj !== null): ?>
      <div class="tier-badge">
        <?php echo htmlspecialchars($tier_obj['name'], ENT_QUOTES, 'UTF-8'); ?> Plan
      </div>
      <?php endif; ?>

      <!-- USD Amount -->
      <div class="amount-display">
        <span class="amount-display__label">Amount Due</span>
        <span class="amount-display__value"><?php echo $usd_display; ?></span>
      </div>

      <!-- XMR Equivalent (server-side conversion) -->
      <div class="xmr-amount">
        <span class="xmr-amount__label">Pay in Monero (XMR)</span>
        <?php if ($xmr_formatted !== null): ?>
          <span class="xmr-amount__value">
            <?php echo htmlspecialchars($xmr_formatted, ENT_QUOTES, 'UTF-8'); ?>
            <span class="xmr-amount__unit">XMR</span>
          </span>
          <?php if ($rate_note !== null): ?>
          <p class="xmr-rate-note"><?php echo $rate_note; ?></p>
          <?php endif; ?>
        <?php else: ?>
          <span class="xmr-amount__value" style="font-size:1.1rem;color:var(--xmr-error);">
            Price unavailable
          </span>
        <?php endif; ?>
      </div>

      <!-- Price fetch error notice -->
      <?php if ($price_error !== null): ?>
      <div class="notice notice--warning" role="alert">
        <?php echo htmlspecialchars($price_error, ENT_QUOTES, 'UTF-8'); ?> &mdash;
        <a href="<?php
            $safe_uri = htmlspecialchars(
                filter_var($_SERVER['REQUEST_URI'] ?? 'pay.php', FILTER_SANITIZE_URL),
                ENT_QUOTES,
                'UTF-8'
            );
            echo $safe_uri;
        ?>">Reload</a> to retry.
      </div>
      <?php endif; ?>

      <!-- Wallet address -->
      <?php if ($wallet !== ''): ?>
      <div class="wallet-address">
        <span class="wallet-address__label">Send XMR to this address</span>

        <!--
          CSS "user-select: all" makes a single click select the entire address.
          The user then presses Ctrl+C (Windows/Linux) or Cmd+C (Mac) to copy.
          No JavaScript is used.
        -->
        <code class="wallet-address__code"
              tabindex="0"
              title="Click to select all, then Ctrl+C / Cmd+C to copy"
              aria-label="Monero wallet address">
          <?php echo htmlspecialchars($wallet, ENT_QUOTES, 'UTF-8'); ?>
        </code>

        <p class="wallet-address__hint">
          &#9757; Click the address to select it, then press
          <kbd>Ctrl</kbd>+<kbd>C</kbd> (<kbd>Cmd</kbd>+<kbd>C</kbd> on Mac) to copy.
        </p>
      </div>

      <!-- Copy XMR amount -->
      <?php if ($xmr_formatted !== null): ?>
      <div class="wallet-address">
        <span class="wallet-address__label">XMR amount to send</span>
        <code class="wallet-address__code"
              tabindex="0"
              title="Click to select all, then Ctrl+C / Cmd+C to copy"
              aria-label="XMR amount">
          <?php echo htmlspecialchars($xmr_formatted, ENT_QUOTES, 'UTF-8'); ?>
        </code>
        <p class="wallet-address__hint">
          &#9757; Click to select, then press <kbd>Ctrl</kbd>+<kbd>C</kbd> to copy.
          Send the <strong>exact amount</strong> shown.
        </p>
      </div>
      <?php endif; ?>

      <!-- Monero URI — opens wallet app on supported devices (no JS) -->
      <?php if ($monero_uri !== null): ?>
      <a href="<?php echo htmlspecialchars($monero_uri, ENT_QUOTES, 'UTF-8'); ?>"
         class="btn btn--secondary"
         title="Open this payment request in your Monero wallet application, if installed">
        Open in Wallet App
      </a>
      <?php endif; ?>

      <?php else: /* wallet address not configured */ ?>
      <div class="notice notice--warning" role="alert">
        <strong>Wallet address not configured.</strong>
        Open <code>includes/config.php</code> and set
        <code>XMR_WALLET_ADDRESS</code> to your Monero primary address.
      </div>
      <?php endif; ?>

    </div><!-- /.payment-card__body -->

    <!-- Footer -->
    <div class="payment-card__footer">
      <p class="payment-card__footnote">
        Send the <strong>exact XMR amount</strong> shown above to the address provided.
        Prices refresh every <?php echo (int)XMR_PRICE_CACHE_TTL; ?>&nbsp;seconds.
        This page contains no JavaScript.
      </p>
    </div>

  </main><!-- /.payment-card -->
</div><!-- /.page-wrapper -->
</body>
</html>
"""


# ---------------------------------------------------------------------------
# File-write helper
# ---------------------------------------------------------------------------

def _write(path: pathlib.Path, content: str) -> None:
    """Create parent directories as needed and write UTF-8 text with LF endings."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    try:
        rel = path.relative_to(pathlib.Path.cwd())
    except ValueError:
        rel = path
    print(f"  wrote  {rel}")


def _apply_header(template: str, filename: str) -> str:
    """Replace the %%GENERATED_HEADER%% marker with the real header lines."""
    return template.replace(_HDR, _file_header(filename))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="configure_site.py",
        description=(
            "Generate a zero-JavaScript PHP website from the AcceptXMR "
            "investment-platform source files."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples
            --------
              python configure_site.py
              python configure_site.py --output ./dist --wallet 4AdUndXHHZ...
              python configure_site.py --repo-root C:\\repos\\acceptxmr --output C:\\www
        """),
    )
    p.add_argument(
        "--repo-root",
        metavar="PATH",
        default=".",
        help="Repository root directory (default: current directory).",
    )
    p.add_argument(
        "--output",
        metavar="PATH",
        default="./site-output",
        help="Output directory, created if absent (default: ./site-output).",
    )
    p.add_argument(
        "--wallet",
        metavar="ADDR",
        default="",
        help=(
            "Monero primary address for receiving payments. "
            "If omitted the script reads it from acceptxmr.yaml."
        ),
    )
    p.add_argument(
        "--version",
        action="version",
        version=f"configure_site.py {_VERSION}",
    )
    return p


def main(argv: list | None = None) -> int:
    parser = _build_parser()
    args   = parser.parse_args(argv)

    repo_root = pathlib.Path(args.repo_root).resolve()
    output    = pathlib.Path(args.output).resolve()
    wallet    = args.wallet.strip()

    print(f"\nconfigure_site.py v{_VERSION}")
    print("=" * 60)

    # -----------------------------------------------------------------------
    # Resolve wallet address
    # -----------------------------------------------------------------------
    if not wallet:
        wallet = _read_wallet_from_yaml(repo_root)
        if wallet:
            print(f"  [info]  Wallet address read from acceptxmr.yaml: {wallet[:12]}…")
        else:
            print(
                "  [warn]  No wallet address provided and none found in acceptxmr.yaml.\n"
                "          Set XMR_WALLET_ADDRESS in includes/config.php before deploying.",
                file=sys.stderr,
            )

    # -----------------------------------------------------------------------
    # Read source config
    # -----------------------------------------------------------------------
    print(f"\nReading source files from: {repo_root}")
    config = _read_payment_config(repo_root)

    # -----------------------------------------------------------------------
    # Write output files
    # -----------------------------------------------------------------------
    print(f"\nWriting output to: {output}")

    _write(
        output / "includes" / ".htaccess",
        _gen_includes_htaccess(),
    )
    _write(
        output / "includes" / "config.php",
        _gen_config_php(config, wallet),
    )
    _write(
        output / "includes" / "price.php",
        _apply_header(_PRICE_PHP, "includes/price.php"),
    )
    _write(
        output / ".htaccess",
        _gen_root_htaccess(),
    )
    _write(
        output / "css" / "payment.css",
        _apply_header(_PAYMENT_CSS, "css/payment.css"),
    )
    _write(
        output / "index.php",
        _apply_header(_INDEX_PHP, "index.php"),
    )
    _write(
        output / "pay.php",
        _apply_header(_PAY_PHP, "pay.php"),
    )

    # -----------------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------------
    print()
    print("=" * 60)
    print("  Done!  Site generated successfully.")
    print("=" * 60)
    print(f"\n  Output directory : {output}")
    print(
        "\n  Next steps:"
        "\n    1. Open includes/config.php and verify XMR_WALLET_ADDRESS."
        "\n    2. Upload the entire output folder to a PHP 7.4+ web host."
        "\n    3. Grant the web server write access to includes/"
        "\n       (needed for includes/price_cache.json created at runtime)."
        "\n    4. Visit index.php in your browser to test."
    )

    if not wallet:
        print(
            "\n  WARNING: XMR_WALLET_ADDRESS is empty in includes/config.php."
            "\n           Visitors will see a configuration notice until it is set."
        )

    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
