#!/usr/bin/env python3
"""
website_updater.py — Static Website Updater Tool

Restructures, SEO-optimizes, and modernizes static HTML/PHP website files.
Adds continent-based pricing, shipping selectors, Monero payment pages,
product category pages, and a modern dark-theme CSS framework — all without
deleting any existing files.

Usage:
    python website_updater.py [--dry-run] [--config path/to/config.json]

Requirements: Python 3.8+, standard library only.
"""

import argparse
import collections
import copy
import datetime
import hashlib
import html
import html.parser
import json
import os
import pathlib
import re
import shutil
import sys
from urllib.parse import urlparse

# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------

DEFAULT_CONFIG = {
    "monero_wallet_address": "YOUR_MONERO_ADDRESS_HERE",
    "website_root": ".",
    "keywords_file": "keywords.txt",
    "site_url": "http://yoursite.onion",
    "shipping_methods": {
        "domestic_standard": 5.00,
        "domestic_express": 10.00,
        "international_standard": 15.00,
        "international_priority": 25.00,
        "international_express": 40.00,
    },
    "continent_pricing": {
        "north_america": 1.0,
        "europe": 1.2,
        "south_america": 1.5,
        "asia": 1.8,
        "africa": 2.0,
        "oceania": 1.6,
        "antarctica": 2.0,
    },
    "contact_wickr": "yourwickrhandle",
    "contact_email": "your@email.com",
}

# Keyword lists used to infer product categories
CATEGORY_KEYWORDS = {
    "electronics": [
        "phone", "laptop", "computer", "tablet", "camera", "electronic",
        "tech", "gadget", "device", "screen", "monitor", "keyboard",
        "mouse", "battery", "charger", "cable",
    ],
    "clothing": [
        "shirt", "pants", "dress", "jacket", "shoe", "boot", "hat",
        "cap", "clothing", "apparel", "fashion", "wear", "outfit", "jeans",
    ],
    "books": [
        "book", "novel", "guide", "manual", "textbook", "magazine",
        "journal", "ebook", "pdf",
    ],
    "food": [
        "food", "drink", "beverage", "snack", "meal", "nutrition",
        "organic", "supplement", "coffee", "tea",
    ],
    "health": [
        "health", "medical", "medicine", "vitamin", "supplement",
        "pharmacy", "pill", "tablet", "capsule", "wellness",
    ],
    "tools": [
        "tool", "equipment", "hardware", "instrument", "machine",
        "power", "drill", "saw", "hammer", "wrench",
    ],
    "home": [
        "home", "house", "furniture", "decor", "kitchen", "bedroom",
        "bathroom", "garden", "outdoor", "lamp", "chair",
    ],
    "software": [
        "software", "app", "application", "program", "license", "key",
        "subscription", "digital", "download", "serial",
    ],
    "services": [
        "service", "consulting", "support", "maintenance", "repair",
        "installation", "tutorial",
    ],
    "other": [],
}

# ---------------------------------------------------------------------------
# DARK THEME CSS
# ---------------------------------------------------------------------------

DARK_THEME_CSS = """\
/* Modern Dark Theme — generated by website_updater.py */
:root {
  --bg-primary:   #0d0d0d;
  --bg-secondary: #1a1a1a;
  --bg-card:      #222222;
  --bg-hover:     #2a2a2a;
  --text-primary:   #e8e8e8;
  --text-secondary: #a0a0a0;
  --text-muted:     #666666;
  --accent:       #ff6b35;
  --accent-hover: #ff8855;
  --accent-dark:  #cc5528;
  --border:       #333333;
  --border-light: #444444;
  --success: #4caf50;
  --warning: #ff9800;
  --error:   #f44336;
  --shadow:      0 4px 20px rgba(0,0,0,0.5);
  --shadow-card: 0 2px 10px rgba(0,0,0,0.4);
  --radius:    8px;
  --radius-sm: 4px;
  --transition: all 0.2s ease;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
html { font-size: 16px; scroll-behavior: smooth; }
body {
  background-color: var(--bg-primary);
  color: var(--text-primary);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
               Ubuntu, Cantarell, sans-serif;
  line-height: 1.6;
  min-height: 100vh;
}
a { color: var(--accent); text-decoration: none; transition: var(--transition); }
a:hover { color: var(--accent-hover); text-decoration: underline; }
h1,h2,h3,h4,h5,h6 { color: var(--text-primary); font-weight: 600;
  line-height: 1.3; margin-bottom: 0.75em; }
p { margin-bottom: 1em; color: var(--text-secondary); }
img { max-width: 100%; height: auto; border-radius: var(--radius-sm); }

/* ── Layout ── */
.container { max-width: 1200px; margin: 0 auto; padding: 0 20px; }
.main-content { padding: 2rem 0; }

/* ── Navigation ── */
.navbar {
  background-color: var(--bg-secondary);
  border-bottom: 1px solid var(--border);
  position: sticky; top: 0; z-index: 1000;
  box-shadow: var(--shadow);
}
.navbar .container {
  display: flex; align-items: center; justify-content: space-between;
  height: 60px;
}
.navbar-brand {
  font-size: 1.4rem; font-weight: 700;
  color: var(--accent) !important; text-decoration: none !important;
}
.navbar-nav { display: flex; list-style: none; gap: 8px; flex-wrap: wrap; }
.navbar-nav a {
  padding: 6px 14px; border-radius: var(--radius-sm);
  font-size: 0.9rem; transition: var(--transition);
}
.navbar-nav a:hover { background-color: var(--bg-hover); text-decoration: none; }

/* ── Cards ── */
.card {
  background-color: var(--bg-card);
  border: 1px solid var(--border); border-radius: var(--radius);
  padding: 1.5rem; transition: var(--transition);
  box-shadow: var(--shadow-card);
}
.card:hover {
  border-color: var(--border-light);
  transform: translateY(-2px); box-shadow: var(--shadow);
}

/* ── Product Grid ── */
.product-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
  gap: 1.5rem; padding: 1rem 0;
}
.product-card {
  background-color: var(--bg-card);
  border: 1px solid var(--border); border-radius: var(--radius);
  overflow: hidden; transition: var(--transition);
  box-shadow: var(--shadow-card);
  display: flex; flex-direction: column;
}
.product-card:hover {
  border-color: var(--accent-dark);
  transform: translateY(-3px); box-shadow: var(--shadow);
}
.product-card .product-image {
  width: 100%; aspect-ratio: 4/3; object-fit: cover;
  background-color: var(--bg-secondary);
}
.product-card .product-body {
  padding: 1rem; flex: 1;
  display: flex; flex-direction: column;
}
.product-card .product-title { font-size: 1rem; font-weight: 600;
  color: var(--text-primary); margin-bottom: 0.5rem; }
.product-card .product-price { font-size: 1.2rem; font-weight: 700;
  color: var(--accent); margin-bottom: 0.5rem; }
.product-card .product-desc { font-size: 0.85rem; color: var(--text-secondary);
  flex: 1; margin-bottom: 1rem; }
.product-card .btn-buy {
  display: block; text-align: center;
  background-color: var(--accent); color: #fff !important;
  padding: 10px 16px; border-radius: var(--radius-sm);
  font-weight: 600; font-size: 0.9rem; transition: var(--transition);
  border: none; cursor: pointer; text-decoration: none !important;
}
.product-card .btn-buy:hover {
  background-color: var(--accent-hover); transform: translateY(-1px);
}

/* ── Buttons ── */
.btn {
  display: inline-block; padding: 10px 20px;
  border-radius: var(--radius-sm); font-weight: 600;
  font-size: 0.9rem; cursor: pointer; border: none;
  transition: var(--transition); text-decoration: none;
}
.btn-primary { background-color: var(--accent); color: #fff; }
.btn-primary:hover { background-color: var(--accent-hover);
  color: #fff; text-decoration: none; }
.btn-secondary {
  background-color: var(--bg-secondary);
  color: var(--text-primary); border: 1px solid var(--border);
}
.btn-secondary:hover { background-color: var(--bg-hover); text-decoration: none; }

/* ── Forms ── */
.form-group { margin-bottom: 1.2rem; }
label { display: block; margin-bottom: 6px; font-size: 0.9rem;
  color: var(--text-secondary); font-weight: 500; }
input[type="text"],
input[type="number"],
input[type="email"],
select,
textarea {
  width: 100%; background-color: var(--bg-secondary);
  border: 1px solid var(--border); color: var(--text-primary);
  padding: 10px 14px; border-radius: var(--radius-sm);
  font-size: 0.95rem; transition: var(--transition);
  outline: none; appearance: none;
}
input:focus, select:focus, textarea:focus {
  border-color: var(--accent);
  box-shadow: 0 0 0 2px rgba(255,107,53,0.15);
}
select {
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%23a0a0a0' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e");
  background-position: right 10px center;
  background-repeat: no-repeat; background-size: 16px;
  padding-right: 36px; cursor: pointer;
}

/* ── Tables ── */
table { width: 100%; border-collapse: collapse; margin-bottom: 1.5rem; }
th, td {
  padding: 12px 16px; text-align: left;
  border-bottom: 1px solid var(--border); font-size: 0.9rem;
}
th {
  background-color: var(--bg-secondary); color: var(--text-secondary);
  font-weight: 600; text-transform: uppercase;
  font-size: 0.75rem; letter-spacing: 0.05em;
}
tr:hover td { background-color: var(--bg-hover); }

/* ── Categories ── */
.category-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 1rem; margin: 1.5rem 0;
}
.category-card {
  background-color: var(--bg-card); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 1.2rem;
  text-align: center; transition: var(--transition);
  display: block; text-decoration: none !important;
}
.category-card:hover { border-color: var(--accent); transform: translateY(-2px); }
.category-card h3 { font-size: 1rem; margin-bottom: 0.25rem; }
.category-card .count { font-size: 0.8rem; color: var(--text-muted); }

/* ── Sorting Controls ── */
.sort-controls {
  display: flex; align-items: center; gap: 1rem;
  margin-bottom: 1.5rem; flex-wrap: wrap;
  padding: 1rem; background-color: var(--bg-secondary);
  border-radius: var(--radius); border: 1px solid var(--border);
}
.sort-controls label { margin: 0; white-space: nowrap; }
.sort-controls select { width: auto; flex: 1; min-width: 160px; }

/* ── Pricing Controls ── */
.pricing-controls {
  background-color: var(--bg-secondary);
  border: 1px solid var(--border); border-radius: var(--radius);
  padding: 1.2rem; margin-bottom: 1.5rem;
}
.pricing-controls h3 {
  font-size: 0.9rem; text-transform: uppercase;
  letter-spacing: 0.05em; color: var(--text-muted); margin-bottom: 1rem;
}

/* ── Footer ── */
footer {
  background-color: var(--bg-secondary);
  border-top: 1px solid var(--border); padding: 2rem 0; margin-top: 4rem;
}
footer .footer-content {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 2rem;
}
footer h3 {
  font-size: 0.85rem; text-transform: uppercase;
  letter-spacing: 0.1em; color: var(--text-muted); margin-bottom: 1rem;
}
footer p, footer a { font-size: 0.875rem; color: var(--text-secondary); }
footer a:hover { color: var(--accent); }
.footer-bottom {
  margin-top: 2rem; padding-top: 1rem;
  border-top: 1px solid var(--border);
  text-align: center; font-size: 0.8rem; color: var(--text-muted);
}

/* ── Page Hero ── */
.page-hero {
  padding: 3rem 0 2rem; border-bottom: 1px solid var(--border);
  margin-bottom: 2rem;
}
.page-hero h1 { font-size: 2rem; margin-bottom: 0.5rem; }
.page-hero p { font-size: 1rem; color: var(--text-secondary); }

/* ── Payment Page ── */
.payment-container { max-width: 760px; margin: 0 auto; }
.payment-step {
  background-color: var(--bg-card); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 1.5rem; margin-bottom: 1.5rem;
}
.payment-step h2 {
  font-size: 1rem; text-transform: uppercase;
  letter-spacing: 0.05em; color: var(--text-muted); margin-bottom: 1.2rem;
}
.wallet-address-box {
  background-color: var(--bg-primary); border: 1px solid var(--border);
  border-radius: var(--radius-sm); padding: 12px;
  font-family: monospace; font-size: 0.8rem;
  word-break: break-all; color: var(--text-secondary); position: relative;
}
.copy-btn {
  position: absolute; right: 8px; top: 8px;
  background: var(--accent); color: #fff; border: none;
  border-radius: var(--radius-sm); padding: 4px 10px;
  font-size: 0.75rem; cursor: pointer;
}
.price-display {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  gap: 1rem; margin: 1rem 0;
}
.price-item {
  background-color: var(--bg-secondary); border-radius: var(--radius-sm);
  padding: 1rem; text-align: center;
}
.price-item .currency {
  font-size: 0.75rem; color: var(--text-muted);
  text-transform: uppercase; letter-spacing: 0.05em;
}
.price-item .amount {
  font-size: 1.5rem; font-weight: 700; color: var(--accent); margin: 4px 0;
}
.price-item .usd-equiv { font-size: 0.8rem; color: var(--text-secondary); }
.status-box {
  display: flex; align-items: center; gap: 1rem; padding: 1rem;
  background-color: var(--bg-secondary); border-radius: var(--radius);
  border-left: 3px solid var(--warning);
}
.status-indicator {
  width: 12px; height: 12px; border-radius: 50%;
  background-color: var(--warning);
  animation: pulse 2s infinite; flex-shrink: 0;
}
@keyframes pulse {
  0%, 100% { opacity: 1; }
  50%       { opacity: 0.4; }
}

/* ── Responsive ── */
@media (max-width: 768px) {
  .navbar .container {
    flex-wrap: wrap; height: auto; padding: 10px 20px; gap: 8px;
  }
  .navbar-nav { width: 100%; }
  .product-grid {
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 1rem;
  }
  .page-hero h1 { font-size: 1.5rem; }
  .sort-controls { flex-direction: column; align-items: stretch; }
  .sort-controls select { width: 100%; }
}
@media (max-width: 480px) {
  .product-grid { grid-template-columns: 1fr; }
  .category-grid { grid-template-columns: repeat(2, 1fr); }
}
"""

# ---------------------------------------------------------------------------
# SORTING / PRICING JAVASCRIPT
# ---------------------------------------------------------------------------

MAIN_JS = """\
/* main.js — generated by website_updater.py */
/* Client-side sorting, continent pricing, and shipping selectors */

/* ── Product Sorting ── */
function sortProducts(criterion) {
  var grid = document.getElementById('product-grid');
  if (!grid) return;
  var cards = Array.from(grid.querySelectorAll('[data-price]'));
  cards.sort(function (a, b) {
    switch (criterion) {
      case 'price-asc':  return parseFloat(a.dataset.price||0) - parseFloat(b.dataset.price||0);
      case 'price-desc': return parseFloat(b.dataset.price||0) - parseFloat(a.dataset.price||0);
      case 'name-asc':   return (a.dataset.name||'').localeCompare(b.dataset.name||'');
      case 'name-desc':  return (b.dataset.name||'').localeCompare(a.dataset.name||'');
      case 'qty-asc':    return parseFloat(a.dataset.qty||0) - parseFloat(b.dataset.qty||0);
      case 'qty-desc':   return parseFloat(b.dataset.qty||0) - parseFloat(a.dataset.qty||0);
      default:           return 0;
    }
  });
  cards.forEach(function (c) { grid.appendChild(c); });
}

/* ── Pricing Helpers ── */
var CONTINENT_MULTIPLIERS = {
  north_america: 1.0, europe: 1.2, south_america: 1.5,
  asia: 1.8, africa: 2.0, oceania: 1.6, antarctica: 2.0
};
var SHIPPING_RATES = {
  domestic_standard: 5.00, domestic_express: 10.00,
  international_standard: 15.00, international_priority: 25.00,
  international_express: 40.00
};

function updatePricing() {
  var cSel = document.getElementById('continent-select');
  var sSel = document.getElementById('shipping-select');
  var multiplier = cSel ? (CONTINENT_MULTIPLIERS[cSel.value] || 1.0) : 1.0;
  var shippingCost = sSel ? (SHIPPING_RATES[sSel.value] || 0) : 0;

  document.querySelectorAll('[data-base-price]').forEach(function (el) {
    var base = parseFloat(el.dataset.basePrice || 0);
    el.textContent = '$' + ((base * multiplier) + shippingCost).toFixed(2);
  });
  updateTotal();
}

function updateTotal() {
  var cSel  = document.getElementById('continent-select');
  var sSel  = document.getElementById('shipping-select');
  var qtyEl = document.getElementById('qty');
  var bpEl  = document.querySelector('[data-item-base-price]');
  if (!bpEl) return;

  var base = parseFloat(bpEl.dataset.itemBasePrice || 0);
  var qty  = parseInt(qtyEl ? qtyEl.value : 1, 10) || 1;
  var multiplier    = cSel ? (CONTINENT_MULTIPLIERS[cSel.value] || 1.0) : 1.0;
  var shippingCost  = sSel ? (SHIPPING_RATES[sSel.value] || 0) : 0;
  var total = (base * multiplier * qty) + shippingCost;

  var totalEl = document.getElementById('order-total');
  if (totalEl) totalEl.textContent = '$' + total.toFixed(2);

  var hiddenInput = document.getElementById('total-input');
  if (hiddenInput) hiddenInput.value = total.toFixed(2);
}

document.addEventListener('DOMContentLoaded', function () {
  var cSel = document.getElementById('continent-select');
  var sSel = document.getElementById('shipping-select');
  var qty  = document.getElementById('qty');
  var sort = document.getElementById('sort-select');

  if (cSel) cSel.addEventListener('change', updatePricing);
  if (sSel) sSel.addEventListener('change', updatePricing);
  if (qty)  qty.addEventListener('input', updateTotal);
  if (sort) sort.addEventListener('change', function () { sortProducts(this.value); });
});
"""

# ---------------------------------------------------------------------------
# LOGGER
# ---------------------------------------------------------------------------

class Logger:
    """Simple logger that writes to console and accumulates entries for a log file."""

    def __init__(self, log_file, dry_run=False):
        self.log_file = log_file
        self.dry_run = dry_run
        self.entries = []

    def log(self, message, level="INFO"):
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        prefix = "[DRY-RUN] " if self.dry_run else ""
        entry = "[{ts}] [{lvl}] {pfx}{msg}".format(
            ts=timestamp, lvl=level, pfx=prefix, msg=message
        )
        self.entries.append(entry)
        print(entry)

    def save(self):
        if not self.dry_run:
            with open(self.log_file, "w", encoding="utf-8") as fh:
                fh.write("\n".join(self.entries))
                fh.write("\n")


# ---------------------------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------------------------

def load_config(config_path, logger):
    """Load and merge user config with defaults."""
    config = copy.deepcopy(DEFAULT_CONFIG)
    if os.path.exists(config_path):
        try:
            with open(config_path, "r", encoding="utf-8") as fh:
                user_config = json.load(fh)
            for key, value in user_config.items():
                if isinstance(value, dict) and isinstance(config.get(key), dict):
                    config[key].update(value)
                else:
                    config[key] = value
            logger.log("Loaded config from: {}".format(config_path))
        except (ValueError, IOError) as exc:
            logger.log("Failed to parse config.json: {}".format(exc), "WARNING")
    else:
        logger.log("Config not found at {}, using defaults".format(config_path), "WARNING")

    # Warn if the placeholder wallet address has not been replaced
    wallet = config.get("monero_wallet_address", "")
    if not wallet or wallet.upper().startswith("YOUR_") or "ADDRESS_HERE" in wallet.upper():
        logger.log(
            "monero_wallet_address is still the placeholder value. "
            "Edit config.json with your real XMR address before going live — "
            "otherwise payments will be unrecoverable.",
            "WARNING",
        )

    return config


def load_keywords(keywords_file, logger):
    """Load keywords from a text file (one per line)."""
    keywords = []
    if os.path.exists(keywords_file):
        try:
            with open(keywords_file, "r", encoding="utf-8") as fh:
                keywords = [line.strip() for line in fh if line.strip()]
            logger.log("Loaded {} keywords from {}".format(len(keywords), keywords_file))
        except IOError as exc:
            logger.log("Failed to load keywords: {}".format(exc), "WARNING")
    else:
        logger.log("Keywords file not found: {}".format(keywords_file), "WARNING")
    return keywords


# ---------------------------------------------------------------------------
# BACKUP
# ---------------------------------------------------------------------------

def create_backup(website_root, logger, dry_run=False):
    """Create a full backup of the website directory."""
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    parent = os.path.dirname(os.path.abspath(website_root))
    backup_dir = os.path.join(parent, "website_backup_{}".format(timestamp))
    if dry_run:
        logger.log("[DRY-RUN] Would create backup at: {}".format(backup_dir))
        return backup_dir
    logger.log("Creating backup at: {}".format(backup_dir))
    shutil.copytree(website_root, backup_dir)
    logger.log("Backup complete: {}".format(backup_dir))
    return backup_dir


# ---------------------------------------------------------------------------
# FILE DISCOVERY
# ---------------------------------------------------------------------------

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".svg", ".webp", ".ico", ".bmp"}


def discover_files(root):
    """Walk the website directory and classify files."""
    result = {"html": [], "php": [], "css": [], "js": [], "images": [], "all": []}
    for dirpath, dirnames, filenames in os.walk(root):
        # Skip backup directories in-place
        dirnames[:] = [
            d for d in dirnames
            if not d.startswith("website_backup_") and d not in {".git"}
        ]
        for filename in filenames:
            filepath = os.path.join(dirpath, filename)
            ext = os.path.splitext(filename)[1].lower()
            result["all"].append(filepath)
            if ext == ".html":
                result["html"].append(filepath)
            elif ext == ".php":
                result["php"].append(filepath)
            elif ext == ".css":
                result["css"].append(filepath)
            elif ext == ".js":
                result["js"].append(filepath)
            elif ext in IMAGE_EXTS:
                result["images"].append(filepath)
    return result


# ---------------------------------------------------------------------------
# FILE I/O HELPERS
# ---------------------------------------------------------------------------

def read_file_safe(filepath):
    """Read a file with encoding fallback."""
    for encoding in ("utf-8", "latin-1", "cp1252"):
        try:
            with open(filepath, "r", encoding=encoding, errors="replace") as fh:
                return fh.read()
        except IOError:
            pass
    return ""


def write_file_safe(filepath, content, dry_run=False):
    """Write content to a file (no-op in dry-run mode)."""
    if dry_run:
        return True
    try:
        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as fh:
            fh.write(content)
        return True
    except IOError:
        return False


# ---------------------------------------------------------------------------
# LINK CHECKER / FIXER
# ---------------------------------------------------------------------------

class _LinkExtractor(html.parser.HTMLParser):
    """Extracts href/src/action attribute values from HTML."""

    def __init__(self):
        super(_LinkExtractor, self).__init__()
        self.links = []  # list of (attr_name, value, tag)

    def handle_starttag(self, tag, attrs):
        attrs_dict = dict(attrs)
        for attr in ("href", "src", "action"):
            val = attrs_dict.get(attr, "")
            if val:
                self.links.append((attr, val, tag))


def _is_external(href):
    parsed = urlparse(href)
    return bool(parsed.scheme) and parsed.scheme not in ("", "file")


def _resolve_link(base_file, href, root):
    """Resolve a relative href to an absolute filesystem path."""
    if _is_external(href):
        return None
    href_clean = href.split("?")[0].split("#")[0]
    if not href_clean:
        return None
    base_dir = os.path.dirname(base_file)
    if href_clean.startswith("/"):
        return os.path.normpath(os.path.join(root, href_clean.lstrip("/")))
    return os.path.normpath(os.path.join(base_dir, href_clean))


def build_file_index(root, files):
    """Build filename → [full_path, ...] index for quick lookup."""
    index = collections.defaultdict(list)
    for f in files["all"]:
        index[os.path.basename(f).lower()].append(f)
    return index


def check_and_fix_links(filepath, root, file_index, logger, dry_run=False):
    """Check and fix broken internal links. Returns count of fixes."""
    content = read_file_safe(filepath)
    if not content:
        return 0

    parser = _LinkExtractor()
    try:
        parser.feed(content)
    except Exception:
        pass

    fixes = 0
    new_content = content

    for attr, href, _tag in parser.links:
        if _is_external(href):
            continue
        href_clean = href.split("?")[0].split("#")[0]
        if not href_clean or href_clean.startswith("#"):
            continue

        resolved = _resolve_link(filepath, href_clean, root)
        if resolved and os.path.exists(resolved):
            continue  # link is valid

        # Try to find the file elsewhere in the directory tree
        basename = os.path.basename(href_clean).lower()
        candidates = file_index.get(basename, [])

        if candidates:
            best = candidates[0]
            rel_path = os.path.relpath(best, os.path.dirname(filepath)).replace(os.sep, "/")
            logger.log(
                "Fixed broken link in {}: {} -> {}".format(
                    os.path.relpath(filepath, root), href, rel_path
                )
            )
            for q in ('"', "'"):
                old = "{}={}{}{}".format(attr, q, re.escape(href), q)
                new = "{}={}{}{}".format(attr, q, rel_path, q)
                if re.search("{}={}{}{}".format(attr, q, re.escape(href), q), new_content):
                    new_content = re.sub(
                        "{}={}{}{}".format(attr, q, re.escape(href), q),
                        "{}={}{}{}".format(attr, q, rel_path, q),
                        new_content, count=1
                    )
                    fixes += 1
                    break
        else:
            logger.log(
                "Broken link (unresolvable) in {}: {} (file not found anywhere)".format(
                    os.path.relpath(filepath, root), href
                ),
                "WARNING",
            )

    if fixes > 0:
        write_file_safe(filepath, new_content, dry_run)
    return fixes


# ---------------------------------------------------------------------------
# DIRECTORY STRUCTURE
# ---------------------------------------------------------------------------

def ensure_directory_structure(root, logger, dry_run=False):
    """Create standard subdirectories if they don't already exist."""
    for d in ("products", "css", "js", "images"):
        full = os.path.join(root, d)
        if not os.path.exists(full):
            logger.log("Creating directory: {}/".format(d))
            if not dry_run:
                os.makedirs(full, exist_ok=True)


# ---------------------------------------------------------------------------
# SEO META TAGS
# ---------------------------------------------------------------------------

def _extract_text(html_content):
    """Strip HTML tags and return plain text."""
    content = re.sub(r"<script[^>]*>.*?</script\s*>", "", html_content,
                     flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r"<style[^>]*>.*?</style\s*>", "", content,
                     flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r"<[^>]+>", " ", content)
    content = html.unescape(content)
    return re.sub(r"\s+", " ", content).strip()


def _generate_description(text, max_len=160):
    """Generate a short meta description from plain text."""
    if not text:
        return "Privacy-focused online store with secure anonymous payments via Monero."
    desc = ""
    for sentence in re.split(r"[.!?]+", text):
        sentence = sentence.strip()
        if len(sentence) < 10:
            continue
        if len(desc) + len(sentence) + 2 <= max_len:
            desc = (desc + ". " + sentence).strip(". ")
        else:
            break
    if not desc:
        desc = text[:max_len].rsplit(" ", 1)[0]
    return (desc[:max_len] if desc else "Privacy-focused online store.").strip()


def _extract_title(html_content):
    m = re.search(r"<title[^>]*>(.*?)</title>", html_content,
                  re.IGNORECASE | re.DOTALL)
    return html.unescape(m.group(1).strip()) if m else ""


def inject_seo_tags(filepath, keywords, site_url, logger, dry_run=False):
    """Inject / update SEO meta tags in an HTML/PHP file."""
    content = read_file_safe(filepath)
    if not content:
        return False

    text = _extract_text(content)
    title = _extract_title(content) or (
        os.path.splitext(os.path.basename(filepath))[0]
        .replace("-", " ").replace("_", " ").title()
    )
    description = _generate_description(text)
    kw_str = ", ".join(keywords[:25]) if keywords else ""

    # Build replacement block
    tags = []
    tags.append('<meta charset="UTF-8">')
    tags.append('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
    tags.append('<meta name="robots" content="index, follow">')
    if kw_str:
        tags.append('<meta name="keywords" content="{}">'.format(html.escape(kw_str)))
    tags.append('<meta name="description" content="{}">'.format(html.escape(description)))
    tags.append('<meta property="og:title" content="{}">'.format(html.escape(title)))
    tags.append('<meta property="og:description" content="{}">'.format(html.escape(description)))
    tags.append('<meta property="og:type" content="website">')
    meta_block = "\n    ".join(tags)

    new_content = content
    # Remove pre-existing duplicates
    for pattern in (
        r'\s*<meta\s+charset=["\'][^"\']*["\'][^>]*/?>',
        r'\s*<meta\s+name=["\']keywords["\'][^>]*/?>',
        r'\s*<meta\s+name=["\']description["\'][^>]*/?>',
        r'\s*<meta\s+property=["\']og:[^"\']*["\'][^>]*/?>',
        r'\s*<meta\s+name=["\']robots["\'][^>]*/?>',
        r'\s*<meta\s+name=["\']viewport["\'][^>]*/?>',
    ):
        new_content = re.sub(pattern, "", new_content, flags=re.IGNORECASE)

    # Insert after opening <head> tag
    if re.search(r"<head[^>]*>", new_content, re.IGNORECASE):
        new_content = re.sub(
            r"(<head[^>]*>)",
            r"\1\n    " + meta_block,
            new_content, count=1, flags=re.IGNORECASE,
        )
    elif re.search(r"</head>", new_content, re.IGNORECASE):
        new_content = re.sub(
            r"(</head>)",
            "    " + meta_block + r"\n\1",
            new_content, count=1, flags=re.IGNORECASE,
        )
    else:
        new_content = "<head>\n    {}\n</head>\n".format(meta_block) + new_content

    if new_content != content:
        logger.log("Updated SEO meta tags: {}".format(os.path.relpath(filepath)))
        write_file_safe(filepath, new_content, dry_run)
        return True
    return False


# ---------------------------------------------------------------------------
# SITEMAP & ROBOTS
# ---------------------------------------------------------------------------

def generate_sitemap(root, files, site_url, logger, dry_run=False):
    """Generate sitemap.xml from discovered HTML/PHP pages."""
    base = site_url.rstrip("/")
    now = datetime.datetime.now().strftime("%Y-%m-%d")
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for filepath in files["html"] + files["php"]:
        rel = os.path.relpath(filepath, root).replace(os.sep, "/")
        if rel in ("index.html", "index.php"):
            priority, changefreq = "1.0", "daily"
        elif "product" in rel.lower():
            priority, changefreq = "0.8", "weekly"
        elif "categor" in rel.lower():
            priority, changefreq = "0.7", "weekly"
        else:
            priority, changefreq = "0.5", "monthly"
        lines += [
            "  <url>",
            "    <loc>{}/{}</loc>".format(base, html.escape(rel)),
            "    <lastmod>{}</lastmod>".format(now),
            "    <changefreq>{}</changefreq>".format(changefreq),
            "    <priority>{}</priority>".format(priority),
            "  </url>",
        ]
    lines.append("</urlset>")
    write_file_safe(os.path.join(root, "sitemap.xml"), "\n".join(lines), dry_run)
    logger.log("Generated sitemap.xml ({} URLs)".format(len(files["html"]) + len(files["php"])))


def generate_robots(root, site_url, logger, dry_run=False):
    """Generate an optimized robots.txt."""
    base = site_url.rstrip("/")
    content = (
        "User-agent: *\n"
        "Allow: /\n"
        "\n"
        "# Block non-essential directories\n"
        "Disallow: /images/thumbs/\n"
        "Disallow: /images/tmp/\n"
        "Disallow: /.git/\n"
        "Disallow: /website_backup*/\n"
        "Disallow: /tmp/\n"
        "Disallow: /cache/\n"
        "Disallow: /logs/\n"
        "\n"
        "# Sitemap\n"
        "Sitemap: {}/sitemap.xml\n".format(base)
    )
    write_file_safe(os.path.join(root, "robots.txt"), content, dry_run)
    logger.log("Generated robots.txt")


# ---------------------------------------------------------------------------
# PRODUCT PARSER
# ---------------------------------------------------------------------------

class _ProductParser(html.parser.HTMLParser):
    """Extracts product metadata from an HTML/PHP page."""

    def __init__(self):
        super(_ProductParser, self).__init__()
        self._stack = []
        self._buf = []
        self.title = ""
        self.price = ""
        self.description = ""
        self.images = []
        self.quantity = ""

    def handle_starttag(self, tag, attrs):
        self._stack.append(tag)
        self._buf = []
        attrs_dict = dict(attrs)
        if tag == "img":
            src = attrs_dict.get("src", "")
            if src and not src.startswith("data:"):
                self.images.append(src)

    def handle_endtag(self, tag):
        text = "".join(self._buf).strip()
        if tag == "title" and not self.title:
            self.title = text
        elif tag == "h1" and not self.title:
            self.title = text
        elif tag == "h2" and not self.title:
            self.title = text
        elif tag == "p" and not self.description and len(text) > 20:
            self.description = text
        if self._stack and self._stack[-1] == tag:
            self._stack.pop()
        self._buf = []

    def handle_data(self, data):
        self._buf.append(data)
        if not self.price:
            m = re.search(r"\$\s*(\d+(?:\.\d{1,2})?)", data)
            if m:
                self.price = m.group(1)
        if not self.quantity:
            m = re.search(r"(?:qty|quantity|stock|available)[:\s]+(\d+)", data,
                          re.IGNORECASE)
            if m:
                self.quantity = m.group(1)


class IndexProductParser(html.parser.HTMLParser):
    """Extracts product listings from an index/main page HTML.

    Looks for elements whose ``class`` attribute contains common product-related
    words ("product", "item", "listing").  Within each matched container the
    parser collects:

    * ``name``  — text of the first heading tag found
    * ``price`` — first ``$XX.XX``-style price string found anywhere in the block
    * ``description`` — first non-trivial ``<p>`` text found in the block
    * ``images`` — ``src`` values of ``<img>`` tags
    * ``link``   — first non-fragment ``<a href>`` value
    * ``quantity`` — value after "qty / quantity / stock / available:" pattern
    """

    _PRODUCT_CONTAINER_TAGS = frozenset(["div", "article", "section", "li", "tr"])
    _HEADING_TAGS = frozenset(["h1", "h2", "h3", "h4", "h5", "h6"])
    _PRODUCT_CLASS_HINTS = ("product", "item", "listing")
    # Void elements never fire handle_endtag so must not affect depth
    _VOID_TAGS = frozenset([
        "area", "base", "br", "col", "embed", "hr", "img", "input", "link",
        "meta", "param", "source", "track", "wbr",
    ])

    def __init__(self):
        super(IndexProductParser, self).__init__()
        self._depth = 0
        self._product_start_depth = None
        self._current = None
        self.products = []
        # Accumulates all stripped text tokens inside the current product block
        self._all_text = []
        # Tracks the depth at which the first heading inside a product opened
        self._heading_depth = None
        self._heading_buf = []

    @staticmethod
    def _has_product_class(attrs_dict):
        cls = attrs_dict.get("class", "").lower()
        return any(hint in cls for hint in IndexProductParser._PRODUCT_CLASS_HINTS)

    def handle_starttag(self, tag, attrs):
        attrs_dict = dict(attrs)

        # Collect img/a attributes before (possibly) skipping depth update
        if self._current is not None:
            if tag == "img":
                src = attrs_dict.get("src", "")
                if src and not src.startswith("data:"):
                    self._current["images"].append(src)
            elif tag == "a":
                href = attrs_dict.get("href", "")
                if href and not any(
                    href.startswith(p) for p in ("#", "javascript:", "mailto:")
                ):
                    if not self._current["link"]:
                        self._current["link"] = href

        # Void elements do not produce a matching endtag, so skip depth tracking
        if tag in self._VOID_TAGS:
            return

        self._depth += 1

        # Only start a new product container when we are not already inside one
        if self._current is None and tag in self._PRODUCT_CONTAINER_TAGS:
            if self._has_product_class(attrs_dict):
                self._product_start_depth = self._depth
                self._current = {
                    "name": "",
                    "price": "",
                    "description": "",
                    "images": [],
                    "link": "",
                    "quantity": "",
                }
                self._all_text = []

        if self._current is not None:
            # Begin collecting heading text (use depth to match the close tag)
            if tag in self._HEADING_TAGS and self._heading_depth is None:
                self._heading_depth = self._depth
                self._heading_buf = []

    def handle_endtag(self, tag):
        if tag in self._VOID_TAGS:
            return

        if self._current is not None:
            # Finalise heading text
            if tag in self._HEADING_TAGS and self._heading_depth == self._depth:
                heading_text = "".join(self._heading_buf).strip()
                if heading_text and not self._current["name"]:
                    self._current["name"] = heading_text
                self._heading_depth = None
                self._heading_buf = []

            # Finalise product when closing its container tag
            if (
                self._depth == self._product_start_depth
                and tag in self._PRODUCT_CONTAINER_TAGS
            ):
                all_text_str = " ".join(self._all_text)
                if not self._current["price"]:
                    m = re.search(r"\$\s*(\d+(?:\.\d{1,2})?)", all_text_str)
                    if m:
                        self._current["price"] = m.group(1)
                if not self._current["description"]:
                    desc = all_text_str.strip()
                    if len(desc) > 15:
                        self._current["description"] = desc[:200]
                if self._current["name"] or self._current["price"]:
                    self.products.append(self._current)
                self._current = None
                self._product_start_depth = None
                self._all_text = []

        self._depth -= 1

    def handle_data(self, data):
        stripped = data.strip()
        if not stripped:
            return
        if self._current is not None:
            self._all_text.append(stripped)
            if not self._current["price"]:
                m = re.search(r"\$\s*(\d+(?:\.\d{1,2})?)", data)
                if m:
                    self._current["price"] = m.group(1)
            if not self._current["quantity"]:
                m = re.search(
                    r"(?:qty|quantity|stock|available)[:\s]+(\d+)",
                    data, re.IGNORECASE,
                )
                if m:
                    self._current["quantity"] = m.group(1)
        if self._heading_depth is not None:
            self._heading_buf.append(data)


def _infer_category(name, content, filepath):
    """Infer product category from name, content, and file path."""
    text = (name + " " + content + " " + filepath).lower()
    best, best_score = "other", 0
    for cat, kws in CATEGORY_KEYWORDS.items():
        if cat == "other":
            continue
        score = sum(1 for kw in kws if kw in text)
        if score > best_score:
            best_score = score
            best = cat
    return best


def parse_product(filepath):
    """Parse a product file and return a metadata dict."""
    content = read_file_safe(filepath)
    parser = _ProductParser()
    try:
        parser.feed(content)
    except Exception:
        pass

    price = parser.price
    if not price:
        m = re.search(r"\$\s*(\d+(?:\.\d{1,2})?)", content)
        if m:
            price = m.group(1)

    name = parser.title or (
        os.path.splitext(os.path.basename(filepath))[0]
        .replace("-", " ").replace("_", " ").title()
    )
    description = parser.description or _extract_text(content)[:200]

    return {
        "name": name,
        "price": price or "0",
        "description": description,
        "images": parser.images,
        "filepath": filepath,
        "quantity": parser.quantity or "1",
        "category": _infer_category(name, content, filepath),
    }


def is_product_file(filepath, root):
    """Heuristic: is this an individual product page?"""
    rel = os.path.relpath(filepath, root).lower()
    basename = os.path.basename(rel)
    excluded = {
        "index.html", "index.php", "payment.php", "payment.html",
        "contact.html", "contact.php", "about.html", "about.php",
        "sitemap.xml", "robots.txt",
    }
    if basename in excluded:
        return False
    if basename.startswith("category_"):
        return False
    return rel.endswith((".html", ".php"))


def _product_path_from_name(root, name, hint_link):
    """Derive a product file path from a product name and optional link hint.

    If *hint_link* looks like a local HTML/PHP path it is used directly
    (resolved relative to *root*).  Otherwise a URL-safe slug built from
    *name* is placed in the ``products/`` subdirectory.
    """
    if hint_link:
        link_clean = hint_link.split("?")[0].split("#")[0].lstrip("/")
        if link_clean.endswith((".html", ".php")):
            return os.path.normpath(os.path.join(root, link_clean))
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or "product"
    return os.path.join(root, "products", slug + ".html")


def parse_products_from_index(website_root, logger):
    """Parse products directly from ``index.html`` or ``index.php``.

    Uses :class:`IndexProductParser` to find product containers in the index
    page.  Returns a list of product dicts (same structure as
    :func:`parse_product`) or an empty list when no products are found.
    This is the preferred product-discovery method; file-based scanning via
    :func:`is_product_file` is only used as a fallback.
    """
    index_path = None
    for fname in ("index.html", "index.php"):
        candidate = os.path.join(website_root, fname)
        if os.path.exists(candidate):
            index_path = candidate
            break

    if not index_path:
        logger.log("No index page found; skipping index product parsing")
        return []

    content = read_file_safe(index_path)
    if not content:
        return []

    parser = IndexProductParser()
    try:
        parser.feed(content)
    except Exception:
        pass

    products = []
    seen_names = set()
    for raw in parser.products:
        name = raw["name"].strip() or "Product"
        if name in seen_names:
            continue
        seen_names.add(name)

        price = raw["price"] or "0"
        description = raw["description"] or ""
        images = raw["images"]
        link = raw["link"]
        quantity = raw["quantity"] or "1"

        # Prefer an existing linked file, otherwise derive a path
        if link:
            linked_path = _resolve_link(index_path, link, website_root)
            if linked_path and os.path.exists(linked_path):
                filepath = linked_path
            else:
                filepath = _product_path_from_name(website_root, name, link)
        else:
            filepath = _product_path_from_name(website_root, name, None)

        products.append({
            "name": name,
            "price": price,
            "description": description,
            "images": images,
            "filepath": filepath,
            "quantity": quantity,
            "category": _infer_category(name, description, ""),
        })

    if products:
        logger.log(
            "Parsed {} product(s) from index page ({})".format(
                len(products), os.path.basename(index_path)
            )
        )
    else:
        logger.log("No product listings found in index page")
    return products



def _rel_root(root, current_file):
    """Return the relative path prefix from current_file's directory to root."""
    rel = os.path.relpath(root, os.path.dirname(current_file))
    if rel == ".":
        return ""
    return rel.replace(os.sep, "/") + "/"


def build_navbar(root, current_file, categories, config):
    rr = _rel_root(root, current_file)
    cat_links = "".join(
        '<li><a href="{rr}category_{cat}.html">{label}</a></li>'.format(
            rr=rr, cat=cat, label=cat.replace("_", " ").title()
        )
        for cat in list(categories)[:6]
    )
    return (
        '<nav class="navbar">\n'
        '  <div class="container">\n'
        '    <a class="navbar-brand" href="{rr}index.html">\U0001f6d2 Shop</a>\n'
        '    <ul class="navbar-nav">\n'
        '      <li><a href="{rr}index.html">Home</a></li>\n'
        '      <li><a href="{rr}products/">Products</a></li>\n'
        "      {cat_links}\n"
        "    </ul>\n"
        "  </div>\n"
        "</nav>"
    ).format(rr=rr, cat_links=cat_links)


def build_footer(config):
    wickr = html.escape(config.get("contact_wickr", ""))
    email = html.escape(config.get("contact_email", ""))
    wickr_html = (
        "<p>Wickr: <strong>{}</strong></p>".format(wickr) if wickr else ""
    )
    email_html = (
        '<p>Email: <a href="mailto:{e}">{e}</a></p>'.format(e=email) if email else ""
    )
    year = datetime.datetime.now().year
    return (
        "<footer>\n"
        "  <div class=\"container\">\n"
        "    <div class=\"footer-content\">\n"
        "      <div><h3>Privacy</h3>"
        "<p>All orders processed anonymously. No account required.</p></div>\n"
        "      <div><h3>Payment</h3>"
        "<p>We accept Monero (XMR) and Bitcoin (BTC) for maximum privacy.</p></div>\n"
        "      <div><h3>Contact</h3>{wickr}{email}</div>\n"
        "    </div>\n"
        "    <div class=\"footer-bottom\">"
        "<p>&copy; {year} &mdash; Secured with Monero.</p></div>\n"
        "  </div>\n"
        "</footer>"
    ).format(wickr=wickr_html, email=email_html, year=year)


def build_page_shell(title, body, root, current_file, categories, config, extra_head=""):
    rr = _rel_root(root, current_file)
    css_path = rr + "css/style.css"
    js_path = rr + "js/main.js"
    navbar = build_navbar(root, current_file, categories, config)
    footer = build_footer(config)
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '  <meta charset="UTF-8">\n'
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        "  <title>{title}</title>\n"
        '  <link rel="stylesheet" href="{css}">\n'
        "  {extra}\n"
        "</head>\n"
        "<body>\n"
        "{navbar}\n"
        '<main class="container main-content">\n'
        "{body}\n"
        "</main>\n"
        "{footer}\n"
        '<script src="{js}"></script>\n'
        "</body>\n"
        "</html>"
    ).format(
        title=html.escape(title),
        css=css_path,
        js=js_path,
        extra=extra_head,
        navbar=navbar,
        body=body,
        footer=footer,
    )


# ---------------------------------------------------------------------------
# CONTINENT / SHIPPING CONTROLS
# ---------------------------------------------------------------------------

def _continent_options(config):
    opts = ""
    for continent, mult in config.get("continent_pricing", {}).items():
        label = continent.replace("_", " ").title()
        opts += '<option value="{}">{} (&times;{})</option>\n'.format(
            continent, label, mult
        )
    return opts


def _shipping_options(config):
    labels = {
        "domestic_standard": "Domestic Standard",
        "domestic_express": "Domestic Express",
        "international_standard": "International Standard",
        "international_priority": "International Priority",
        "international_express": "International Express",
    }
    opts = ""
    for method, cost in config.get("shipping_methods", {}).items():
        label = labels.get(method, method.replace("_", " ").title())
        opts += '<option value="{}">{} (+${:.2f})</option>\n'.format(
            method, label, cost
        )
    return opts


def build_pricing_controls(config):
    return (
        '<div class="pricing-controls">\n'
        "  <h3>Shipping &amp; Region</h3>\n"
        '  <div class="form-group">\n'
        '    <label for="continent-select">Your Region</label>\n'
        '    <select id="continent-select" name="continent">\n'
        "      {co}"
        "    </select>\n"
        "  </div>\n"
        '  <div class="form-group">\n'
        '    <label for="shipping-select">Shipping Method</label>\n'
        '    <select id="shipping-select" name="shipping">\n'
        "      {so}"
        "    </select>\n"
        "  </div>\n"
        "</div>"
    ).format(co=_continent_options(config), so=_shipping_options(config))


# ---------------------------------------------------------------------------
# PAYMENT PAGE
# ---------------------------------------------------------------------------

def generate_payment_page(root, config, categories, logger, dry_run=False):
    """Generate a modern client-side payment.php page."""
    wallet = config.get("monero_wallet_address", "")
    wickr = html.escape(config.get("contact_wickr", ""))
    email = html.escape(config.get("contact_email", ""))
    continent_js = json.dumps(config.get("continent_pricing", {}))
    shipping_js = json.dumps(config.get("shipping_methods", {}))
    qr_url = "https://api.qrserver.com/v1/create-qr-code/?size=200x200&data={}".format(
        html.escape(wallet)
    )

    navbar = build_navbar(root, os.path.join(root, "payment.php"), categories, config)
    footer = build_footer(config)

    wickr_card = (
        '<div class="card" style="flex:1;min-width:180px">'
        "<strong>Wickr</strong><br>"
        '<span style="color:var(--accent)">{}</span>'
        "</div>".format(wickr)
        if wickr else ""
    )
    email_card = (
        '<div class="card" style="flex:1;min-width:180px">'
        "<strong>Email</strong><br>"
        '<a href="mailto:{e}">{e}</a>'
        "</div>".format(e=email)
        if email else ""
    )

    page = (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '  <meta charset="UTF-8">\n'
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        '  <meta name="robots" content="noindex, nofollow">\n'
        "  <title>Secure Checkout</title>\n"
        '  <link rel="stylesheet" href="css/style.css">\n'
        "</head>\n"
        "<body>\n"
        "{navbar}\n"
        '<main class="container main-content">\n'
        '<div class="payment-container">\n'
        '  <div class="page-hero" style="padding-top:1.5rem">\n'
        "    <h1>Secure Checkout</h1>\n"
        "    <p>Complete your order with anonymous cryptocurrency payment.</p>\n"
        "  </div>\n"
        "\n"
        '  <div class="payment-step" id="order-summary">\n'
        "    <h2>Order Summary</h2>\n"
        "    <table>\n"
        "      <thead><tr><th>Item</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead>\n"
        "      <tbody><tr>\n"
        '        <td id="display-item">&#8212;</td>\n'
        '        <td id="display-qty">&#8212;</td>\n'
        '        <td id="display-price">&#8212;</td>\n'
        '        <td id="display-total">&#8212;</td>\n'
        "      </tr></tbody>\n"
        "    </table>\n"
        "  </div>\n"
        "\n"
        '  <div class="payment-step">\n'
        "    <h2>Shipping Region</h2>\n"
        '    <div class="form-group">\n'
        '      <label for="continent-select">Your Region</label>\n'
        '      <select id="continent-select">\n'
        "        {co}"
        "      </select>\n"
        "    </div>\n"
        '    <div class="form-group">\n'
        '      <label for="shipping-select">Shipping Method</label>\n'
        '      <select id="shipping-select">\n'
        "        {so}"
        "      </select>\n"
        "    </div>\n"
        '    <div style="margin-top:1rem;padding:1rem;'
        'background:var(--bg-secondary);border-radius:var(--radius-sm)">\n'
        "      <strong>Order Total: </strong>\n"
        '      <span id="order-total" style="color:var(--accent);font-size:1.2rem;'
        'font-weight:700">&#8212;</span>\n'
        "    </div>\n"
        "  </div>\n"
        "\n"
        '  <div class="payment-step">\n'
        "    <h2>Live Crypto Prices</h2>\n"
        '    <div class="price-display">\n'
        '      <div class="price-item">\n'
        '        <div class="currency">XMR (Monero)</div>\n'
        '        <div class="amount" id="xmr-amount">&#8230;</div>\n'
        '        <div class="usd-equiv" id="xmr-usd">Loading&hellip;</div>\n'
        "      </div>\n"
        '      <div class="price-item">\n'
        '        <div class="currency">BTC (Bitcoin)</div>\n'
        '        <div class="amount" id="btc-amount">&#8230;</div>\n'
        '        <div class="usd-equiv" id="btc-usd">Loading&hellip;</div>\n'
        "      </div>\n"
        "    </div>\n"
        '    <p style="font-size:0.8rem;color:var(--text-muted)">'
        "Prices fetched live from CoinGecko. Refresh to update.</p>\n"
        "  </div>\n"
        "\n"
        '  <div class="payment-step">\n'
        "    <h2>Pay with Monero (XMR)</h2>\n"
        "    <p style=\"margin-bottom:1rem;font-size:0.9rem;\">Send the exact XMR amount "
        "shown above to the address below.</p>\n"
        '    <div style="text-align:center;margin-bottom:1rem;">\n'
        '      <img id="xmr-qr" src="{qr}" alt="Monero QR Code"\n'
        '           width="200" height="200"\n'
        '           style="border:6px solid #fff;border-radius:var(--radius-sm)">\n'
        "    </div>\n"
        '    <div class="wallet-address-box" id="xmr-address">{wallet}\n'
        '      <button class="copy-btn" onclick="copyAddress()">Copy</button>\n'
        "    </div>\n"
        "  </div>\n"
        "\n"
        '  <div class="payment-step">\n'
        "    <h2>Payment Status</h2>\n"
        '    <div class="status-box">\n'
        '      <div class="status-indicator"></div>\n'
        "      <div><strong>Waiting for Deposit</strong><br>\n"
        '        <span style="font-size:0.85rem;color:var(--text-secondary)">'
        "Send payment to the address above. Once confirmed, contact us with your TXID.</span>\n"
        "      </div>\n"
        "    </div>\n"
        "  </div>\n"
        "\n"
        '  <div class="payment-step">\n'
        "    <h2>After Payment</h2>\n"
        "    <p>Once you have sent your payment, contact us with your transaction ID (TXID) "
        "and shipping address.</p>\n"
        '    <div style="margin-top:1rem;display:flex;gap:1rem;flex-wrap:wrap;">\n'
        "      {wickr_card}\n"
        "      {email_card}\n"
        "    </div>\n"
        "  </div>\n"
        "\n"
        "</div>\n"
        "</main>\n"
        "{footer}\n"
        "\n"
        "<script>\n"
        "var CONTINENTS = {continent_js};\n"
        "var SHIPPING   = {shipping_js};\n"
        "\n"
        "(function () {{\n"
        "  var p = new URLSearchParams(window.location.search);\n"
        "  var item  = p.get('item')   || 'Order';\n"
        "  var qty   = p.get('amount') || p.get('qty') || '1';\n"
        "  var price = parseFloat(p.get('price') || '0');\n"
        "  document.getElementById('display-item').textContent  = item;\n"
        "  document.getElementById('display-qty').textContent   = qty;\n"
        "  document.getElementById('display-price').textContent = '$' + price.toFixed(2);\n"
        "  window._basePrice = price;\n"
        "  window._baseQty   = parseInt(qty, 10) || 1;\n"
        "  updateOrderTotal();\n"
        "}})();\n"
        "\n"
        "function updateOrderTotal() {{\n"
        "  var cSel = document.getElementById('continent-select');\n"
        "  var sSel = document.getElementById('shipping-select');\n"
        "  var mult = cSel ? (CONTINENTS[cSel.value] || 1.0) : 1.0;\n"
        "  var ship = sSel ? (SHIPPING[sSel.value]   || 0)   : 0;\n"
        "  var total = (window._basePrice * mult * window._baseQty) + ship;\n"
        "  document.getElementById('display-total').textContent = '$' + total.toFixed(2);\n"
        "  document.getElementById('order-total').textContent   = '$' + total.toFixed(2);\n"
        "  if (window._xmrPrice) updateCryptoAmounts(total);\n"
        "}}\n"
        "\n"
        "document.getElementById('continent-select').addEventListener('change', updateOrderTotal);\n"
        "document.getElementById('shipping-select').addEventListener('change', updateOrderTotal);\n"
        "\n"
        "function updateCryptoAmounts(usd) {{\n"
        "  if (!usd || !window._xmrPrice || !window._btcPrice) return;\n"
        "  document.getElementById('xmr-amount').textContent ="
        " (usd / window._xmrPrice).toFixed(6) + ' XMR';\n"
        "  document.getElementById('btc-amount').textContent ="
        " (usd / window._btcPrice).toFixed(8) + ' BTC';\n"
        "  document.getElementById('xmr-usd').textContent ="
        " '1 XMR = $' + window._xmrPrice.toFixed(2);\n"
        "  document.getElementById('btc-usd').textContent ="
        " '1 BTC = $' + window._btcPrice.toLocaleString();\n"
        "}}\n"
        "\n"
        "fetch('https://api.coingecko.com/api/v3/simple/price?ids=monero,bitcoin&vs_currencies=usd')\n"
        "  .then(function (r) {{ return r.json(); }})\n"
        "  .then(function (d) {{\n"
        "    window._xmrPrice = d.monero  ? d.monero.usd  : null;\n"
        "    window._btcPrice = d.bitcoin ? d.bitcoin.usd : null;\n"
        "    var tot = parseFloat(\n"
        "      (document.getElementById('order-total').textContent || '0').replace('$', '')\n"
        "    ) || 0;\n"
        "    if (tot > 0) updateCryptoAmounts(tot);\n"
        "  }})\n"
        "  .catch(function () {{\n"
        "    document.getElementById('xmr-usd').textContent = 'Price fetch failed.';\n"
        "    document.getElementById('btc-usd').textContent = '';\n"
        "  }});\n"
        "\n"
        "function copyAddress() {{\n"
        "  var addr = '{wallet_escaped}';\n"
        "  if (navigator.clipboard) {{\n"
        "    navigator.clipboard.writeText(addr).then(function () {{\n"
        "      var btn = document.querySelector('.copy-btn');\n"
        "      btn.textContent = 'Copied!';\n"
        "      setTimeout(function () {{ btn.textContent = 'Copy'; }}, 2000);\n"
        "    }});\n"
        "  }} else {{\n"
        "    var ta = document.createElement('textarea');\n"
        "    ta.value = addr; document.body.appendChild(ta);\n"
        "    ta.select(); document.execCommand('copy');\n"
        "    document.body.removeChild(ta);\n"
        "  }}\n"
        "}}\n"
        "</script>\n"
        "</body>\n"
        "</html>"
    ).format(
        navbar=navbar,
        co=_continent_options(config),
        so=_shipping_options(config),
        qr=qr_url,
        wallet=html.escape(wallet),
        wallet_escaped=wallet.replace("'", "\\'"),
        wickr_card=wickr_card,
        email_card=email_card,
        footer=footer,
        continent_js=continent_js,
        shipping_js=shipping_js,
    )

    payment_path = os.path.join(root, "payment.php")
    logger.log("Generated modern payment.php")
    write_file_safe(payment_path, page, dry_run)


# ---------------------------------------------------------------------------
# CATEGORY PAGES
# ---------------------------------------------------------------------------

def _product_card(product, root, ref_file):
    """Build a product card HTML snippet."""
    rel_path = os.path.relpath(product["filepath"], os.path.dirname(ref_file)).replace(
        os.sep, "/"
    )
    price = product.get("price", "0")
    name = html.escape(product.get("name", "Product"))
    desc = html.escape(product.get("description", "")[:100])
    qty = product.get("quantity", "1")
    if product.get("images"):
        img = '<img class="product-image" src="{}" alt="{}" loading="lazy">'.format(
            html.escape(product["images"][0]), name
        )
    else:
        img = (
            '<div class="product-image" style="display:flex;align-items:center;'
            'justify-content:center;color:var(--text-muted);font-size:3rem;">\U0001f4e6</div>'
        )
    return (
        '<div class="product-card" data-price="{price}" data-name="{name}" data-qty="{qty}">\n'
        "  {img}\n"
        '  <div class="product-body">\n'
        '    <div class="product-title">{name}</div>\n'
        '    <div class="product-price" data-base-price="{price}">${price}</div>\n'
        '    <div class="product-desc">{desc}</div>\n'
        '    <a href="{path}" class="btn-buy">View Product</a>\n'
        "  </div>\n"
        "</div>"
    ).format(price=price, name=name, qty=qty, img=img, desc=desc, path=rel_path)


def generate_category_page(category, products, root, all_categories, config,
                            logger, dry_run=False):
    cat_title = category.replace("_", " ").title()
    cat_file = os.path.join(root, "category_{}.html".format(category))
    cards = "\n".join(_product_card(p, root, cat_file) for p in products)
    if not cards:
        cards = "<p>No products in this category yet.</p>"

    body = (
        '<div class="page-hero">\n'
        "  <h1>{title}</h1>\n"
        "  <p>{n} product(s) in this category.</p>\n"
        "</div>\n"
        '<div class="sort-controls">\n'
        '  <label for="sort-select">Sort by:</label>\n'
        '  <select id="sort-select">\n'
        '    <option value="">Default</option>\n'
        '    <option value="price-asc">Price: Low to High</option>\n'
        '    <option value="price-desc">Price: High to Low</option>\n'
        '    <option value="name-asc">Name: A&#8211;Z</option>\n'
        '    <option value="name-desc">Name: Z&#8211;A</option>\n'
        '    <option value="qty-desc">Quantity: Most First</option>\n'
        '    <option value="qty-asc">Quantity: Least First</option>\n'
        "  </select>\n"
        "</div>\n"
        '<div class="product-grid" id="product-grid">\n'
        "{cards}\n"
        "</div>"
    ).format(title=cat_title, n=len(products), cards=cards)

    page = build_page_shell(
        "{} — Products".format(cat_title), body, root, cat_file, all_categories, config
    )
    logger.log(
        "Generated category_{}.html ({} products)".format(category, len(products))
    )
    write_file_safe(cat_file, page, dry_run)


# ---------------------------------------------------------------------------
# INDEX PAGE
# ---------------------------------------------------------------------------

def update_index_page(root, categories, all_categories, config, logger, dry_run=False):
    """Inject a category grid and featured products into the existing index, or create one."""
    index_path = None
    for name in ("index.html", "index.php"):
        candidate = os.path.join(root, name)
        if os.path.exists(candidate):
            index_path = candidate
            break

    cat_cards = "".join(
        '<a href="category_{cat}.html" class="category-card">'
        "<h3>{title}</h3>"
        '<div class="count">{n} product(s)</div>'
        "</a>\n".format(
            cat=cat,
            title=cat.replace("_", " ").title(),
            n=len(prods),
        )
        for cat, prods in categories.items()
    )

    section = (
        "<!-- AUTO-GENERATED CATEGORY SECTION -->\n"
        '<section class="category-section" style="margin:2rem 0">\n'
        "  <h2 style=\"margin-bottom:1rem\">Browse by Category</h2>\n"
        '  <div class="category-grid">\n'
        "    {cats}\n"
        "  </div>\n"
        "</section>\n"
        "<!-- END AUTO-GENERATED CATEGORY SECTION -->"
    ).format(cats=cat_cards)

    if index_path:
        content = read_file_safe(index_path)
        # Remove any previously injected section
        content = re.sub(
            r"<!-- AUTO-GENERATED CATEGORY SECTION -->.*?"
            r"<!-- END AUTO-GENERATED CATEGORY SECTION -->",
            "",
            content,
            flags=re.DOTALL,
        )
        if "</main>" in content:
            content = content.replace("</main>", section + "\n</main>", 1)
        elif "</body>" in content:
            content = content.replace("</body>", section + "\n</body>", 1)
        else:
            content += "\n" + section
        logger.log("Updated index page with category section")
        write_file_safe(index_path, content, dry_run)
    else:
        # Build a brand-new index page
        all_products = [p for prods in categories.values() for p in prods]
        new_index = os.path.join(root, "index.html")
        top_cards = "".join(
            _product_card(p, root, new_index) + "\n" for p in all_products[:8]
        )
        body = (
            '<div class="page-hero">\n'
            "  <h1>Welcome to Our Store</h1>\n"
            "  <p>Browse our products and pay anonymously with Monero.</p>\n"
            "</div>\n"
            "<section style=\"margin-bottom:2.5rem\">\n"
            "  <h2 style=\"margin-bottom:1rem\">Shop by Category</h2>\n"
            '  <div class="category-grid">\n'
            "    {cats}\n"
            "  </div>\n"
            "</section>\n"
            "<section>\n"
            "  <h2 style=\"margin-bottom:1rem\">Featured Products</h2>\n"
            '  <div class="sort-controls">\n'
            '    <label for="sort-select">Sort by:</label>\n'
            '    <select id="sort-select">\n'
            '      <option value="">Default</option>\n'
            '      <option value="price-asc">Price: Low to High</option>\n'
            '      <option value="price-desc">Price: High to Low</option>\n'
            '      <option value="name-asc">Name: A&#8211;Z</option>\n'
            '      <option value="name-desc">Name: Z&#8211;A</option>\n'
            "    </select>\n"
            "  </div>\n"
            '  <div class="product-grid" id="product-grid">\n'
            "    {cards}\n"
            "  </div>\n"
            "</section>"
        ).format(cats=cat_cards, cards=top_cards)

        page = build_page_shell(
            "Online Store — Secure Anonymous Shopping",
            body, root, new_index, all_categories, config,
        )
        logger.log("Generated new index.html")
        write_file_safe(new_index, page, dry_run)


# ---------------------------------------------------------------------------
# PRODUCT PAGE ENHANCER
# ---------------------------------------------------------------------------

def enhance_product_page(filepath, product, root, all_categories, config,
                          logger, dry_run=False):
    """Add continent/shipping pricing controls to an existing product page."""
    content = read_file_safe(filepath)
    if not content:
        return False
    if "continent-select" in content:
        return False  # already enhanced

    price = product.get("price", "0")
    name = html.escape(product.get("name", "Product"))
    continent_js = json.dumps(config.get("continent_pricing", {}))
    shipping_js = json.dumps(config.get("shipping_methods", {}))

    pricing_block = build_pricing_controls(config)
    section = (
        "<!-- AUTO-GENERATED PRICING SECTION -->\n"
        '<div class="pricing-section card" style="margin:1.5rem 0">\n'
        "  <h2 style=\"margin-bottom:1rem\">Order</h2>\n"
        "  {pricing}\n"
        '  <div class="form-group">\n'
        '    <label for="qty">Quantity</label>\n'
        '    <input type="number" id="qty" name="amount" value="1" min="1" max="999">\n'
        "  </div>\n"
        '  <div style="padding:1rem;background:var(--bg-primary);'
        'border-radius:var(--radius-sm);margin-bottom:1rem">\n'
        "    <strong>Total: </strong>\n"
        '    <span id="order-total" style="color:var(--accent);font-size:1.2rem;font-weight:700"'
        '          data-item-base-price="{price}">${price}</span>\n'
        '    <span style="color:var(--text-muted);font-size:0.85rem"> (+ shipping)</span>\n'
        "  </div>\n"
        '  <a id="buy-btn"\n'
        '     href="payment.php?item={name}&price={price}&amount=1"\n'
        '     class="btn btn-primary" style="display:block;text-align:center"\n'
        "     onclick=\"this.href='payment.php?item={name}&price={price}&amount='"
        "+(document.getElementById('qty').value||1)\">\n"
        "    Proceed to Payment &rarr;\n"
        "  </a>\n"
        "</div>\n"
        "<script>\n"
        "var CONTINENTS = {continent_js};\n"
        "var SHIPPING   = {shipping_js};\n"
        "function updateProductTotal() {{\n"
        "  var c = document.getElementById('continent-select');\n"
        "  var s = document.getElementById('shipping-select');\n"
        "  var q = document.getElementById('qty');\n"
        "  var mult = c ? (CONTINENTS[c.value] || 1.0) : 1.0;\n"
        "  var ship = s ? (SHIPPING[s.value]   || 0)   : 0;\n"
        "  var qty  = parseInt(q ? q.value : 1, 10) || 1;\n"
        "  var total = ({price} * mult * qty) + ship;\n"
        "  var el = document.getElementById('order-total');\n"
        "  if (el) el.textContent = '$' + total.toFixed(2);\n"
        "  var btn = document.getElementById('buy-btn');\n"
        "  if (btn) btn.href = 'payment.php?item={name}&price='"
        "+ ({price}*mult).toFixed(2) + '&amount=' + qty;\n"
        "}}\n"
        "document.addEventListener('DOMContentLoaded', function () {{\n"
        "  var c = document.getElementById('continent-select');\n"
        "  var s = document.getElementById('shipping-select');\n"
        "  var q = document.getElementById('qty');\n"
        "  if (c) c.addEventListener('change', updateProductTotal);\n"
        "  if (s) s.addEventListener('change', updateProductTotal);\n"
        "  if (q) q.addEventListener('input',  updateProductTotal);\n"
        "}});\n"
        "</script>\n"
        "<!-- END AUTO-GENERATED PRICING SECTION -->"
    ).format(
        pricing=pricing_block,
        price=price,
        name=name,
        continent_js=continent_js,
        shipping_js=shipping_js,
    )

    new_content = content
    # Remove any previously generated section
    new_content = re.sub(
        r"<!-- AUTO-GENERATED PRICING SECTION -->.*?"
        r"<!-- END AUTO-GENERATED PRICING SECTION -->",
        "",
        new_content,
        flags=re.DOTALL,
    )

    if "</body>" in new_content:
        new_content = new_content.replace("</body>", section + "\n</body>", 1)
    else:
        new_content += "\n" + section

    if new_content != content:
        logger.log(
            "Enhanced product page: {}".format(os.path.relpath(filepath, root))
        )
        write_file_safe(filepath, new_content, dry_run)
        return True
    return False


def _create_product_page_if_needed(product, root, all_categories, config,
                                   logger, dry_run=False):
    """Create a basic HTML product page for a product that has no existing file.

    This is used for products discovered via :func:`parse_products_from_index`
    that are not yet backed by an individual product page.  The generated page
    is intentionally minimal so that :func:`enhance_product_page` can enrich it
    with pricing controls in the normal pipeline flow.
    """
    filepath = product["filepath"]
    if os.path.exists(filepath):
        return

    name = html.escape(product.get("name", "Product"))
    price = product.get("price", "0")
    description = html.escape(product.get("description", ""))

    if product.get("images"):
        img_html = (
            '<img class="product-image" src="{}" alt="{}" loading="lazy"'
            ' style="max-width:100%;border-radius:var(--radius)">'.format(
                html.escape(product["images"][0]), name
            )
        )
    else:
        img_html = ""

    body = (
        '<div class="page-hero">\n'
        "  <h1>{name}</h1>\n"
        "</div>\n"
        '<div class="card" style="margin-bottom:1.5rem">\n'
        "  {img}\n"
        '  <p class="product-price" style="font-size:1.4rem;'
        'color:var(--accent);font-weight:700;margin:1rem 0">${price}</p>\n'
        "  <p>{desc}</p>\n"
        "</div>"
    ).format(name=name, price=price, img=img_html, desc=description)

    page = build_page_shell(name, body, root, filepath, all_categories, config)
    logger.log("Created product page: {}".format(os.path.relpath(filepath, root)))
    write_file_safe(filepath, page, dry_run)


# ---------------------------------------------------------------------------
# CSS / JS INJECTION INTO EXISTING PAGES
# ---------------------------------------------------------------------------

def inject_css_link(filepath, root, logger, dry_run=False):
    """Ensure the page references css/style.css."""
    content = read_file_safe(filepath)
    if not content or "style.css" in content:
        return False

    rel_css = os.path.relpath(
        os.path.join(root, "css", "style.css"), os.path.dirname(filepath)
    ).replace(os.sep, "/")
    tag = '<link rel="stylesheet" href="{}">'.format(rel_css)

    if "</head>" in content:
        new_content = content.replace("</head>", "  {}\n</head>".format(tag), 1)
    elif re.search(r"<head[^>]*>", content, re.IGNORECASE):
        new_content = re.sub(
            r"(<head[^>]*>)", r"\1\n  " + tag, content, count=1, flags=re.IGNORECASE
        )
    else:
        new_content = tag + "\n" + content

    if new_content != content:
        logger.log("Injected CSS link: {}".format(os.path.relpath(filepath, root)))
        write_file_safe(filepath, new_content, dry_run)
        return True
    return False


def inject_js_link(filepath, root, logger, dry_run=False):
    """Ensure the page references js/main.js."""
    content = read_file_safe(filepath)
    if not content or "main.js" in content:
        return False

    rel_js = os.path.relpath(
        os.path.join(root, "js", "main.js"), os.path.dirname(filepath)
    ).replace(os.sep, "/")
    tag = '<script src="{}"></script>'.format(rel_js)

    if "</body>" in content:
        new_content = content.replace("</body>", "  {}\n</body>".format(tag), 1)
    else:
        new_content = content + "\n" + tag + "\n"

    if new_content != content:
        logger.log("Injected JS link: {}".format(os.path.relpath(filepath, root)))
        write_file_safe(filepath, new_content, dry_run)
        return True
    return False


# ---------------------------------------------------------------------------
# WRITE STATIC ASSETS
# ---------------------------------------------------------------------------

def write_css_and_js(root, logger, dry_run=False):
    for subdir, content, name in (
        ("css", DARK_THEME_CSS, "style.css"),
        ("js", MAIN_JS, "main.js"),
    ):
        dirpath = os.path.join(root, subdir)
        if not dry_run:
            os.makedirs(dirpath, exist_ok=True)
        fpath = os.path.join(dirpath, name)
        logger.log("Writing {}/{}".format(subdir, name))
        write_file_safe(fpath, content, dry_run)


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description="website_updater.py — Modernize static HTML/PHP website files."
    )
    ap.add_argument(
        "--dry-run", action="store_true",
        help="Preview what would change without modifying any files.",
    )
    ap.add_argument(
        "--config", default="config.json",
        help="Path to config.json (default: config.json in current directory).",
    )
    ap.add_argument(
        "--root", default=None,
        help="Path to website root directory (overrides config.json website_root).",
    )
    args = ap.parse_args()
    dry_run = args.dry_run

    if dry_run:
        print("=" * 60)
        print("DRY-RUN MODE — No files will be modified.")
        print("=" * 60)

    # ── Config ──────────────────────────────────────────────────────────────
    config_path = args.config
    if not os.path.isabs(config_path):
        config_path = os.path.join(os.getcwd(), config_path)

    log_path = os.path.join(os.path.dirname(config_path), "update_log.txt")
    logger = Logger(log_path, dry_run=dry_run)

    config = load_config(config_path, logger)

    # Determine website root
    if args.root:
        website_root = os.path.abspath(args.root)
    else:
        raw = config.get("website_root", ".")
        website_root = (
            os.path.abspath(raw)
            if os.path.isabs(raw)
            else os.path.abspath(os.path.join(os.path.dirname(config_path), raw))
        )

    if not os.path.isdir(website_root):
        logger.log("Website root does not exist: {}".format(website_root), "ERROR")
        sys.exit(1)

    logger.log("Website root: {}".format(website_root))

    # ── Keywords ────────────────────────────────────────────────────────────
    kw_file = config.get("keywords_file", "keywords.txt")
    if not os.path.isabs(kw_file):
        kw_file = os.path.join(website_root, kw_file)
    keywords = load_keywords(kw_file, logger)

    # ── Step 1: Backup ───────────────────────────────────────────────────────
    logger.log("─── Step 1: Creating backup ───")
    create_backup(website_root, logger, dry_run)

    # ── Step 2: Directory structure ──────────────────────────────────────────
    logger.log("─── Step 2: Ensuring directory structure ───")
    ensure_directory_structure(website_root, logger, dry_run)

    # ── Step 3: Write CSS & JS ───────────────────────────────────────────────
    logger.log("─── Step 3: Writing CSS & JS assets ───")
    write_css_and_js(website_root, logger, dry_run)

    # ── Step 4: Discover files ───────────────────────────────────────────────
    logger.log("─── Step 4: Discovering files ───")
    files = discover_files(website_root)
    logger.log(
        "Found: {} HTML, {} PHP, {} CSS, {} JS, {} images".format(
            len(files["html"]), len(files["php"]),
            len(files["css"]), len(files["js"]), len(files["images"]),
        )
    )

    # ── Step 5: Check & fix broken links ────────────────────────────────────
    logger.log("─── Step 5: Checking and fixing broken links ───")
    file_index = build_file_index(website_root, files)
    total_fixes = sum(
        check_and_fix_links(fp, website_root, file_index, logger, dry_run)
        for fp in files["html"] + files["php"]
    )
    logger.log("Total broken link fixes: {}".format(total_fixes))

    # ── Step 6: Inject CSS / JS links ───────────────────────────────────────
    logger.log("─── Step 6: Injecting CSS/JS references ───")
    for fp in files["html"] + files["php"]:
        inject_css_link(fp, website_root, logger, dry_run)
        inject_js_link(fp, website_root, logger, dry_run)

    # ── Step 7: SEO meta tags ────────────────────────────────────────────────
    logger.log("─── Step 7: Injecting SEO meta tags ───")
    site_url = config.get("site_url", "http://localhost")
    for fp in files["html"] + files["php"]:
        inject_seo_tags(fp, keywords, site_url, logger, dry_run)

    # ── Step 8: Parse products & categorise ─────────────────────────────────
    logger.log("─── Step 8: Parsing products and categorising ───")

    # Primary: try to extract products from the index page
    products = parse_products_from_index(website_root, logger)

    if products:
        logger.log(
            "Using {} product(s) parsed from index page (primary source)".format(
                len(products)
            )
        )
    else:
        # Fallback: discover individual product files
        logger.log(
            "No index products found; falling back to file-based product discovery"
        )
        products = [
            parse_product(fp)
            for fp in files["html"] + files["php"]
            if is_product_file(fp, website_root)
        ]
        logger.log("Found {} product page(s) via file scan".format(len(products)))

    categories = collections.OrderedDict()
    for product in products:
        cat = product["category"]
        categories.setdefault(cat, []).append(product)

    all_category_names = sorted(categories.keys())
    logger.log(
        "Categories: {}".format(
            ", ".join(all_category_names) if all_category_names else "none"
        )
    )

    # Create individual product pages for index-parsed products that have no file
    for product in products:
        _create_product_page_if_needed(
            product, website_root, all_category_names, config, logger, dry_run
        )

    # ── Step 9: Enhance product pages ───────────────────────────────────────
    logger.log("─── Step 9: Enhancing product pages with pricing controls ───")
    for product in products:
        enhance_product_page(
            product["filepath"], product, website_root,
            all_category_names, config, logger, dry_run,
        )

    # ── Step 10: Category pages ──────────────────────────────────────────────
    logger.log("─── Step 10: Generating category pages ───")
    for category, cat_products in categories.items():
        generate_category_page(
            category, cat_products, website_root,
            all_category_names, config, logger, dry_run,
        )

    # ── Step 11: Index page ──────────────────────────────────────────────────
    logger.log("─── Step 11: Updating index page ───")
    update_index_page(
        website_root, categories, all_category_names, config, logger, dry_run
    )

    # ── Step 12: Payment page ────────────────────────────────────────────────
    logger.log("─── Step 12: Generating payment page ───")
    generate_payment_page(website_root, config, all_category_names, logger, dry_run)

    # ── Step 13: Sitemap & robots ────────────────────────────────────────────
    logger.log("─── Step 13: Generating sitemap.xml and robots.txt ───")
    files_after = discover_files(website_root)
    generate_sitemap(website_root, files_after, site_url, logger, dry_run)
    generate_robots(website_root, site_url, logger, dry_run)

    # ── Done ─────────────────────────────────────────────────────────────────
    logger.log("─── Complete ───")
    if not dry_run:
        logger.save()
        logger.log("Log saved to: {}".format(log_path))

    print("\n\u2713 website_updater.py finished successfully.")
    if dry_run:
        print("  (DRY-RUN mode \u2014 no files were modified)")
    else:
        print("  Log: {}".format(log_path))


if __name__ == "__main__":
    main()
