#!/usr/bin/env python3
"""
website_updater.py — Static Website Updater Tool

Restructures, SEO-optimizes, and modernizes static HTML/PHP website files.
Adds continent-based pricing, shipping selectors, Monero payment pages,
product category pages, and a modern dark-theme CSS framework — all without
deleting any existing files.

Usage:
    python website_updater.py [--dry-run] [--config path/to/config.json]

Requirements: Python 3.8+, standard library only.
"""

import argparse
import collections
import copy
import datetime
import hashlib
import html
import html.parser
import json
import os
import pathlib
import re
import shutil
import sys
from urllib.parse import urlparse

# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------

DEFAULT_CONFIG = {
    "monero_wallet_address": "YOUR_MONERO_ADDRESS_HERE",
    "website_root": ".",
    "keywords_file": "keywords.txt",
    "site_url": "http://yoursite.onion",
    "shipping_methods": {
        "domestic_standard": 5.00,
        "domestic_express": 10.00,
        "international_standard": 15.00,
        "international_priority": 25.00,
        "international_express": 40.00,
    },
    "continent_pricing": {
        "north_america": 1.0,
        "europe": 1.2,
        "south_america": 1.5,
        "asia": 1.8,
        "africa": 2.0,
        "oceania": 1.6,
        "antarctica": 2.0,
    },
    "contact_wickr": "yourwickrhandle",
    "contact_email": "your@email.com",
}

# Keyword lists used to infer product categories
CATEGORY_KEYWORDS = {
    "electronics": [
        "phone", "laptop", "computer", "tablet", "camera", "electronic",
        "tech", "gadget", "device", "screen", "monitor", "keyboard",
        "mouse", "battery", "charger", "cable",
    ],
    "clothing": [
        "shirt", "pants", "dress", "jacket", "shoe", "boot", "hat",
        "cap", "clothing", "apparel", "fashion", "wear", "outfit", "jeans",
    ],
    "books": [
        "book", "novel", "guide", "manual", "textbook", "magazine",
        "journal", "ebook", "pdf",
    ],
    "food": [
        "food", "drink", "beverage", "snack", "meal", "nutrition",
        "organic", "supplement", "coffee", "tea",
    ],
    "health": [
        "health", "medical", "medicine", "vitamin", "supplement",
        "pharmacy", "pill", "tablet", "capsule", "wellness",
    ],
    "tools": [
        "tool", "equipment", "hardware", "instrument", "machine",
        "power", "drill", "saw", "hammer", "wrench",
    ],
    "home": [
        "home", "house", "furniture", "decor", "kitchen", "bedroom",
        "bathroom", "garden", "outdoor", "lamp", "chair",
    ],
    "software": [
        "software", "app", "application", "program", "license", "key",
        "subscription", "digital", "download", "serial",
    ],
    "services": [
        "service", "consulting", "support", "maintenance", "repair",
        "installation", "tutorial",
    ],
    "other": [],
}

# ---------------------------------------------------------------------------
# DARK THEME CSS
# ---------------------------------------------------------------------------

DARK_THEME_CSS = """\
/* Modern Dark Theme — generated by website_updater.py */
:root {
  --bg-primary:   #0d0d0d;
  --bg-secondary: #1a1a1a;
  --bg-card:      #222222;
  --bg-hover:     #2a2a2a;
  --text-primary:   #e8e8e8;
  --text-secondary: #a0a0a0;
  --text-muted:     #666666;
  --accent:       #ff6b35;
  --accent-hover: #ff8855;
  --accent-dark:  #cc5528;
  --border:       #333333;
  --border-light: #444444;
  --success: #4caf50;
  --warning: #ff9800;
  --error:   #f44336;
  --shadow:      0 4px 20px rgba(0,0,0,0.5);
  --shadow-card: 0 2px 10px rgba(0,0,0,0.4);
  --radius:    8px;
  --radius-sm: 4px;
  --transition: all 0.2s ease;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
html { font-size: 16px; scroll-behavior: smooth; }
body {
  background-color: var(--bg-primary);
  color: var(--text-primary);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
               Ubuntu, Cantarell, sans-serif;
  line-height: 1.6;
  min-height: 100vh;
}
a { color: var(--accent); text-decoration: none; transition: var(--transition); }
a:hover { color: var(--accent-hover); text-decoration: underline; }
h1,h2,h3,h4,h5,h6 { color: var(--text-primary); font-weight: 600;
  line-height: 1.3; margin-bottom: 0.75em; }
p { margin-bottom: 1em; color: var(--text-secondary); }
img { max-width: 100%; height: auto; border-radius: var(--radius-sm); }

/* ── Layout ── */
.container { max-width: 1200px; margin: 0 auto; padding: 0 20px; }
.main-content { padding: 2rem 0; }

/* ── Navigation ── */
.navbar {
  background-color: var(--bg-secondary);
  border-bottom: 1px solid var(--border);
  position: sticky; top: 0; z-index: 1000;
  box-shadow: var(--shadow);
}
.navbar .container {
  display: flex; align-items: center; justify-content: space-between;
  height: 60px;
}
.navbar-brand {
  font-size: 1.4rem; font-weight: 700;
  color: var(--accent) !important; text-decoration: none !important;
}
.navbar-nav { display: flex; list-style: none; gap: 8px; flex-wrap: wrap; }
.navbar-nav a {
  padding: 6px 14px; border-radius: var(--radius-sm);
  font-size: 0.9rem; transition: var(--transition);
}
.navbar-nav a:hover { background-color: var(--bg-hover); text-decoration: none; }

/* ── Cards ── */
.card {
  background-color: var(--bg-card);
  border: 1px solid var(--border); border-radius: var(--radius);
  padding: 1.5rem; transition: var(--transition);
  box-shadow: var(--shadow-card);
}
.card:hover {
  border-color: var(--border-light);
  transform: translateY(-2px); box-shadow: var(--shadow);
}

/* ── Product Grid ── */
.product-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
  gap: 1.5rem; padding: 1rem 0;
}
.product-card {
  background-color: var(--bg-card);
  border: 1px solid var(--border); border-radius: var(--radius);
  overflow: hidden; transition: var(--transition);
  box-shadow: var(--shadow-card);
  display: flex; flex-direction: column;
}
.product-card:hover {
  border-color: var(--accent-dark);
  transform: translateY(-3px); box-shadow: var(--shadow);
}
.product-card .product-image {
  width: 100%; aspect-ratio: 4/3; object-fit: cover;
  background-color: var(--bg-secondary);
}
.product-card .product-body {
  padding: 1rem; flex: 1;
  display: flex; flex-direction: column;
}
.product-card .product-title { font-size: 1rem; font-weight: 600;
  color: var(--text-primary); margin-bottom: 0.5rem; }
.product-card .product-price { font-size: 1.2rem; font-weight: 700;
  color: var(--accent); margin-bottom: 0.5rem; }
.product-card .product-desc { font-size: 0.85rem; color: var(--text-secondary);
  flex: 1; margin-bottom: 1rem; }
.product-card .btn-buy {
  display: block; text-align: center;
  background-color: var(--accent); color: #fff !important;
  padding: 10px 16px; border-radius: var(--radius-sm);
  font-weight: 600; font-size: 0.9rem; transition: var(--transition);
  border: none; cursor: pointer; text-decoration: none !important;
}
.product-card .btn-buy:hover {
  background-color: var(--accent-hover); transform: translateY(-1px);
}

/* ── Buttons ── */
.btn {
  display: inline-block; padding: 10px 20px;
  border-radius: var(--radius-sm); font-weight: 600;
  font-size: 0.9rem; cursor: pointer; border: none;
  transition: var(--transition); text-decoration: none;
}
.btn-primary { background-color: var(--accent); color: #fff; }
.btn-primary:hover { background-color: var(--accent-hover);
  color: #fff; text-decoration: none; }
.btn-secondary {
  background-color: var(--bg-secondary);
  color: var(--text-primary); border: 1px solid var(--border);
}
.btn-secondary:hover { background-color: var(--bg-hover); text-decoration: none; }

/* ── Forms ── */
.form-group { margin-bottom: 1.2rem; }
label { display: block; margin-bottom: 6px; font-size: 0.9rem;
  color: var(--text-secondary); font-weight: 500; }
input[type="text"],
input[type="number"],
input[type="email"],
select,
textarea {
  width: 100%; background-color: var(--bg-secondary);
  border: 1px solid var(--border); color: var(--text-primary);
  padding: 10px 14px; border-radius: var(--radius-sm);
  font-size: 0.95rem; transition: var(--transition);
  outline: none; appearance: none;
}
input:focus, select:focus, textarea:focus {
  border-color: var(--accent);
  box-shadow: 0 0 0 2px rgba(255,107,53,0.15);
}
select {
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%23a0a0a0' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e");
  background-position: right 10px center;
  background-repeat: no-repeat; background-size: 16px;
  padding-right: 36px; cursor: pointer;
}

/* ── Tables ── */
table { width: 100%; border-collapse: collapse; margin-bottom: 1.5rem; }
th, td {
  padding: 12px 16px; text-align: left;
  border-bottom: 1px solid var(--border); font-size: 0.9rem;
}
th {
  background-color: var(--bg-secondary); color: var(--text-secondary);
  font-weight: 600; text-transform: uppercase;
  font-size: 0.75rem; letter-spacing: 0.05em;
}
tr:hover td { background-color: var(--bg-hover); }

/* ── Categories ── */
.category-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 1rem; margin: 1.5rem 0;
}
.category-card {
  background-color: var(--bg-card); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 1.2rem;
  text-align: center; transition: var(--transition);
  display: block; text-decoration: none !important;
}
.category-card:hover { border-color: var(--accent); transform: translateY(-2px); }
.category-card h3 { font-size: 1rem; margin-bottom: 0.25rem; }
.category-card .count { font-size: 0.8rem; color: var(--text-muted); }

/* ── Sorting Controls ── */
.sort-controls {
  display: flex; align-items: center; gap: 1rem;
  margin-bottom: 1.5rem; flex-wrap: wrap;
  padding: 1rem; background-color: var(--bg-secondary);
  border-radius: var(--radius); border: 1px solid var(--border);
}
.sort-controls label { margin: 0; white-space: nowrap; }
.sort-controls select { width: auto; flex: 1; min-width: 160px; }

/* ── Pricing Controls ── */
.pricing-controls {
  background-color: var(--bg-secondary);
  border: 1px solid var(--border); border-radius: var(--radius);
  padding: 1.2rem; margin-bottom: 1.5rem;
}
.pricing-controls h3 {
  font-size: 0.9rem; text-transform: uppercase;
  letter-spacing: 0.05em; color: var(--text-muted); margin-bottom: 1rem;
}

/* ── Footer ── */
footer {
  background-color: var(--bg-secondary);
  border-top: 1px solid var(--border); padding: 2rem 0; margin-top: 4rem;
}
footer .footer-content {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 2rem;
}
footer h3 {
  font-size: 0.85rem; text-transform: uppercase;
  letter-spacing: 0.1em; color: var(--text-muted); margin-bottom: 1rem;
}
footer p, footer a { font-size: 0.875rem; color: var(--text-secondary); }
footer a:hover { color: var(--accent); }
.footer-bottom {
  margin-top: 2rem; padding-top: 1rem;
  border-top: 1px solid var(--border);
  text-align: center; font-size: 0.8rem; color: var(--text-muted);
}

/* ── Page Hero ── */
.page-hero {
  padding: 3rem 0 2rem; border-bottom: 1px solid var(--border);
  margin-bottom: 2rem;
}
.page-hero h1 { font-size: 2rem; margin-bottom: 0.5rem; }
.page-hero p { font-size: 1rem; color: var(--text-secondary); }

/* ── Payment Page ── */
.payment-container { max-width: 760px; margin: 0 auto; }
.payment-step {
  background-color: var(--bg-card); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 1.5rem; margin-bottom: 1.5rem;
}
.payment-step h2 {
  font-size: 1rem; text-transform: uppercase;
  letter-spacing: 0.05em; color: var(--text-muted); margin-bottom: 1.2rem;
}
.wallet-address-box {
  background-color: var(--bg-primary); border: 1px solid var(--border);
  border-radius: var(--radius-sm); padding: 12px;
  font-family: monospace; font-size: 0.8rem;
  word-break: break-all; color: var(--text-secondary); position: relative;
}
.copy-btn {
  position: absolute; right: 8px; top: 8px;
  background: var(--accent); color: #fff; border: none;
  border-radius: var(--radius-sm); padding: 4px 10px;
  font-size: 0.75rem; cursor: pointer;
}
.price-display {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  gap: 1rem; margin: 1rem 0;
}
.price-item {
  background-color: var(--bg-secondary); border-radius: var(--radius-sm);
  padding: 1rem; text-align: center;
}
.price-item .currency {
  font-size: 0.75rem; color: var(--text-muted);
  text-transform: uppercase; letter-spacing: 0.05em;
}
.price-item .amount {
  font-size: 1.5rem; font-weight: 700; color: var(--accent); margin: 4px 0;
}
.price-item .usd-equiv { font-size: 0.8rem; color: var(--text-secondary); }
.status-box {
  display: flex; align-items: center; gap: 1rem; padding: 1rem;
  background-color: var(--bg-secondary); border-radius: var(--radius);
  border-left: 3px solid var(--warning);
}
.status-indicator {
  width: 12px; height: 12px; border-radius: 50%;
  background-color: var(--warning);
  animation: pulse 2s infinite; flex-shrink: 0;
}
@keyframes pulse {
  0%, 100% { opacity: 1; }
  50%       { opacity: 0.4; }
}

/* ── Payment Products Grid ── */
.products-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
  gap: 1.5rem; padding: 1rem 0;
}
.products-grid .product-card .qty-row {
  display: flex; align-items: center; gap: 0.5rem; margin-bottom: 0.75rem;
}
.products-grid .product-card .qty-row label {
  font-size: 0.85rem; margin: 0; white-space: nowrap; flex-shrink: 0;
}
.products-grid .product-card .qty-row input {
  width: 70px; padding: 6px 10px; font-size: 0.9rem;
}
.products-grid .product-card .subtotal {
  font-size: 0.9rem; color: var(--text-secondary); margin-bottom: 0.75rem;
}
.checkout-breakdown {
  background: var(--bg-secondary); border-radius: var(--radius-sm);
  padding: 1rem; margin: 1rem 0;
}
.checkout-breakdown .line {
  display: flex; justify-content: space-between;
  padding: 4px 0; font-size: 0.9rem; color: var(--text-secondary);
  border-bottom: 1px solid var(--border);
}
.checkout-breakdown .line:last-child { border-bottom: none; }
.checkout-breakdown .line.total {
  font-weight: 700; font-size: 1.1rem;
  color: var(--accent); padding-top: 8px;
}
.btn-back {
  display: inline-block; margin-bottom: 1.5rem;
  padding: 8px 16px; border-radius: var(--radius-sm);
  background: var(--bg-secondary); color: var(--text-primary);
  border: 1px solid var(--border); cursor: pointer;
  font-size: 0.9rem; transition: var(--transition);
}
.btn-back:hover { background: var(--bg-hover); text-decoration: none; }

/* ── Responsive ── */
@media (max-width: 768px) {
  .navbar .container {
    flex-wrap: wrap; height: auto; padding: 10px 20px; gap: 8px;
  }
  .navbar-nav { width: 100%; }
  .product-grid, .products-grid {
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 1rem;
  }
  .page-hero h1 { font-size: 1.5rem; }
  .sort-controls { flex-direction: column; align-items: stretch; }
  .sort-controls select { width: 100%; }
}
@media (max-width: 480px) {
  .product-grid, .products-grid { grid-template-columns: 1fr; }
  .category-grid { grid-template-columns: repeat(2, 1fr); }
}
"""

# ---------------------------------------------------------------------------
# SORTING / PRICING JAVASCRIPT
# ---------------------------------------------------------------------------

MAIN_JS = """\
/* main.js — generated by website_updater.py */
/* Client-side sorting, continent pricing, and shipping selectors */

/* ── Product Sorting ── */
function sortProducts(criterion) {
  var grid = document.getElementById('product-grid');
  if (!grid) return;
  var cards = Array.from(grid.querySelectorAll('[data-price]'));
  cards.sort(function (a, b) {
    switch (criterion) {
      case 'price-asc':  return parseFloat(a.dataset.price||0) - parseFloat(b.dataset.price||0);
      case 'price-desc': return parseFloat(b.dataset.price||0) - parseFloat(a.dataset.price||0);
      case 'name-asc':   return (a.dataset.name||'').localeCompare(b.dataset.name||'');
      case 'name-desc':  return (b.dataset.name||'').localeCompare(a.dataset.name||'');
      case 'qty-asc':    return parseFloat(a.dataset.qty||0) - parseFloat(b.dataset.qty||0);
      case 'qty-desc':   return parseFloat(b.dataset.qty||0) - parseFloat(a.dataset.qty||0);
      default:           return 0;
    }
  });
  cards.forEach(function (c) { grid.appendChild(c); });
}

/* ── Pricing Helpers ── */
var CONTINENT_MULTIPLIERS = {
  north_america: 1.0, europe: 1.2, south_america: 1.5,
  asia: 1.8, africa: 2.0, oceania: 1.6, antarctica: 2.0
};
var SHIPPING_RATES = {
  domestic_standard: 5.00, domestic_express: 10.00,
  international_standard: 15.00, international_priority: 25.00,
  international_express: 40.00
};

function updatePricing() {
  var cSel = document.getElementById('continent-select');
  var sSel = document.getElementById('shipping-select');
  var multiplier = cSel ? (CONTINENT_MULTIPLIERS[cSel.value] || 1.0) : 1.0;
  var shippingCost = sSel ? (SHIPPING_RATES[sSel.value] || 0) : 0;

  document.querySelectorAll('[data-base-price]').forEach(function (el) {
    var base = parseFloat(el.dataset.basePrice || 0);
    el.textContent = '$' + ((base * multiplier) + shippingCost).toFixed(2);
  });
  updateTotal();
}

function updateTotal() {
  var cSel  = document.getElementById('continent-select');
  var sSel  = document.getElementById('shipping-select');
  var qtyEl = document.getElementById('qty');
  var bpEl  = document.querySelector('[data-item-base-price]');
  if (!bpEl) return;

  var base = parseFloat(bpEl.dataset.itemBasePrice || 0);
  var qty  = parseInt(qtyEl ? qtyEl.value : 1, 10) || 1;
  var multiplier    = cSel ? (CONTINENT_MULTIPLIERS[cSel.value] || 1.0) : 1.0;
  var shippingCost  = sSel ? (SHIPPING_RATES[sSel.value] || 0) : 0;
  var total = (base * multiplier * qty) + shippingCost;

  var totalEl = document.getElementById('order-total');
  if (totalEl) totalEl.textContent = '$' + total.toFixed(2);

  var hiddenInput = document.getElementById('total-input');
  if (hiddenInput) hiddenInput.value = total.toFixed(2);
}

document.addEventListener('DOMContentLoaded', function () {
  var cSel = document.getElementById('continent-select');
  var sSel = document.getElementById('shipping-select');
  var qty  = document.getElementById('qty');
  var sort = document.getElementById('sort-select');

  if (cSel) cSel.addEventListener('change', updatePricing);
  if (sSel) sSel.addEventListener('change', updatePricing);
  if (qty)  qty.addEventListener('input', updateTotal);
  if (sort) sort.addEventListener('change', function () { sortProducts(this.value); });
});
"""

# ---------------------------------------------------------------------------
# LOGGER
# ---------------------------------------------------------------------------

class Logger:
    """Simple logger that writes to console and accumulates entries for a log file."""

    def __init__(self, log_file, dry_run=False):
        self.log_file = log_file
        self.dry_run = dry_run
        self.entries = []

    def log(self, message, level="INFO"):
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        prefix = "[DRY-RUN] " if self.dry_run else ""
        entry = "[{ts}] [{lvl}] {pfx}{msg}".format(
            ts=timestamp, lvl=level, pfx=prefix, msg=message
        )
        self.entries.append(entry)
        print(entry)

    def save(self):
        if not self.dry_run:
            with open(self.log_file, "w", encoding="utf-8") as fh:
                fh.write("\n".join(self.entries))
                fh.write("\n")


# ---------------------------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------------------------

def load_config(config_path, logger):
    """Load and merge user config with defaults."""
    config = copy.deepcopy(DEFAULT_CONFIG)
    if os.path.exists(config_path):
        try:
            with open(config_path, "r", encoding="utf-8") as fh:
                user_config = json.load(fh)
            for key, value in user_config.items():
                if isinstance(value, dict) and isinstance(config.get(key), dict):
                    config[key].update(value)
                else:
                    config[key] = value
            logger.log("Loaded config from: {}".format(config_path))
        except (ValueError, IOError) as exc:
            logger.log("Failed to parse config.json: {}".format(exc), "WARNING")
    else:
        logger.log("Config not found at {}, using defaults".format(config_path), "WARNING")

    # Warn if the placeholder wallet address has not been replaced
    wallet = config.get("monero_wallet_address", "")
    if not wallet or wallet.upper().startswith("YOUR_") or "ADDRESS_HERE" in wallet.upper():
        logger.log(
            "monero_wallet_address is still the placeholder value. "
            "Edit config.json with your real XMR address before going live — "
            "otherwise payments will be unrecoverable.",
            "WARNING",
        )

    return config


def load_keywords(keywords_file, logger):
    """Load keywords from a text file (one per line)."""
    keywords = []
    if os.path.exists(keywords_file):
        try:
            with open(keywords_file, "r", encoding="utf-8") as fh:
                keywords = [line.strip() for line in fh if line.strip()]
            logger.log("Loaded {} keywords from {}".format(len(keywords), keywords_file))
        except IOError as exc:
            logger.log("Failed to load keywords: {}".format(exc), "WARNING")
    else:
        logger.log("Keywords file not found: {}".format(keywords_file), "WARNING")
    return keywords


# ---------------------------------------------------------------------------
# BACKUP
# ---------------------------------------------------------------------------

def create_backup(website_root, logger, dry_run=False):
    """Create a full backup of the website directory."""
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    parent = os.path.dirname(os.path.abspath(website_root))
    backup_dir = os.path.join(parent, "website_backup_{}".format(timestamp))
    if dry_run:
        logger.log("[DRY-RUN] Would create backup at: {}".format(backup_dir))
        return backup_dir
    logger.log("Creating backup at: {}".format(backup_dir))
    shutil.copytree(website_root, backup_dir)
    logger.log("Backup complete: {}".format(backup_dir))
    return backup_dir


# ---------------------------------------------------------------------------
# FILE DISCOVERY
# ---------------------------------------------------------------------------

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".svg", ".webp", ".ico", ".bmp"}


def discover_files(root):
    """Walk the website directory and classify files."""
    result = {"html": [], "php": [], "css": [], "js": [], "images": [], "all": []}
    for dirpath, dirnames, filenames in os.walk(root):
        # Skip backup directories in-place
        dirnames[:] = [
            d for d in dirnames
            if not d.startswith("website_backup_") and d not in {".git"}
        ]
        for filename in filenames:
            filepath = os.path.join(dirpath, filename)
            ext = os.path.splitext(filename)[1].lower()
            result["all"].append(filepath)
            if ext == ".html":
                result["html"].append(filepath)
            elif ext == ".php":
                result["php"].append(filepath)
            elif ext == ".css":
                result["css"].append(filepath)
            elif ext == ".js":
                result["js"].append(filepath)
            elif ext in IMAGE_EXTS:
                result["images"].append(filepath)
    return result


# ---------------------------------------------------------------------------
# FILE I/O HELPERS
# ---------------------------------------------------------------------------

def read_file_safe(filepath):
    """Read a file with encoding fallback."""
    for encoding in ("utf-8", "latin-1", "cp1252"):
        try:
            with open(filepath, "r", encoding=encoding, errors="replace") as fh:
                return fh.read()
        except IOError:
            pass
    return ""


def write_file_safe(filepath, content, dry_run=False):
    """Write content to a file (no-op in dry-run mode)."""
    if dry_run:
        return True
    try:
        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as fh:
            fh.write(content)
        return True
    except IOError:
        return False


# ---------------------------------------------------------------------------
# LINK CHECKER / FIXER
# ---------------------------------------------------------------------------

class _LinkExtractor(html.parser.HTMLParser):
    """Extracts href/src/action attribute values from HTML."""

    def __init__(self):
        super(_LinkExtractor, self).__init__()
        self.links = []  # list of (attr_name, value, tag)

    def handle_starttag(self, tag, attrs):
        attrs_dict = dict(attrs)
        for attr in ("href", "src", "action"):
            val = attrs_dict.get(attr, "")
            if val:
                self.links.append((attr, val, tag))


def _is_external(href):
    parsed = urlparse(href)
    return bool(parsed.scheme) and parsed.scheme not in ("", "file")


def _resolve_link(base_file, href, root):
    """Resolve a relative href to an absolute filesystem path."""
    if _is_external(href):
        return None
    href_clean = href.split("?")[0].split("#")[0]
    if not href_clean:
        return None
    base_dir = os.path.dirname(base_file)
    if href_clean.startswith("/"):
        return os.path.normpath(os.path.join(root, href_clean.lstrip("/")))
    return os.path.normpath(os.path.join(base_dir, href_clean))


def build_file_index(root, files):
    """Build filename → [full_path, ...] index for quick lookup."""
    index = collections.defaultdict(list)
    for f in files["all"]:
        index[os.path.basename(f).lower()].append(f)
    return index


def check_and_fix_links(filepath, root, file_index, logger, dry_run=False):
    """Check and fix broken internal links. Returns count of fixes."""
    content = read_file_safe(filepath)
    if not content:
        return 0

    parser = _LinkExtractor()
    try:
        parser.feed(content)
    except Exception:
        pass

    fixes = 0
    new_content = content

    for attr, href, _tag in parser.links:
        if _is_external(href):
            continue
        href_clean = href.split("?")[0].split("#")[0]
        if not href_clean or href_clean.startswith("#"):
            continue

        resolved = _resolve_link(filepath, href_clean, root)
        if resolved and os.path.exists(resolved):
            continue  # link is valid

        # Try to find the file elsewhere in the directory tree
        basename = os.path.basename(href_clean).lower()
        candidates = file_index.get(basename, [])

        if candidates:
            best = candidates[0]
            rel_path = os.path.relpath(best, os.path.dirname(filepath)).replace(os.sep, "/")
            logger.log(
                "Fixed broken link in {}: {} -> {}".format(
                    os.path.relpath(filepath, root), href, rel_path
                )
            )
            for q in ('"', "'"):
                old = "{}={}{}{}".format(attr, q, re.escape(href), q)
                new = "{}={}{}{}".format(attr, q, rel_path, q)
                if re.search("{}={}{}{}".format(attr, q, re.escape(href), q), new_content):
                    new_content = re.sub(
                        "{}={}{}{}".format(attr, q, re.escape(href), q),
                        "{}={}{}{}".format(attr, q, rel_path, q),
                        new_content, count=1
                    )
                    fixes += 1
                    break
        else:
            logger.log(
                "Broken link (unresolvable) in {}: {} (file not found anywhere)".format(
                    os.path.relpath(filepath, root), href
                ),
                "WARNING",
            )

    if fixes > 0:
        write_file_safe(filepath, new_content, dry_run)
    return fixes


# ---------------------------------------------------------------------------
# DIRECTORY STRUCTURE
# ---------------------------------------------------------------------------

def ensure_directory_structure(root, logger, dry_run=False):
    """Create standard subdirectories if they don't already exist."""
    for d in ("products", "css", "js", "images"):
        full = os.path.join(root, d)
        if not os.path.exists(full):
            logger.log("Creating directory: {}/".format(d))
            if not dry_run:
                os.makedirs(full, exist_ok=True)


# ---------------------------------------------------------------------------
# SEO META TAGS
# ---------------------------------------------------------------------------

def _extract_text(html_content):
    """Strip HTML tags and return plain text."""
    content = re.sub(r"<script[^>]*>.*?</script\s*>", "", html_content,
                     flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r"<style[^>]*>.*?</style\s*>", "", content,
                     flags=re.DOTALL | re.IGNORECASE)
    content = re.sub(r"<[^>]+>", " ", content)
    content = html.unescape(content)
    return re.sub(r"\s+", " ", content).strip()


def _generate_description(text, max_len=160):
    """Generate a short meta description from plain text."""
    if not text:
        return "Privacy-focused online store with secure anonymous payments via Monero."
    desc = ""
    for sentence in re.split(r"[.!?]+", text):
        sentence = sentence.strip()
        if len(sentence) < 10:
            continue
        if len(desc) + len(sentence) + 2 <= max_len:
            desc = (desc + ". " + sentence).strip(". ")
        else:
            break
    if not desc:
        desc = text[:max_len].rsplit(" ", 1)[0]
    return (desc[:max_len] if desc else "Privacy-focused online store.").strip()


def _extract_title(html_content):
    m = re.search(r"<title[^>]*>(.*?)</title>", html_content,
                  re.IGNORECASE | re.DOTALL)
    return html.unescape(m.group(1).strip()) if m else ""


def inject_seo_tags(filepath, keywords, site_url, logger, dry_run=False):
    """Inject / update SEO meta tags in an HTML/PHP file."""
    content = read_file_safe(filepath)
    if not content:
        return False

    text = _extract_text(content)
    title = _extract_title(content) or (
        os.path.splitext(os.path.basename(filepath))[0]
        .replace("-", " ").replace("_", " ").title()
    )
    description = _generate_description(text)
    kw_str = ", ".join(keywords[:25]) if keywords else ""

    # Build replacement block
    tags = []
    tags.append('<meta charset="UTF-8">')
    tags.append('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
    tags.append('<meta name="robots" content="index, follow">')
    if kw_str:
        tags.append('<meta name="keywords" content="{}">'.format(html.escape(kw_str)))
    tags.append('<meta name="description" content="{}">'.format(html.escape(description)))
    tags.append('<meta property="og:title" content="{}">'.format(html.escape(title)))
    tags.append('<meta property="og:description" content="{}">'.format(html.escape(description)))
    tags.append('<meta property="og:type" content="website">')
    meta_block = "\n    ".join(tags)

    new_content = content
    # Remove pre-existing duplicates
    for pattern in (
        r'\s*<meta\s+charset=["\'][^"\']*["\'][^>]*/?>',
        r'\s*<meta\s+name=["\']keywords["\'][^>]*/?>',
        r'\s*<meta\s+name=["\']description["\'][^>]*/?>',
        r'\s*<meta\s+property=["\']og:[^"\']*["\'][^>]*/?>',
        r'\s*<meta\s+name=["\']robots["\'][^>]*/?>',
        r'\s*<meta\s+name=["\']viewport["\'][^>]*/?>',
    ):
        new_content = re.sub(pattern, "", new_content, flags=re.IGNORECASE)

    # Insert after opening <head> tag
    if re.search(r"<head[^>]*>", new_content, re.IGNORECASE):
        new_content = re.sub(
            r"(<head[^>]*>)",
            r"\1\n    " + meta_block,
            new_content, count=1, flags=re.IGNORECASE,
        )
    elif re.search(r"</head>", new_content, re.IGNORECASE):
        new_content = re.sub(
            r"(</head>)",
            "    " + meta_block + r"\n\1",
            new_content, count=1, flags=re.IGNORECASE,
        )
    else:
        new_content = "<head>\n    {}\n</head>\n".format(meta_block) + new_content

    if new_content != content:
        logger.log("Updated SEO meta tags: {}".format(os.path.relpath(filepath)))
        write_file_safe(filepath, new_content, dry_run)
        return True
    return False


# ---------------------------------------------------------------------------
# SITEMAP & ROBOTS
# ---------------------------------------------------------------------------

def generate_sitemap(root, files, site_url, logger, dry_run=False):
    """Generate sitemap.xml from discovered HTML/PHP pages."""
    base = site_url.rstrip("/")
    now = datetime.datetime.now().strftime("%Y-%m-%d")
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for filepath in files["html"] + files["php"]:
        rel = os.path.relpath(filepath, root).replace(os.sep, "/")
        if rel in ("index.html", "index.php"):
            priority, changefreq = "1.0", "daily"
        elif "product" in rel.lower():
            priority, changefreq = "0.8", "weekly"
        elif "categor" in rel.lower():
            priority, changefreq = "0.7", "weekly"
        else:
            priority, changefreq = "0.5", "monthly"
        lines += [
            "  <url>",
            "    <loc>{}/{}</loc>".format(base, html.escape(rel)),
            "    <lastmod>{}</lastmod>".format(now),
            "    <changefreq>{}</changefreq>".format(changefreq),
            "    <priority>{}</priority>".format(priority),
            "  </url>",
        ]
    lines.append("</urlset>")
    write_file_safe(os.path.join(root, "sitemap.xml"), "\n".join(lines), dry_run)
    logger.log("Generated sitemap.xml ({} URLs)".format(len(files["html"]) + len(files["php"])))


def generate_robots(root, site_url, logger, dry_run=False):
    """Generate an optimized robots.txt."""
    base = site_url.rstrip("/")
    content = (
        "User-agent: *\n"
        "Allow: /\n"
        "\n"
        "# Block non-essential directories\n"
        "Disallow: /images/thumbs/\n"
        "Disallow: /images/tmp/\n"
        "Disallow: /.git/\n"
        "Disallow: /website_backup*/\n"
        "Disallow: /tmp/\n"
        "Disallow: /cache/\n"
        "Disallow: /logs/\n"
        "\n"
        "# Sitemap\n"
        "Sitemap: {}/sitemap.xml\n".format(base)
    )
    write_file_safe(os.path.join(root, "robots.txt"), content, dry_run)
    logger.log("Generated robots.txt")


# ---------------------------------------------------------------------------
# PRODUCT PARSER
# ---------------------------------------------------------------------------

class _ProductParser(html.parser.HTMLParser):
    """Extracts product metadata from an HTML/PHP page."""

    def __init__(self):
        super(_ProductParser, self).__init__()
        self._stack = []
        self._buf = []
        self.title = ""
        self.price = ""
        self.description = ""
        self.images = []
        self.quantity = ""

    def handle_starttag(self, tag, attrs):
        self._stack.append(tag)
        self._buf = []
        attrs_dict = dict(attrs)
        if tag == "img":
            src = attrs_dict.get("src", "")
            if src and not src.startswith("data:"):
                self.images.append(src)

    def handle_endtag(self, tag):
        text = "".join(self._buf).strip()
        if tag == "title" and not self.title:
            self.title = text
        elif tag == "h1" and not self.title:
            self.title = text
        elif tag == "h2" and not self.title:
            self.title = text
        elif tag == "p" and not self.description and len(text) > 20:
            self.description = text
        if self._stack and self._stack[-1] == tag:
            self._stack.pop()
        self._buf = []

    def handle_data(self, data):
        self._buf.append(data)
        if not self.price:
            m = re.search(r"\$\s*(\d+(?:\.\d{1,2})?)", data)
            if m:
                self.price = m.group(1)
        if not self.quantity:
            m = re.search(r"(?:qty|quantity|stock|available)[:\s]+(\d+)", data,
                          re.IGNORECASE)
            if m:
                self.quantity = m.group(1)


_VOID_ELEMENTS = frozenset([
    'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input',
    'link', 'meta', 'param', 'source', 'track', 'wbr',
])
_BLOCK_TAGS = frozenset(['div', 'li', 'article', 'section', 'tr'])
_BLOCK_RE = re.compile(r'product|item|listing|card|goods|merch', re.IGNORECASE)


class FormProductParser(html.parser.HTMLParser):
    """Extracts real products from index.html/index.php by parsing form and
    product-container block structures, with a regex fallback.

    Attributes:
        form_products  -- list of product dicts found in <form> elements
        block_products -- list of product dicts found in block containers
    """

    _NAME_FIELDS = frozenset([
        'item', 'product', 'product_name', 'product-name', 'name',
        'item_name', 'item-name', 'title',
    ])
    _PRICE_FIELDS = frozenset([
        'price', 'cost', 'amount_usd', 'product_price', 'product-price',
        'item_price', 'item-price', 'unit_price',
    ])
    _QTY_FIELDS = frozenset(['qty', 'quantity', 'amount', 'count', 'num'])
    _ID_FIELDS = frozenset(['id', 'product_id', 'product-id', 'item_id', 'item-id', 'pid'])
    _PRICE_RE = re.compile(r'\$\s*(\d+(?:\.\d{1,2})?)')
    _HEADING_TAGS = frozenset(['h1', 'h2', 'h3', 'h4', 'h5', 'h6'])

    def __init__(self):
        super(FormProductParser, self).__init__()
        self.form_products = []
        self.block_products = []

        # Stack of open non-void tags (tag names only) for depth tracking.
        self._tag_stack = []

        # ── Form state ──────────────────────────────────────────────────────
        self._cur_form = None   # dict accumulating the current form's data
        self._cur_select = None  # name attr of the currently-open <select>

        # ── Block state ─────────────────────────────────────────────────────
        # Each entry: {'depth': int, 'data': {name, price, qty, images, description}}
        self._blk_stack = []

        # ── Text collection ─────────────────────────────────────────────────
        # Stack of {'tag': str, 'depth': int, 'buf': list}
        self._txt_stack = []

    # ── Context helpers ──────────────────────────────────────────────────────

    def _in_form(self):
        return self._cur_form is not None

    def _cur_depth(self):
        return len(self._tag_stack)

    def _push_price(self, price):
        if self._cur_form is not None and not self._cur_form['price']:
            self._cur_form['price'] = price
        if self._blk_stack and not self._blk_stack[-1]['data']['price']:
            self._blk_stack[-1]['data']['price'] = price

    def _push_name(self, name):
        if self._cur_form is not None and not self._cur_form['name']:
            self._cur_form['name'] = name
        if self._blk_stack and not self._blk_stack[-1]['data']['name']:
            self._blk_stack[-1]['data']['name'] = name

    def _push_desc(self, desc):
        if self._cur_form is not None and not self._cur_form['description']:
            self._cur_form['description'] = desc
        if self._blk_stack and not self._blk_stack[-1]['data']['description']:
            self._blk_stack[-1]['data']['description'] = desc

    def _push_image(self, src):
        if self._cur_form is not None:
            self._cur_form['images'].append(src)
        for entry in self._blk_stack:
            entry['data']['images'].append(src)

    # ── HTML parser callbacks ────────────────────────────────────────────────

    def handle_starttag(self, tag, attrs):
        tag = tag.lower()
        attrs_d = dict(attrs)

        # Push to tag stack (void elements have no matching end tag)
        if tag not in _VOID_ELEMENTS:
            self._tag_stack.append(tag)
        depth = len(self._tag_stack)

        # ── Form element handling ─────────────────────────────────────────
        if tag == 'form':
            self._cur_form = {
                'name': '', 'price': '', 'qty': '', 'product_id': '',
                'images': [], 'description': '',
            }
            self._cur_select = None

        elif tag == 'input' and self._in_form():
            itype = attrs_d.get('type', 'text').lower()
            iname = attrs_d.get('name', '').lower().strip()
            ival = attrs_d.get('value', '').strip()
            if itype in ('hidden', 'text'):
                if iname in self._NAME_FIELDS and ival and not self._cur_form['name']:
                    self._cur_form['name'] = ival
                elif iname in self._PRICE_FIELDS and ival and not self._cur_form['price']:
                    self._cur_form['price'] = ival
                elif iname in self._QTY_FIELDS and ival and not self._cur_form['qty']:
                    self._cur_form['qty'] = ival
                elif iname in self._ID_FIELDS and ival and not self._cur_form['product_id']:
                    self._cur_form['product_id'] = ival
            elif itype == 'submit' and ival and not self._cur_form['name']:
                self._cur_form['name'] = ival

        elif tag == 'select' and self._in_form():
            self._cur_select = attrs_d.get('name', '').lower().strip()

        elif tag == 'option' and self._in_form() and self._cur_select:
            ival = attrs_d.get('value', '').strip()
            if ival:
                sel = self._cur_select
                if sel in self._PRICE_FIELDS and not self._cur_form['price']:
                    self._cur_form['price'] = ival
                elif sel in self._NAME_FIELDS and not self._cur_form['name']:
                    self._cur_form['name'] = ival

        elif tag == 'img':
            src = attrs_d.get('src', '').strip()
            if src and not src.startswith('data:'):
                self._push_image(src)

        # ── Block container detection ─────────────────────────────────────
        if tag in _BLOCK_TAGS:
            cls = attrs_d.get('class', '') or ''
            bid = attrs_d.get('id', '') or ''
            if _BLOCK_RE.search(cls) or _BLOCK_RE.search(bid):
                self._blk_stack.append({
                    'depth': depth,
                    'data': {
                        'name': '', 'price': '', 'qty': '',
                        'images': [], 'description': '',
                    },
                })

        # ── Open text collector for text-bearing tags ─────────────────────
        if tag in self._HEADING_TAGS or tag == 'p':
            self._txt_stack.append({'tag': tag, 'depth': depth, 'buf': []})

    def handle_endtag(self, tag):
        tag = tag.lower()

        # Current depth before popping
        closing_depth = len(self._tag_stack)

        # ── Collect buffered text if the matching collector is on top ─────
        text = ''
        if self._txt_stack and self._txt_stack[-1]['tag'] == tag:
            text = ''.join(self._txt_stack.pop()['buf']).strip()

        if text:
            if tag in self._HEADING_TAGS:
                self._push_name(text)
            elif tag == 'p':
                m = self._PRICE_RE.search(text)
                if m:
                    self._push_price(m.group(1))
                elif len(text) > 10:
                    self._push_desc(text)

        # ── Finalise form ─────────────────────────────────────────────────
        if tag == 'form' and self._in_form():
            f = self._cur_form
            self._cur_form = None
            self._cur_select = None
            if f['name'] or f['price']:
                self.form_products.append({
                    'name': f['name'] or 'Product',
                    'price': f['price'] or '0',
                    'description': f['description'],
                    'images': list(f['images']),
                    'quantity': f['qty'] or '1',
                    'product_id': f['product_id'],
                    'link': '',
                    'source': 'form',
                })

        # ── Finalise block containers at this depth ───────────────────────
        if tag in _BLOCK_TAGS:
            remaining = []
            for entry in self._blk_stack:
                if entry['depth'] == closing_depth:
                    d = entry['data']
                    if not d['price']:
                        m = self._PRICE_RE.search(d['description'])
                        if m:
                            d['price'] = m.group(1)
                    if d['name'] and d['price']:
                        self.block_products.append({
                            'name': d['name'],
                            'price': d['price'],
                            'description': d['description'],
                            'images': list(d['images']),
                            'quantity': d.get('qty') or '1',
                            'product_id': '',
                            'link': '',
                            'source': 'block',
                        })
                else:
                    remaining.append(entry)
            self._blk_stack = remaining

        # ── Pop from tag stack ────────────────────────────────────────────
        if tag not in _VOID_ELEMENTS:
            if self._tag_stack and self._tag_stack[-1] == tag:
                self._tag_stack.pop()
            else:
                for i in range(len(self._tag_stack) - 1, -1, -1):
                    if self._tag_stack[i] == tag:
                        self._tag_stack.pop(i)
                        break

    def handle_data(self, data):
        # Propagate raw text to every open text collector (handles nested tags)
        for entry in self._txt_stack:
            entry['buf'].append(data)

        # Also scan inline data for prices so spans/tds are covered
        m = self._PRICE_RE.search(data)
        if m:
            self._push_price(m.group(1))


def _fallback_regex_products(content):
    """Regex fallback: scan all lines for $XX.XX patterns and look nearby for names/images."""
    products = []
    price_re = re.compile(r'\$\s*(\d+(?:\.\d{1,2})?)')
    heading_re = re.compile(r'<h[1-6][^>]*>(.*?)</h[1-6]>', re.DOTALL | re.IGNORECASE)
    bold_re = re.compile(r'<(?:b|strong)[^>]*>(.*?)</(?:b|strong)>', re.DOTALL | re.IGNORECASE)
    img_re = re.compile(r'<img[^>]+src\s*=\s*["\']([^"\']*)["\']', re.IGNORECASE)
    tag_re = re.compile(r'<[^>]+>')

    lines = content.splitlines()
    seen = set()
    for i, line in enumerate(lines):
        m = price_re.search(line)
        if not m:
            continue
        price = m.group(1)
        start = max(0, i - 10)
        context = '\n'.join(lines[start:i + 3])

        name = ''
        for hm in heading_re.finditer(context):
            txt = tag_re.sub('', hm.group(1)).strip()
            if txt:
                name = txt
                break
        if not name:
            for bm in bold_re.finditer(context):
                txt = tag_re.sub('', bm.group(1)).strip()
                if txt:
                    name = txt
                    break

        images = [
            im.group(1) for im in img_re.finditer(context)
            if im.group(1) and not im.group(1).startswith('data:')
        ]

        key = (name.lower(), price)
        if key not in seen:
            seen.add(key)
            products.append({
                'name': name or 'Product',
                'price': price,
                'description': '',
                'images': images,
                'quantity': '1',
                'product_id': '',
                'link': '',
                'source': 'regex',
            })
    return products


def extract_products(filepath):
    """Extract products from an index.html / index.php file.

    Priority: form products > block products > regex fallback.
    When both form and block products are found the block products are used
    to enrich the form products with images and descriptions.

    Returns a list of product dicts with keys:
        name, price, description, images, quantity, link, product_id, source
    """
    content = read_file_safe(filepath)
    if not content:
        return []

    parser = FormProductParser()
    try:
        parser.feed(content)
    except Exception:
        pass

    if parser.form_products and parser.block_products:
        products = list(parser.form_products)
        for fp in products:
            for bp in parser.block_products:
                name_match = fp['name'].lower() == bp['name'].lower()
                price_match = fp['price'] and fp['price'] == bp['price']
                # Require both name and price to match to avoid false merges
                if name_match and price_match:
                    if not fp['images']:
                        fp['images'] = list(bp['images'])
                    if not fp['description']:
                        fp['description'] = bp['description']
                    break
                # Fall back: name-only match is sufficient for enrichment
                elif name_match:
                    if not fp['images']:
                        fp['images'] = list(bp['images'])
                    if not fp['description']:
                        fp['description'] = bp['description']
                    break
    elif parser.form_products:
        products = list(parser.form_products)
    elif parser.block_products:
        products = list(parser.block_products)
    else:
        products = _fallback_regex_products(content)

    # Deduplicate by (name.lower(), price)
    seen = set()
    unique = []
    for p in products:
        key = (p['name'].lower(), p['price'])
        if key not in seen:
            seen.add(key)
            p.setdefault('link', '')
            p.setdefault('source', 'unknown')
            p.setdefault('product_id', '')
            p.setdefault('description', '')
            p.setdefault('images', [])
            p.setdefault('quantity', '1')
            unique.append(p)
    return unique


def _infer_category(name, content, filepath):
    """Infer product category from name, content, and file path."""
    text = (name + " " + content + " " + filepath).lower()
    best, best_score = "other", 0
    for cat, kws in CATEGORY_KEYWORDS.items():
        if cat == "other":
            continue
        score = sum(1 for kw in kws if kw in text)
        if score > best_score:
            best_score = score
            best = cat
    return best


def parse_product(filepath):
    """Parse a product file and return a metadata dict."""
    content = read_file_safe(filepath)
    parser = _ProductParser()
    try:
        parser.feed(content)
    except Exception:
        pass

    price = parser.price
    if not price:
        m = re.search(r"\$\s*(\d+(?:\.\d{1,2})?)", content)
        if m:
            price = m.group(1)

    name = parser.title or (
        os.path.splitext(os.path.basename(filepath))[0]
        .replace("-", " ").replace("_", " ").title()
    )
    description = parser.description or _extract_text(content)[:200]

    return {
        "name": name,
        "price": price or "0",
        "description": description,
        "images": parser.images,
        "filepath": filepath,
        "quantity": parser.quantity or "1",
        "category": _infer_category(name, content, filepath),
    }


def is_product_file(filepath, root):
    """Heuristic: is this an individual product page?"""
    rel = os.path.relpath(filepath, root).lower()
    basename = os.path.basename(rel)
    excluded = {
        "index.html", "index.php", "payment.php", "payment.html",
        "contact.html", "contact.php", "about.html", "about.php",
        "sitemap.xml", "robots.txt",
    }
    if basename in excluded:
        return False
    if basename.startswith("category_"):
        return False
    return rel.endswith((".html", ".php"))


# ---------------------------------------------------------------------------
# HTML BUILDING HELPERS
# ---------------------------------------------------------------------------

def _rel_root(root, current_file):
    """Return the relative path prefix from current_file's directory to root."""
    rel = os.path.relpath(root, os.path.dirname(current_file))
    if rel == ".":
        return ""
    return rel.replace(os.sep, "/") + "/"


def build_navbar(root, current_file, categories, config):
    rr = _rel_root(root, current_file)
    cat_links = "".join(
        '<li><a href="{rr}category_{cat}.html">{label}</a></li>'.format(
            rr=rr, cat=cat, label=cat.replace("_", " ").title()
        )
        for cat in list(categories)[:6]
    )
    return (
        '<nav class="navbar">\n'
        '  <div class="container">\n'
        '    <a class="navbar-brand" href="{rr}index.html">\U0001f6d2 Shop</a>\n'
        '    <ul class="navbar-nav">\n'
        '      <li><a href="{rr}index.html">Home</a></li>\n'
        '      <li><a href="{rr}products/">Products</a></li>\n'
        "      {cat_links}\n"
        "    </ul>\n"
        "  </div>\n"
        "</nav>"
    ).format(rr=rr, cat_links=cat_links)


def build_footer(config):
    wickr = html.escape(config.get("contact_wickr", ""))
    email = html.escape(config.get("contact_email", ""))
    wickr_html = (
        "<p>Wickr: <strong>{}</strong></p>".format(wickr) if wickr else ""
    )
    email_html = (
        '<p>Email: <a href="mailto:{e}">{e}</a></p>'.format(e=email) if email else ""
    )
    year = datetime.datetime.now().year
    return (
        "<footer>\n"
        "  <div class=\"container\">\n"
        "    <div class=\"footer-content\">\n"
        "      <div><h3>Privacy</h3>"
        "<p>All orders processed anonymously. No account required.</p></div>\n"
        "      <div><h3>Payment</h3>"
        "<p>We accept Monero (XMR) and Bitcoin (BTC) for maximum privacy.</p></div>\n"
        "      <div><h3>Contact</h3>{wickr}{email}</div>\n"
        "    </div>\n"
        "    <div class=\"footer-bottom\">"
        "<p>&copy; {year} &mdash; Secured with Monero.</p></div>\n"
        "  </div>\n"
        "</footer>"
    ).format(wickr=wickr_html, email=email_html, year=year)


def build_page_shell(title, body, root, current_file, categories, config, extra_head=""):
    rr = _rel_root(root, current_file)
    css_path = rr + "css/style.css"
    js_path = rr + "js/main.js"
    navbar = build_navbar(root, current_file, categories, config)
    footer = build_footer(config)
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '  <meta charset="UTF-8">\n'
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        "  <title>{title}</title>\n"
        '  <link rel="stylesheet" href="{css}">\n'
        "  {extra}\n"
        "</head>\n"
        "<body>\n"
        "{navbar}\n"
        '<main class="container main-content">\n'
        "{body}\n"
        "</main>\n"
        "{footer}\n"
        '<script src="{js}"></script>\n'
        "</body>\n"
        "</html>"
    ).format(
        title=html.escape(title),
        css=css_path,
        js=js_path,
        extra=extra_head,
        navbar=navbar,
        body=body,
        footer=footer,
    )


# ---------------------------------------------------------------------------
# CONTINENT / SHIPPING CONTROLS
# ---------------------------------------------------------------------------

def _continent_options(config):
    opts = ""
    for continent, mult in config.get("continent_pricing", {}).items():
        label = continent.replace("_", " ").title()
        opts += '<option value="{}">{} (&times;{})</option>\n'.format(
            continent, label, mult
        )
    return opts


def _shipping_options(config):
    labels = {
        "domestic_standard": "Domestic Standard",
        "domestic_express": "Domestic Express",
        "international_standard": "International Standard",
        "international_priority": "International Priority",
        "international_express": "International Express",
    }
    opts = ""
    for method, cost in config.get("shipping_methods", {}).items():
        label = labels.get(method, method.replace("_", " ").title())
        opts += '<option value="{}">{} (+${:.2f})</option>\n'.format(
            method, label, cost
        )
    return opts


def build_pricing_controls(config):
    return (
        '<div class="pricing-controls">\n'
        "  <h3>Shipping &amp; Region</h3>\n"
        '  <div class="form-group">\n'
        '    <label for="continent-select">Your Region</label>\n'
        '    <select id="continent-select" name="continent">\n'
        "      {co}"
        "    </select>\n"
        "  </div>\n"
        '  <div class="form-group">\n'
        '    <label for="shipping-select">Shipping Method</label>\n'
        '    <select id="shipping-select" name="shipping">\n'
        "      {so}"
        "    </select>\n"
        "  </div>\n"
        "</div>"
    ).format(co=_continent_options(config), so=_shipping_options(config))


# ---------------------------------------------------------------------------
# PAYMENT PAGE
# ---------------------------------------------------------------------------

def generate_payment_page(root, config, categories, logger, dry_run=False,
                          products=None):
    """Generate a modern client-side payment.php page with product cards.

    If *products* is supplied each product gets its own card in a CSS grid.
    Clicking "Order Now" on a card switches to the single-product checkout
    panel.  Navigating to payment.php?item=X&price=Y&amount=Z skips straight
    to checkout (backward-compatible URL-param behaviour is preserved).
    """
    wallet = config.get("monero_wallet_address", "")
    wickr = html.escape(config.get("contact_wickr", ""))
    email = html.escape(config.get("contact_email", ""))
    continent_js = json.dumps(config.get("continent_pricing", {}))
    shipping_js = json.dumps(config.get("shipping_methods", {}))
    qr_url = "https://api.qrserver.com/v1/create-qr-code/?size=200x200&data={}".format(
        html.escape(wallet)
    )

    navbar = build_navbar(root, os.path.join(root, "payment.php"), categories, config)
    footer = build_footer(config)

    wickr_card = (
        '<div class="card" style="flex:1;min-width:180px">'
        "<strong>Wickr</strong><br>"
        '<span style="color:var(--accent)">{}</span>'
        "</div>".format(wickr)
        if wickr else ""
    )
    email_card = (
        '<div class="card" style="flex:1;min-width:180px">'
        "<strong>Email</strong><br>"
        '<a href="mailto:{e}">{e}</a>'
        "</div>".format(e=email)
        if email else ""
    )

    # ── Build product cards for the grid ────────────────────────────────────
    product_cards_html = ""
    products_json = "[]"
    has_products = bool(products)

    if has_products:
        card_parts = []
        prod_data = []
        for idx, p in enumerate(products):
            pname = html.escape(p.get("name", "Product"))
            pprice = p.get("price", "0")
            pdesc = html.escape(p.get("description", "")[:100])
            pqty = p.get("quantity", "1")
            pimg = p.get("images", [])
            if pimg:
                img_html = (
                    '<img class="product-image" src="{}" alt="{}" loading="lazy">'.format(
                        html.escape(pimg[0]), pname
                    )
                )
            else:
                img_html = (
                    '<div class="product-image" style="display:flex;align-items:center;'
                    'justify-content:center;color:var(--text-muted);font-size:3rem;">'
                    '&#128230;</div>'
                )
            card_parts.append((
                '<div class="product-card" data-price="{price}" data-name="{name}">\n'
                "  {img}\n"
                '  <div class="product-body">\n'
                '    <div class="product-title">{name}</div>\n'
                '    <div class="product-price" data-base-price="{price}">${price}</div>\n'
                '    <div class="product-desc">{desc}</div>\n'
                '    <div class="qty-row">\n'
                '      <label for="qty-{idx}">Qty:</label>\n'
                '      <input type="number" id="qty-{idx}" value="{default_qty}"'
                ' min="1" max="999" onchange="recalcProduct({idx})">\n'
                "    </div>\n"
                '    <div class="subtotal" id="subtotal-{idx}">'
                'Subtotal: ${price}</div>\n'
                '    <button class="btn-buy" onclick="orderProduct({idx})">'
                'Order Now &rarr;</button>\n'
                "  </div>\n"
                "</div>"
            ).format(
                idx=idx, name=pname, price=pprice,
                desc=pdesc, img=img_html, default_qty=pqty,
            ))
            try:
                price_f = float(pprice)
            except (ValueError, TypeError):
                price_f = 0.0
            prod_data.append({
                "name": p.get("name", "Product"),
                "price": price_f,
                "qty": pqty,
            })
        product_cards_html = "\n".join(card_parts)
        products_json = json.dumps(prod_data)

    # ── Assemble product grid section ────────────────────────────────────────
    if has_products:
        grid_section = (
            '<div id="products-section">\n'
            '  <div class="page-hero" style="padding-top:1.5rem">\n'
            "    <h1>Our Products</h1>\n"
            "    <p>Select a product and click Order Now to proceed to checkout.</p>\n"
            "  </div>\n"
            '  <div class="products-grid" id="product-grid">\n'
            "    {cards}\n"
            "  </div>\n"
            "</div>\n"
        ).format(cards=product_cards_html)
        checkout_display = "display:none"
    else:
        grid_section = ""
        checkout_display = "display:block"

    # ── Assemble checkout section ────────────────────────────────────────────
    checkout_section = (
        '<div id="checkout-section" style="{checkout_display}">\n'
        "  {back_btn}\n"
        '  <div class="page-hero" style="padding-top:1.5rem">\n'
        "    <h1>Secure Checkout</h1>\n"
        "    <p>Complete your order with anonymous cryptocurrency payment.</p>\n"
        "  </div>\n"
        "\n"
        '  <div class="payment-step" id="order-summary">\n'
        "    <h2>Order Summary</h2>\n"
        "    <table>\n"
        "      <thead><tr>"
        "<th>Product</th><th>Unit Price</th><th>Qty</th><th>Subtotal</th>"
        "</tr></thead>\n"
        "      <tbody><tr>\n"
        '        <td id="display-item">&#8212;</td>\n'
        '        <td id="display-price">&#8212;</td>\n'
        '        <td id="display-qty">&#8212;</td>\n'
        '        <td id="display-subtotal">&#8212;</td>\n'
        "      </tr></tbody>\n"
        "    </table>\n"
        "  </div>\n"
        "\n"
        '  <div class="payment-step">\n'
        "    <h2>Shipping Region</h2>\n"
        '    <div class="form-group">\n'
        '      <label for="continent-select">Your Region</label>\n'
        '      <select id="continent-select" onchange="recalcCheckout()">\n'
        "        {co}"
        "      </select>\n"
        "    </div>\n"
        '    <div class="form-group">\n'
        '      <label for="shipping-select">Shipping Method</label>\n'
        '      <select id="shipping-select" onchange="recalcCheckout()">\n'
        "        {so}"
        "      </select>\n"
        "    </div>\n"
        '    <div class="checkout-breakdown">\n'
        '      <div class="line"><span>Subtotal</span>'
        '<span id="co-subtotal">&#8212;</span></div>\n'
        '      <div class="line"><span>Region multiplier</span>'
        '<span id="co-region">&times;1.00</span></div>\n'
        '      <div class="line"><span>Shipping</span>'
        '<span id="co-shipping">&#8212;</span></div>\n'
        '      <div class="line total"><span>Order Total</span>'
        '<span id="order-total">&#8212;</span></div>\n'
        "    </div>\n"
        "  </div>\n"
        "\n"
        '  <div class="payment-step">\n'
        "    <h2>Live Crypto Prices</h2>\n"
        '    <div class="price-display">\n'
        '      <div class="price-item">\n'
        '        <div class="currency">XMR (Monero)</div>\n'
        '        <div class="amount" id="xmr-amount">&#8230;</div>\n'
        '        <div class="usd-equiv" id="xmr-usd">Loading&hellip;</div>\n'
        "      </div>\n"
        '      <div class="price-item">\n'
        '        <div class="currency">BTC (Bitcoin)</div>\n'
        '        <div class="amount" id="btc-amount">&#8230;</div>\n'
        '        <div class="usd-equiv" id="btc-usd">Loading&hellip;</div>\n'
        "      </div>\n"
        "    </div>\n"
        '    <p style="font-size:0.8rem;color:var(--text-muted)">'
        "Prices fetched live from CoinGecko. Refresh to update.</p>\n"
        "  </div>\n"
        "\n"
        '  <div class="payment-step">\n'
        "    <h2>Pay with Monero (XMR)</h2>\n"
        '    <p style="margin-bottom:1rem;font-size:0.9rem;">Send the exact XMR amount '
        "shown above to the address below.</p>\n"
        '    <div style="text-align:center;margin-bottom:1rem;">\n'
        '      <img id="xmr-qr" src="{qr}" alt="Monero QR Code"\n'
        '           width="200" height="200"\n'
        '           style="border:6px solid #fff;border-radius:var(--radius-sm)">\n'
        "    </div>\n"
        '    <div class="wallet-address-box" id="xmr-address">{wallet}\n'
        '      <button class="copy-btn" onclick="copyAddress()">Copy</button>\n'
        "    </div>\n"
        "  </div>\n"
        "\n"
        '  <div class="payment-step">\n'
        "    <h2>Payment Status</h2>\n"
        '    <div class="status-box">\n'
        '      <div class="status-indicator"></div>\n'
        "      <div><strong>Waiting for Deposit</strong><br>\n"
        '        <span style="font-size:0.85rem;color:var(--text-secondary)">'
        "Send payment to the address above. Once confirmed, contact us with your TXID.</span>\n"
        "      </div>\n"
        "    </div>\n"
        "  </div>\n"
        "\n"
        '  <div class="payment-step">\n'
        "    <h2>After Payment</h2>\n"
        "    <p>Once you have sent your payment, contact us with your transaction ID (TXID) "
        "and shipping address.</p>\n"
        '    <div style="margin-top:1rem;display:flex;gap:1rem;flex-wrap:wrap;">\n'
        "      {wickr_card}\n"
        "      {email_card}\n"
        "    </div>\n"
        "  </div>\n"
        "\n"
        "</div>\n"
    ).format(
        checkout_display=checkout_display,
        back_btn=(
            '<button class="btn-back" onclick="backToProducts()">'
            '&larr; Back to Products</button>'
            if has_products else ""
        ),
        co=_continent_options(config),
        so=_shipping_options(config),
        qr=qr_url,
        wallet=html.escape(wallet),
        wickr_card=wickr_card,
        email_card=email_card,
    )

    page = (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '  <meta charset="UTF-8">\n'
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        '  <meta name="robots" content="noindex, nofollow">\n'
        "  <title>Secure Checkout</title>\n"
        '  <link rel="stylesheet" href="css/style.css">\n'
        "</head>\n"
        "<body>\n"
        "{navbar}\n"
        '<main class="container main-content">\n'
        '<div class="payment-container">\n'
        "{grid_section}"
        "{checkout_section}"
        "</div>\n"
        "</main>\n"
        "{footer}\n"
        "\n"
        "<script>\n"
        "var CONTINENTS = {continent_js};\n"
        "var SHIPPING   = {shipping_js};\n"
        "var PRODUCTS   = {products_json};\n"
        "\n"
        "/* ── Per-product helpers ── */\n"
        "function recalcProduct(idx) {{\n"
        "  var qEl = document.getElementById('qty-' + idx);\n"
        "  var qty = parseInt(qEl ? qEl.value : 1, 10) || 1;\n"
        "  var price = PRODUCTS[idx] ? PRODUCTS[idx].price : 0;\n"
        "  var sub = (price * qty).toFixed(2);\n"
        "  var el = document.getElementById('subtotal-' + idx);\n"
        "  if (el) el.textContent = 'Subtotal: $' + sub;\n"
        "}}\n"
        "\n"
        "function orderProduct(idx) {{\n"
        "  var p = PRODUCTS[idx];\n"
        "  if (!p) return;\n"
        "  var qEl = document.getElementById('qty-' + idx);\n"
        "  var qty = parseInt(qEl ? qEl.value : 1, 10) || 1;\n"
        "  window._checkoutItem  = p.name;\n"
        "  window._checkoutPrice = p.price;\n"
        "  window._checkoutQty   = qty;\n"
        "  document.getElementById('display-item').textContent  = p.name;\n"
        "  document.getElementById('display-price').textContent = '$' + p.price.toFixed(2);\n"
        "  document.getElementById('display-qty').textContent   = qty;\n"
        "  document.getElementById('products-section').style.display = 'none';\n"
        "  document.getElementById('checkout-section').style.display = 'block';\n"
        "  recalcCheckout();\n"
        "}}\n"
        "\n"
        "function backToProducts() {{\n"
        "  document.getElementById('products-section').style.display = 'block';\n"
        "  document.getElementById('checkout-section').style.display = 'none';\n"
        "}}\n"
        "\n"
        "/* ── Checkout total calculation ── */\n"
        "function recalcCheckout() {{\n"
        "  var cSel = document.getElementById('continent-select');\n"
        "  var sSel = document.getElementById('shipping-select');\n"
        "  var mult = cSel ? (CONTINENTS[cSel.value] || 1.0) : 1.0;\n"
        "  var ship = sSel ? (SHIPPING[sSel.value]   || 0)   : 0;\n"
        "  var price = window._checkoutPrice || 0;\n"
        "  var qty   = window._checkoutQty   || 1;\n"
        "  var sub   = price * qty;\n"
        "  var total = (sub * mult) + ship;\n"
        "  var fmt = function (n) {{ return '$' + n.toFixed(2); }};\n"
        "  var elSub  = document.getElementById('co-subtotal');\n"
        "  var elReg  = document.getElementById('co-region');\n"
        "  var elShip = document.getElementById('co-shipping');\n"
        "  var elTot  = document.getElementById('order-total');\n"
        "  var elDisp = document.getElementById('display-subtotal');\n"
        "  if (elSub)  elSub.textContent  = fmt(sub);\n"
        "  if (elReg)  elReg.textContent  = '\\u00d7' + mult.toFixed(2);\n"
        "  if (elShip) elShip.textContent = fmt(ship);\n"
        "  if (elTot)  elTot.textContent  = fmt(total);\n"
        "  if (elDisp) elDisp.textContent = fmt(sub);\n"
        "  if (window._xmrPrice) updateCryptoAmounts(total);\n"
        "}}\n"
        "\n"
        "/* ── Live crypto prices ── */\n"
        "function updateCryptoAmounts(usd) {{\n"
        "  if (!usd || !window._xmrPrice || !window._btcPrice) return;\n"
        "  document.getElementById('xmr-amount').textContent ="
        " (usd / window._xmrPrice).toFixed(6) + ' XMR';\n"
        "  document.getElementById('btc-amount').textContent ="
        " (usd / window._btcPrice).toFixed(8) + ' BTC';\n"
        "  document.getElementById('xmr-usd').textContent ="
        " '1 XMR = $' + window._xmrPrice.toFixed(2);\n"
        "  document.getElementById('btc-usd').textContent ="
        " '1 BTC = $' + window._btcPrice.toLocaleString();\n"
        "}}\n"
        "\n"
        "fetch('https://api.coingecko.com/api/v3/simple/price?ids=monero,bitcoin&vs_currencies=usd')\n"
        "  .then(function (r) {{ return r.json(); }})\n"
        "  .then(function (d) {{\n"
        "    window._xmrPrice = d.monero  ? d.monero.usd  : null;\n"
        "    window._btcPrice = d.bitcoin ? d.bitcoin.usd : null;\n"
        "    var totEl = document.getElementById('order-total');\n"
        "    var tot = totEl ? parseFloat((totEl.textContent || '0').replace('$', '')) : 0;\n"
        "    if (tot > 0) updateCryptoAmounts(tot);\n"
        "  }})\n"
        "  .catch(function () {{\n"
        "    document.getElementById('xmr-usd').textContent = 'Price fetch failed.';\n"
        "    document.getElementById('btc-usd').textContent = '';\n"
        "  }});\n"
        "\n"
        "/* ── Copy wallet address ── */\n"
        "function copyAddress() {{\n"
        "  var addr = {wallet_json};\n"
        "  if (navigator.clipboard) {{\n"
        "    navigator.clipboard.writeText(addr).then(function () {{\n"
        "      var btn = document.querySelector('.copy-btn');\n"
        "      if (btn) {{ btn.textContent = 'Copied!';\n"
        "        setTimeout(function () {{ btn.textContent = 'Copy'; }}, 2000); }}\n"
        "    }});\n"
        "  }} else {{\n"
        "    var ta = document.createElement('textarea');\n"
        "    ta.value = addr; document.body.appendChild(ta);\n"
        "    ta.select(); document.execCommand('copy');\n"
        "    document.body.removeChild(ta);\n"
        "  }}\n"
        "}}\n"
        "\n"
        "/* ── URL param support — skip straight to checkout ── */\n"
        "(function () {{\n"
        "  var p = new URLSearchParams(window.location.search);\n"
        "  var item  = p.get('item');\n"
        "  var qty   = parseInt(p.get('amount') || p.get('qty') || '1', 10) || 1;\n"
        "  var price = parseFloat(p.get('price') || '0');\n"
        "  if (item || price) {{\n"
        "    window._checkoutItem  = item || 'Order';\n"
        "    window._checkoutPrice = price;\n"
        "    window._checkoutQty   = qty;\n"
        "    document.getElementById('display-item').textContent  = window._checkoutItem;\n"
        "    document.getElementById('display-price').textContent = '$' + price.toFixed(2);\n"
        "    document.getElementById('display-qty').textContent   = qty;\n"
        "    var ps = document.getElementById('products-section');\n"
        "    var cs = document.getElementById('checkout-section');\n"
        "    if (ps) ps.style.display = 'none';\n"
        "    if (cs) cs.style.display = 'block';\n"
        "    recalcCheckout();\n"
        "  }}\n"
        "}})();\n"
        "</script>\n"
        "</body>\n"
        "</html>"
    ).format(
        navbar=navbar,
        grid_section=grid_section,
        checkout_section=checkout_section,
        footer=footer,
        continent_js=continent_js,
        shipping_js=shipping_js,
        products_json=products_json,
        wallet_json=json.dumps(wallet),
    )

    payment_path = os.path.join(root, "payment.php")
    logger.log("Generated modern payment.php ({} products)".format(
        len(products) if products else 0
    ))
    write_file_safe(payment_path, page, dry_run)


# ---------------------------------------------------------------------------
# CATEGORY PAGES
# ---------------------------------------------------------------------------

def _product_card(product, root, ref_file):
    """Build a product card HTML snippet."""
    price = product.get("price", "0")
    name = html.escape(product.get("name", "Product"))
    desc = html.escape(product.get("description", "")[:100])
    qty = product.get("quantity", "1")
    name_enc = html.escape(product.get("name", "Product"), quote=True)

    # Decide link target: use filepath only when it differs from the index file
    fp = product.get("filepath", "")
    fp_base = os.path.basename(fp).lower() if fp else ""
    is_index = fp_base in ("index.html", "index.php", "")
    if fp and not is_index:
        rel_path = os.path.relpath(fp, os.path.dirname(ref_file)).replace(os.sep, "/")
        view_btn = '<a href="{}" class="btn-buy" style="margin-bottom:0.4rem;display:block">View Product</a>\n'.format(
            rel_path
        )
    else:
        view_btn = ""

    # Order Now button: onclick reads the adjacent qty input and updates the URL
    order_btn = (
        '<a href="payment.php?item={name}&price={price}&amount={qty}" '
        'class="btn-buy" '
        "onclick=\"var q=this.parentElement.querySelector('input[type=number]');"
        "if(q){{this.href='payment.php?item={name}&price={price}&amount='+q.value;}}\">"
        'Order Now &rarr;</a>'
    ).format(name=name_enc, price=price, qty=qty)

    if product.get("images"):
        img = '<img class="product-image" src="{}" alt="{}" loading="lazy">'.format(
            html.escape(product["images"][0]), name
        )
    else:
        img = (
            '<div class="product-image" style="display:flex;align-items:center;'
            'justify-content:center;color:var(--text-muted);font-size:3rem;">&#128230;</div>'
        )
    return (
        '<div class="product-card" data-price="{price}" data-name="{name}" data-qty="{qty}">\n'
        "  {img}\n"
        '  <div class="product-body">\n'
        '    <div class="product-title">{name}</div>\n'
        '    <div class="product-price" data-base-price="{price}">${price}</div>\n'
        '    <div class="product-desc">{desc}</div>\n'
        '    <div class="qty-row">'
        '<label>Qty:</label>'
        '<input type="number" value="{qty}" min="1" max="999">'
        '</div>\n'
        "    {view_btn}"
        "    {order_btn}\n"
        "  </div>\n"
        "</div>"
    ).format(
        price=price, name=name, qty=qty, img=img, desc=desc,
        view_btn=view_btn, order_btn=order_btn,
    )


def generate_category_page(category, products, root, all_categories, config,
                            logger, dry_run=False):
    cat_title = category.replace("_", " ").title()
    cat_file = os.path.join(root, "category_{}.html".format(category))
    cards = "\n".join(_product_card(p, root, cat_file) for p in products)
    if not cards:
        cards = "<p>No products in this category yet.</p>"

    body = (
        '<div class="page-hero">\n'
        "  <h1>{title}</h1>\n"
        "  <p>{n} product(s) in this category.</p>\n"
        "</div>\n"
        '<div class="sort-controls">\n'
        '  <label for="sort-select">Sort by:</label>\n'
        '  <select id="sort-select">\n'
        '    <option value="">Default</option>\n'
        '    <option value="price-asc">Price: Low to High</option>\n'
        '    <option value="price-desc">Price: High to Low</option>\n'
        '    <option value="name-asc">Name: A&#8211;Z</option>\n'
        '    <option value="name-desc">Name: Z&#8211;A</option>\n'
        '    <option value="qty-desc">Quantity: Most First</option>\n'
        '    <option value="qty-asc">Quantity: Least First</option>\n'
        "  </select>\n"
        "</div>\n"
        '<div class="product-grid" id="product-grid">\n'
        "{cards}\n"
        "</div>"
    ).format(title=cat_title, n=len(products), cards=cards)

    page = build_page_shell(
        "{} — Products".format(cat_title), body, root, cat_file, all_categories, config
    )
    logger.log(
        "Generated category_{}.html ({} products)".format(category, len(products))
    )
    write_file_safe(cat_file, page, dry_run)


# ---------------------------------------------------------------------------
# INDEX PAGE
# ---------------------------------------------------------------------------

def update_index_page(root, categories, all_categories, config, logger, dry_run=False):
    """Inject a category grid and featured products into the existing index, or create one."""
    index_path = None
    for name in ("index.html", "index.php"):
        candidate = os.path.join(root, name)
        if os.path.exists(candidate):
            index_path = candidate
            break

    cat_cards = "".join(
        '<a href="category_{cat}.html" class="category-card">'
        "<h3>{title}</h3>"
        '<div class="count">{n} product(s)</div>'
        "</a>\n".format(
            cat=cat,
            title=cat.replace("_", " ").title(),
            n=len(prods),
        )
        for cat, prods in categories.items()
    )

    section = (
        "<!-- AUTO-GENERATED CATEGORY SECTION -->\n"
        '<section class="category-section" style="margin:2rem 0">\n'
        "  <h2 style=\"margin-bottom:1rem\">Browse by Category</h2>\n"
        '  <div class="category-grid">\n'
        "    {cats}\n"
        "  </div>\n"
        "</section>\n"
        "<!-- END AUTO-GENERATED CATEGORY SECTION -->"
    ).format(cats=cat_cards)

    if index_path:
        content = read_file_safe(index_path)
        # Remove any previously injected section
        content = re.sub(
            r"<!-- AUTO-GENERATED CATEGORY SECTION -->.*?"
            r"<!-- END AUTO-GENERATED CATEGORY SECTION -->",
            "",
            content,
            flags=re.DOTALL,
        )
        if "</main>" in content:
            content = content.replace("</main>", section + "\n</main>", 1)
        elif "</body>" in content:
            content = content.replace("</body>", section + "\n</body>", 1)
        else:
            content += "\n" + section
        logger.log("Updated index page with category section")
        write_file_safe(index_path, content, dry_run)
    else:
        # Build a brand-new index page
        all_products = [p for prods in categories.values() for p in prods]
        new_index = os.path.join(root, "index.html")
        top_cards = "".join(
            _product_card(p, root, new_index) + "\n" for p in all_products[:8]
        )
        body = (
            '<div class="page-hero">\n'
            "  <h1>Welcome to Our Store</h1>\n"
            "  <p>Browse our products and pay anonymously with Monero.</p>\n"
            "</div>\n"
            "<section style=\"margin-bottom:2.5rem\">\n"
            "  <h2 style=\"margin-bottom:1rem\">Shop by Category</h2>\n"
            '  <div class="category-grid">\n'
            "    {cats}\n"
            "  </div>\n"
            "</section>\n"
            "<section>\n"
            "  <h2 style=\"margin-bottom:1rem\">Featured Products</h2>\n"
            '  <div class="sort-controls">\n'
            '    <label for="sort-select">Sort by:</label>\n'
            '    <select id="sort-select">\n'
            '      <option value="">Default</option>\n'
            '      <option value="price-asc">Price: Low to High</option>\n'
            '      <option value="price-desc">Price: High to Low</option>\n'
            '      <option value="name-asc">Name: A&#8211;Z</option>\n'
            '      <option value="name-desc">Name: Z&#8211;A</option>\n'
            "    </select>\n"
            "  </div>\n"
            '  <div class="product-grid" id="product-grid">\n'
            "    {cards}\n"
            "  </div>\n"
            "</section>"
        ).format(cats=cat_cards, cards=top_cards)

        page = build_page_shell(
            "Online Store — Secure Anonymous Shopping",
            body, root, new_index, all_categories, config,
        )
        logger.log("Generated new index.html")
        write_file_safe(new_index, page, dry_run)


# ---------------------------------------------------------------------------
# PRODUCT PAGE ENHANCER
# ---------------------------------------------------------------------------

def enhance_product_page(filepath, product, root, all_categories, config,
                          logger, dry_run=False):
    """Add continent/shipping pricing controls to an existing product page."""
    content = read_file_safe(filepath)
    if not content:
        return False
    if "continent-select" in content:
        return False  # already enhanced

    price = product.get("price", "0")
    name = html.escape(product.get("name", "Product"))
    continent_js = json.dumps(config.get("continent_pricing", {}))
    shipping_js = json.dumps(config.get("shipping_methods", {}))

    pricing_block = build_pricing_controls(config)
    section = (
        "<!-- AUTO-GENERATED PRICING SECTION -->\n"
        '<div class="pricing-section card" style="margin:1.5rem 0">\n'
        "  <h2 style=\"margin-bottom:1rem\">Order</h2>\n"
        "  {pricing}\n"
        '  <div class="form-group">\n'
        '    <label for="qty">Quantity</label>\n'
        '    <input type="number" id="qty" name="amount" value="1" min="1" max="999">\n'
        "  </div>\n"
        '  <div style="padding:1rem;background:var(--bg-primary);'
        'border-radius:var(--radius-sm);margin-bottom:1rem">\n'
        "    <strong>Total: </strong>\n"
        '    <span id="order-total" style="color:var(--accent);font-size:1.2rem;font-weight:700"'
        '          data-item-base-price="{price}">${price}</span>\n'
        '    <span style="color:var(--text-muted);font-size:0.85rem"> (+ shipping)</span>\n'
        "  </div>\n"
        '  <a id="buy-btn"\n'
        '     href="payment.php?item={name}&price={price}&amount=1"\n'
        '     class="btn btn-primary" style="display:block;text-align:center"\n'
        "     onclick=\"this.href='payment.php?item={name}&price={price}&amount='"
        "+(document.getElementById('qty').value||1)\">\n"
        "    Proceed to Payment &rarr;\n"
        "  </a>\n"
        "</div>\n"
        "<script>\n"
        "var CONTINENTS = {continent_js};\n"
        "var SHIPPING   = {shipping_js};\n"
        "function updateProductTotal() {{\n"
        "  var c = document.getElementById('continent-select');\n"
        "  var s = document.getElementById('shipping-select');\n"
        "  var q = document.getElementById('qty');\n"
        "  var mult = c ? (CONTINENTS[c.value] || 1.0) : 1.0;\n"
        "  var ship = s ? (SHIPPING[s.value]   || 0)   : 0;\n"
        "  var qty  = parseInt(q ? q.value : 1, 10) || 1;\n"
        "  var total = ({price} * mult * qty) + ship;\n"
        "  var el = document.getElementById('order-total');\n"
        "  if (el) el.textContent = '$' + total.toFixed(2);\n"
        "  var btn = document.getElementById('buy-btn');\n"
        "  if (btn) btn.href = 'payment.php?item={name}&price='"
        "+ ({price}*mult).toFixed(2) + '&amount=' + qty;\n"
        "}}\n"
        "document.addEventListener('DOMContentLoaded', function () {{\n"
        "  var c = document.getElementById('continent-select');\n"
        "  var s = document.getElementById('shipping-select');\n"
        "  var q = document.getElementById('qty');\n"
        "  if (c) c.addEventListener('change', updateProductTotal);\n"
        "  if (s) s.addEventListener('change', updateProductTotal);\n"
        "  if (q) q.addEventListener('input',  updateProductTotal);\n"
        "}});\n"
        "</script>\n"
        "<!-- END AUTO-GENERATED PRICING SECTION -->"
    ).format(
        pricing=pricing_block,
        price=price,
        name=name,
        continent_js=continent_js,
        shipping_js=shipping_js,
    )

    new_content = content
    # Remove any previously generated section
    new_content = re.sub(
        r"<!-- AUTO-GENERATED PRICING SECTION -->.*?"
        r"<!-- END AUTO-GENERATED PRICING SECTION -->",
        "",
        new_content,
        flags=re.DOTALL,
    )

    if "</body>" in new_content:
        new_content = new_content.replace("</body>", section + "\n</body>", 1)
    else:
        new_content += "\n" + section

    if new_content != content:
        logger.log(
            "Enhanced product page: {}".format(os.path.relpath(filepath, root))
        )
        write_file_safe(filepath, new_content, dry_run)
        return True
    return False


# ---------------------------------------------------------------------------
# CSS / JS INJECTION INTO EXISTING PAGES
# ---------------------------------------------------------------------------

def inject_css_link(filepath, root, logger, dry_run=False):
    """Ensure the page references css/style.css."""
    content = read_file_safe(filepath)
    if not content or "style.css" in content:
        return False

    rel_css = os.path.relpath(
        os.path.join(root, "css", "style.css"), os.path.dirname(filepath)
    ).replace(os.sep, "/")
    tag = '<link rel="stylesheet" href="{}">'.format(rel_css)

    if "</head>" in content:
        new_content = content.replace("</head>", "  {}\n</head>".format(tag), 1)
    elif re.search(r"<head[^>]*>", content, re.IGNORECASE):
        new_content = re.sub(
            r"(<head[^>]*>)", r"\1\n  " + tag, content, count=1, flags=re.IGNORECASE
        )
    else:
        new_content = tag + "\n" + content

    if new_content != content:
        logger.log("Injected CSS link: {}".format(os.path.relpath(filepath, root)))
        write_file_safe(filepath, new_content, dry_run)
        return True
    return False


def inject_js_link(filepath, root, logger, dry_run=False):
    """Ensure the page references js/main.js."""
    content = read_file_safe(filepath)
    if not content or "main.js" in content:
        return False

    rel_js = os.path.relpath(
        os.path.join(root, "js", "main.js"), os.path.dirname(filepath)
    ).replace(os.sep, "/")
    tag = '<script src="{}"></script>'.format(rel_js)

    if "</body>" in content:
        new_content = content.replace("</body>", "  {}\n</body>".format(tag), 1)
    else:
        new_content = content + "\n" + tag + "\n"

    if new_content != content:
        logger.log("Injected JS link: {}".format(os.path.relpath(filepath, root)))
        write_file_safe(filepath, new_content, dry_run)
        return True
    return False


# ---------------------------------------------------------------------------
# WRITE STATIC ASSETS
# ---------------------------------------------------------------------------

def write_css_and_js(root, logger, dry_run=False):
    for subdir, content, name in (
        ("css", DARK_THEME_CSS, "style.css"),
        ("js", MAIN_JS, "main.js"),
    ):
        dirpath = os.path.join(root, subdir)
        if not dry_run:
            os.makedirs(dirpath, exist_ok=True)
        fpath = os.path.join(dirpath, name)
        logger.log("Writing {}/{}".format(subdir, name))
        write_file_safe(fpath, content, dry_run)


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description="website_updater.py — Modernize static HTML/PHP website files."
    )
    ap.add_argument(
        "--dry-run", action="store_true",
        help="Preview what would change without modifying any files.",
    )
    ap.add_argument(
        "--config", default="config.json",
        help="Path to config.json (default: config.json in current directory).",
    )
    ap.add_argument(
        "--root", default=None,
        help="Path to website root directory (overrides config.json website_root).",
    )
    args = ap.parse_args()
    dry_run = args.dry_run

    if dry_run:
        print("=" * 60)
        print("DRY-RUN MODE — No files will be modified.")
        print("=" * 60)

    # ── Config ──────────────────────────────────────────────────────────────
    config_path = args.config
    if not os.path.isabs(config_path):
        config_path = os.path.join(os.getcwd(), config_path)

    log_path = os.path.join(os.path.dirname(config_path), "update_log.txt")
    logger = Logger(log_path, dry_run=dry_run)

    config = load_config(config_path, logger)

    # Determine website root
    if args.root:
        website_root = os.path.abspath(args.root)
    else:
        raw = config.get("website_root", ".")
        website_root = (
            os.path.abspath(raw)
            if os.path.isabs(raw)
            else os.path.abspath(os.path.join(os.path.dirname(config_path), raw))
        )

    if not os.path.isdir(website_root):
        logger.log("Website root does not exist: {}".format(website_root), "ERROR")
        sys.exit(1)

    logger.log("Website root: {}".format(website_root))

    # ── Keywords ────────────────────────────────────────────────────────────
    kw_file = config.get("keywords_file", "keywords.txt")
    if not os.path.isabs(kw_file):
        kw_file = os.path.join(website_root, kw_file)
    keywords = load_keywords(kw_file, logger)

    # ── Step 1: Backup ───────────────────────────────────────────────────────
    logger.log("─── Step 1: Creating backup ───")
    create_backup(website_root, logger, dry_run)

    # ── Step 2: Directory structure ──────────────────────────────────────────
    logger.log("─── Step 2: Ensuring directory structure ───")
    ensure_directory_structure(website_root, logger, dry_run)

    # ── Step 3: Write CSS & JS ───────────────────────────────────────────────
    logger.log("─── Step 3: Writing CSS & JS assets ───")
    write_css_and_js(website_root, logger, dry_run)

    # ── Step 4: Discover files ───────────────────────────────────────────────
    logger.log("─── Step 4: Discovering files ───")
    files = discover_files(website_root)
    logger.log(
        "Found: {} HTML, {} PHP, {} CSS, {} JS, {} images".format(
            len(files["html"]), len(files["php"]),
            len(files["css"]), len(files["js"]), len(files["images"]),
        )
    )

    # ── Step 5: Check & fix broken links ────────────────────────────────────
    logger.log("─── Step 5: Checking and fixing broken links ───")
    file_index = build_file_index(website_root, files)
    total_fixes = sum(
        check_and_fix_links(fp, website_root, file_index, logger, dry_run)
        for fp in files["html"] + files["php"]
    )
    logger.log("Total broken link fixes: {}".format(total_fixes))

    # ── Step 6: Inject CSS / JS links ───────────────────────────────────────
    logger.log("─── Step 6: Injecting CSS/JS references ───")
    for fp in files["html"] + files["php"]:
        inject_css_link(fp, website_root, logger, dry_run)
        inject_js_link(fp, website_root, logger, dry_run)

    # ── Step 7: SEO meta tags ────────────────────────────────────────────────
    logger.log("─── Step 7: Injecting SEO meta tags ───")
    site_url = config.get("site_url", "http://localhost")
    for fp in files["html"] + files["php"]:
        inject_seo_tags(fp, keywords, site_url, logger, dry_run)

    # ── Step 8: Parse products & categorise ─────────────────────────────────
    logger.log("─── Step 8: Parsing products and categorising ───")

    # First, try to extract real products from the index file
    products = []
    index_file = None
    for idx_name in ("index.html", "index.php"):
        candidate = os.path.join(website_root, idx_name)
        if os.path.exists(candidate):
            index_file = candidate
            break

    if index_file:
        products = extract_products(index_file)
        if products:
            src = products[0].get("source", "unknown")
            logger.log("Extracted {} product(s) from index file ({} source)".format(
                len(products), src
            ))
            # Assign filepath and category to each index-extracted product
            for p in products:
                p.setdefault("filepath", index_file)
                p["category"] = _infer_category(
                    p.get("name", ""), p.get("description", ""), ""
                )

    # Fall back to file-based scanning if index extraction yielded nothing
    if not products:
        products = [
            parse_product(fp)
            for fp in files["html"] + files["php"]
            if is_product_file(fp, website_root)
        ]
        logger.log("Found {} product page(s) from file scan".format(len(products)))

    logger.log("Total products: {}".format(len(products)))

    categories = collections.OrderedDict()
    for product in products:
        cat = product["category"]
        categories.setdefault(cat, []).append(product)

    all_category_names = sorted(categories.keys())
    logger.log(
        "Categories: {}".format(
            ", ".join(all_category_names) if all_category_names else "none"
        )
    )

    # ── Step 9: Enhance product pages ───────────────────────────────────────
    logger.log("─── Step 9: Enhancing product pages with pricing controls ───")
    _skip_enhance = {"index.html", "index.php", "payment.php", "payment.html"}
    for product in products:
        fp = product.get("filepath", "")
        if os.path.basename(fp).lower() not in _skip_enhance:
            enhance_product_page(
                fp, product, website_root,
                all_category_names, config, logger, dry_run,
            )

    # ── Step 10: Category pages ──────────────────────────────────────────────
    logger.log("─── Step 10: Generating category pages ───")
    for category, cat_products in categories.items():
        generate_category_page(
            category, cat_products, website_root,
            all_category_names, config, logger, dry_run,
        )

    # ── Step 11: Index page ──────────────────────────────────────────────────
    logger.log("─── Step 11: Updating index page ───")
    update_index_page(
        website_root, categories, all_category_names, config, logger, dry_run
    )

    # ── Step 12: Payment page ────────────────────────────────────────────────
    logger.log("─── Step 12: Generating payment page ───")
    generate_payment_page(
        website_root, config, all_category_names, logger, dry_run,
        products=products,
    )

    # ── Step 13: Sitemap & robots ────────────────────────────────────────────
    logger.log("─── Step 13: Generating sitemap.xml and robots.txt ───")
    files_after = discover_files(website_root)
    generate_sitemap(website_root, files_after, site_url, logger, dry_run)
    generate_robots(website_root, site_url, logger, dry_run)

    # ── Done ─────────────────────────────────────────────────────────────────
    logger.log("─── Complete ───")
    if not dry_run:
        logger.save()
        logger.log("Log saved to: {}".format(log_path))

    print("\n\u2713 website_updater.py finished successfully.")
    if dry_run:
        print("  (DRY-RUN mode \u2014 no files were modified)")
    else:
        print("  Log: {}".format(log_path))


if __name__ == "__main__":
    main()
